var wordBank = wordBank || {};

wordBank["外研版 必修一"] = {

    // =============================================
    //  Unit 1 — 高中新生活 / Senior High
    // =============================================
    "Unit 1": [
        { en: "senior", phonetic: "/ˈsiːniə/", cn: "adj.（地位、水平或级别）高的" },
        { en: "curious", phonetic: "/ˈkjʊəriəs/", cn: "adj.好奇的" },
        { en: "impression", phonetic: "/ɪmˈpreʃ(ə)n/", cn: "n.印象，感想" },
        { en: "campus", phonetic: "/ˈkæmpəs/", cn: "n.校园" },
        { en: "tradition", phonetic: "/trəˈdɪʃ(ə)n/", cn: "n.传统" },
        { en: "facility", phonetic: "/fəˈsɪlɪti/", cn: "n.设施" },
        { en: "impressive", phonetic: "/ɪmˈpresɪv/", cn: "adj.令人钦佩的，给人深刻印象的" },
        { en: "moment", phonetic: "/ˈməʊmənt/", cn: "n.某一时刻" },
        { en: "author", phonetic: "/ˈɔːθə/", cn: "n.作者，作家" },
        { en: "eagerness", phonetic: "/ˈiːɡənəs/", cn: "n.热切，渴望" },
        { en: "explore", phonetic: "/ɪkˈsplɔː/", cn: "v.考察，探险" },
        { en: "engine", phonetic: "/ˈendʒɪn/", cn: "n.发动机，引擎" },
        { en: "insect", phonetic: "/ˈɪnsekt/", cn: "n.昆虫" },
        { en: "collection", phonetic: "/kəˈlekʃ(ə)n/", cn: "n.（一批）收藏品" },
        { en: "organise", phonetic: "/ˈɔːɡənaɪz/", cn: "v.组织" },
        { en: "nudge", phonetic: "/nʌdʒ/", cn: "n.（通常用肘）轻推" },
        { en: "butterfly", phonetic: "/ˈbʌtəflaɪ/", cn: "n.蝴蝶" },
        { en: "breathe", phonetic: "/briːð/", cn: "v.呼吸" },
        { en: "panic", phonetic: "/ˈpænɪk/", cn: "n.惊恐，惊慌" },
        { en: "challenge", phonetic: "/ˈtʃælɪndʒ/", cn: "n.挑战" },
        { en: "pressure", phonetic: "/ˈpreʃə/", cn: "n.压力" },
        { en: "calm", phonetic: "/kɑːm/", cn: "adj.镇静的，沉着的" },
        { en: "description", phonetic: "/dɪˈskrɪpʃ(ə)n/", cn: "n.描述，描写" },
        { en: "confident", phonetic: "/ˈkɒnfɪdənt/", cn: "adj.有信心的，自信的" },
        { en: "poster", phonetic: "/ˈpəʊstə/", cn: "n.海报" },
        { en: "badminton", phonetic: "/ˈbædmɪntən/", cn: "n.羽毛球" },
        { en: "drama", phonetic: "/ˈdrɑːmə/", cn: "n.戏剧" },
        { en: "band", phonetic: "/bænd/", cn: "n.乐队，乐团" },
        { en: "debate", phonetic: "/dɪˈbeɪt/", cn: "n.讨论，辩论" },
        { en: "gym", phonetic: "/dʒɪm/", cn: "n.体育馆，健身房" },
        { en: "piano", phonetic: "/piˈænəʊ/", cn: "n.钢琴" },
        { en: "stage", phonetic: "/steɪdʒ/", cn: "n.舞台" },
        { en: "photography", phonetic: "/fəˈtɒɡrəfi/", cn: "n.摄影" },
        { en: "inner", phonetic: "/ˈɪnə/", cn: "adj.内心的，隐藏的" },
        { en: "argue", phonetic: "/ˈɑːɡjuː/", cn: "v.争论，争辩" },
        { en: "topic", phonetic: "/ˈtɒpɪk/", cn: "n.话题，论题" },
        { en: "sharp", phonetic: "/ʃɑːp/", cn: "adj.敏锐的，聪明的" },
        { en: "dinosaur", phonetic: "/ˈdaɪnəsɔː/", cn: "n.恐龙" },
        { en: "dolphin", phonetic: "/ˈdɒlfɪn/", cn: "n.海豚" },
        { en: "intelligent", phonetic: "/ɪnˈtelɪdʒ(ə)nt/", cn: "adj.有智慧的，聪明的" },
        { en: "investigate", phonetic: "/ɪnˈvestɪɡeɪt/", cn: "v.查明，调查" },
        { en: "various", phonetic: "/ˈveəriəs/", cn: "adj.各种各样的" },
        { en: "volunteer", phonetic: "/ˌvɒlənˈtɪə/", cn: "n.志愿者" },
        { en: "gain", phonetic: "/ɡeɪn/", cn: "v.获得，赢得" },
        { en: "apply", phonetic: "/əˈplaɪ/", cn: "v.申请" },
        { en: "schedule", phonetic: "/ˈʃedjuːl/", cn: "n.计划表，日程表" },
        { en: "award", phonetic: "/əˈwɔːd/", cn: "n.奖，奖赏" },
        { en: "opportunity", phonetic: "/ˌɒpəˈtjuːnɪti/", cn: "n.机会，时机" },
        { en: "hint", phonetic: "/hɪnt/", cn: "n.有益的建议" },
        { en: "subscribe", phonetic: "/səbˈskraɪb/", cn: "v.订阅" },
        { en: "view", phonetic: "/vjuː/", cn: "n.（一次）观看" },
        { en: "former", phonetic: "/ˈfɔːmə/", cn: "adj.从前的" },
        { en: "graduate", phonetic: "/ˈɡrædʒueɪt/", cn: "v.毕业" },
        { en: "orientation", phonetic: "/ˌɔːriənˈteɪʃ(ə)n/", cn: "n.培训，迎新" },
        { en: "frightened", phonetic: "/ˈfraɪtnd/", cn: "adj.受惊的，害怕的" },
        { en: "sight", phonetic: "/saɪt/", cn: "n.看到，看见" },
        { en: "figure", phonetic: "/ˈfɪɡə/", cn: "v.认为，以为" },
        { en: "select", phonetic: "/səˈlekt/", cn: "v.挑选，选择" },
        { en: "particular", phonetic: "/pəˈtɪkjʊlə/", cn: "adj.特定的，特指的" },
        { en: "rainbow", phonetic: "/ˈreɪnbəʊ/", cn: "n.彩虹" },
        { en: "neat", phonetic: "/niːt/", cn: "adj.好的，令人愉快的" },
        { en: "specific", phonetic: "/spəˈsɪfɪk/", cn: "adj.具体的，特定的" },
        { en: "refer", phonetic: "/rɪˈfɜː/", cn: "v.提到，谈到" },
        { en: "journal", phonetic: "/ˈdʒɜːnl/", cn: "n.日记，日志" },
        { en: "junior", phonetic: "/ˈdʒuːniə/", cn: "adj.低年级的" },
        { en: "struggle", phonetic: "/ˈstrʌɡ(ə)l/", cn: "v.奋斗，拼搏" },
        { en: "memorise", phonetic: "/ˈmeməraɪz/", cn: "v.记住，熟记" },
        { en: "skateboarding", phonetic: "/ˈskeɪtbɔːdɪŋ/", cn: "n.滑板运动" },
        { en: "forward", phonetic: "/ˈfɔːwəd/", cn: "adv.向前" },
        { en: "committee", phonetic: "/kəˈmɪti/", cn: "n.委员会" },
        { en: "improve", phonetic: "/ɪmˈpruːv/", cn: "v.改善，改进" },
        { en: "rate", phonetic: "/reɪt/", cn: "v.对……作评估，评价" },
        { en: "performance", phonetic: "/pəˈfɔːməns/", cn: "n.表现" },
        { en: "exchange", phonetic: "/ɪksˈtʃeɪndʒ/", cn: "v.交流" },
        // 短语
        { en: "senior high", phonetic: "", cn: "高中" },
        { en: "one by one", phonetic: "", cn: "依次地，一个接一个地" },
        { en: "butterflies in one's stomach", phonetic: "", cn: "情绪紧张，心里发慌" },
        { en: "in panic", phonetic: "", cn: "惊慌地" },
        { en: "pm", phonetic: "/piːˈem/", cn: "下午" },
        { en: "Orientation Day", phonetic: "", cn: "迎新日" },
        { en: "go all out", phonetic: "", cn: "全力以赴，竭尽全力" },
        { en: "in particular", phonetic: "", cn: "尤其，特别" },
        { en: "refer to", phonetic: "", cn: "提到，谈到" },
        { en: "look forward to", phonetic: "", cn: "（兴奋地）期待，盼望" }
    ],

    // =============================================
    //  Unit 2 — 语言与文化 / Language
    // =============================================
    "Unit 2": [
        { en: "title", phonetic: "/ˈtaɪtəl/", cn: "n.题目，标题" },
        { en: "ham", phonetic: "/hæm/", cn: "n.火腿" },
        { en: "eggplant", phonetic: "/ˈeɡplɑːnt/", cn: "n.茄子" },
        { en: "pine", phonetic: "/paɪn/", cn: "n.松树" },
        { en: "pineapple", phonetic: "/ˈpaɪnˌæpəl/", cn: "n.菠萝" },
        { en: "sculpt", phonetic: "/skʌlpt/", cn: "v.雕刻，雕塑" },
        { en: "sculpture", phonetic: "/ˈskʌlptʃə/", cn: "n.雕像，雕刻品" },
        { en: "seasick", phonetic: "/ˈsiːsɪk/", cn: "adj.晕船的" },
        { en: "airsick", phonetic: "/ˈeəsɪk/", cn: "adj.晕机的" },
        { en: "carsick", phonetic: "/ˈkɑːsɪk/", cn: "adj.晕车的" },
        { en: "homesick", phonetic: "/ˈhəʊmsɪk/", cn: "adj.想家的" },
        { en: "opposing", phonetic: "/əˈpəʊzɪŋ/", cn: "adj.（观点、意见等）相反的，相对立的" },
        { en: "behavior", phonetic: "/bɪˈheɪvjə/", cn: "n.举止，行为" },
        { en: "confusing", phonetic: "/kənˈfjuːzɪŋ/", cn: "adj.令人困惑的" },
        { en: "capitalized", phonetic: "/ˈkæpɪtlaɪzd/", cn: "adj.大写的" },
        { en: "unique", phonetic: "/juːˈniːk/", cn: "adj.独一无二的，独特的" },
        { en: "alarm", phonetic: "/əˈlɑːm/", cn: "n.警报器；闹钟" },
        { en: "reflect", phonetic: "/rɪˈflekt/", cn: "v.显示，反映" },
        { en: "creativity", phonetic: "/kriːeɪˈtɪvɪti/", cn: "n.创造性，创造力" },
        { en: "visible", phonetic: "/ˈvɪzɪb(ə)l/", cn: "adj.看得见的，可见的" },
        { en: "creative", phonetic: "/kriˈeɪtɪv/", cn: "adj.创造（性）的" },
        { en: "type", phonetic: "/taɪp/", cn: "n.类型，种类" },
        { en: "unfamiliar", phonetic: "/ˌʌnfəˈmɪliə/", cn: "adj.不熟悉的，不了解的" },
        { en: "contact", phonetic: "/ˈkɒntækt/", cn: "v.联系，联络" },
        { en: "organization", phonetic: "/ˌɔːɡənaɪˈzeɪʃ(ə)n/", cn: "n.组织，团体，机构" },
        { en: "likely", phonetic: "/ˈlaɪkli/", cn: "adj.可能的，可能发生的" },
        { en: "subway", phonetic: "/ˈsʌbweɪ/", cn: "n.地铁" },
        { en: "highway", phonetic: "/ˈhaɪweɪ/", cn: "n.公路" },
        { en: "motorway", phonetic: "/ˈməʊtəweɪ/", cn: "n.高速公路" },
        { en: "gas", phonetic: "/ɡæs/", cn: "n.汽油" },
        { en: "petrol", phonetic: "/ˈpetrəl/", cn: "n.汽油" },
        { en: "apartment", phonetic: "/əˈpɑːtmənt/", cn: "n.一套住房，公寓套房" },
        { en: "flat", phonetic: "/flæt/", cn: "n.一套住房，公寓套房" },
        { en: "elevator", phonetic: "/ˈelɪveɪtə/", cn: "n.电梯，升降机" },
        { en: "context", phonetic: "/ˈkɒntekst/", cn: "n.上下文，语境" },
        { en: "addition", phonetic: "/əˈdɪʃ(ə)n/", cn: "n.增加物，添加物" },
        { en: "forum", phonetic: "/ˈfɔːrəm/", cn: "n.论坛，讨论区" },
        { en: "resource", phonetic: "/rɪˈzɔːs/", cn: "n.资料，（教学）资源" },
        { en: "misadventure", phonetic: "/ˌmɪsədˈventʃə/", cn: "n.事故，灾难" },
        { en: "remind", phonetic: "/rɪˈmaɪnd/", cn: "v.提醒，使……想起" },
        { en: "rather", phonetic: "/ˈrɑːdə/", cn: "adv.相当，颇" },
        { en: "comment", phonetic: "/ˈkɒment/", cn: "n.评论" },
        { en: "frog", phonetic: "/frɒɡ/", cn: "n.蛙，青蛙" },
        { en: "throat", phonetic: "/θrəʊt/", cn: "n.喉咙，咽喉" },
        { en: "downtown", phonetic: "/ˌdaʊnˈtaʊn/", cn: "adj.在城镇中心区的，在闹市区的" },
        { en: "boot", phonetic: "/buːt/", cn: "n.靴子" },
        { en: "entrance", phonetic: "/ˈentrəns/", cn: "n.大门（口），入口（处）" },
        { en: "section", phonetic: "/ˈsekʃ(ə)n/", cn: "n.区域" },
        { en: "exit", phonetic: "/ˈeɡzɪt/", cn: "n.出口" },
        { en: "actually", phonetic: "/ˈæktʃuəli/", cn: "adv.事实上，实际上" },
        { en: "downstairs", phonetic: "/ˌdaʊnˈsteəz/", cn: "adv.在楼下" },
        { en: "wicked", phonetic: "/ˈwɪkɪd/", cn: "adj.缺德的，邪恶的；很棒的，极好的" },
        { en: "odd", phonetic: "/ɒd/", cn: "adj.奇特的，古怪的" },
        { en: "negative", phonetic: "/ˈneɡətɪv/", cn: "adj.消极的，负面的" },
        { en: "error", phonetic: "/ˈerə/", cn: "n.错误，谬误" },
        { en: "intend", phonetic: "/ɪnˈtend/", cn: "v.计划，打算" },
        { en: "informal", phonetic: "/ɪnˈfɔːm(ə)l/", cn: "adj.非正式的" },
        { en: "recognise", phonetic: "/ˈrekəɡnaɪz/", cn: "v.认识，辨认出" },
        { en: "base", phonetic: "/beɪs/", cn: "v.以……为基础" },
        { en: "aware", phonetic: "/əˈweə/", cn: "adj.意识到的，明白的" },
        // 短语
        { en: "burn up", phonetic: "", cn: "烧毁，烧尽" },
        { en: "burn down", phonetic: "", cn: "烧毁" },
        { en: "wind up", phonetic: "", cn: "给（机械）上发条；使（活动、会议等）结束" },
        { en: "come across", phonetic: "", cn: "偶然发现" },
        { en: "have a frog in one's throat", phonetic: "", cn: "（尤因喉咙痛）说话困难" },
        { en: "be aware of", phonetic: "", cn: "意识到，察觉到" }
    ],

    // =============================================
    //  Unit 3 — 人物与职业 / People & Careers
    // =============================================
    "Unit 3": [
        { en: "character", phonetic: "/ˈkærɪktə/", cn: "n.（书、剧本、电影等中的）人物，角色" },
        { en: "approach", phonetic: "/əˈprəʊtʃ/", cn: "v.走近，靠近" },
        { en: "chat", phonetic: "/tʃæt/", cn: "n.闲谈，聊天" },
        { en: "focus", phonetic: "/ˈfəʊkəs/", cn: "v.（把……）集中（于）" },
        { en: "career", phonetic: "/kəˈrɪə/", cn: "n.职业，事业" },
        { en: "lawyer", phonetic: "/ˈlɔːjə/", cn: "n.律师" },
        { en: "assume", phonetic: "/əˈsjuːm/", cn: "v.假定，假设，认为" },
        { en: "respect", phonetic: "/rɪˈspekt/", cn: "v.尊敬，敬重" },
        { en: "studio", phonetic: "/ˈstjuːdiəʊ/", cn: "n.（音乐）录音室" },
        { en: "court", phonetic: "/kɔːt/", cn: "n.法院，法庭" },
        { en: "ignore", phonetic: "/ɪɡˈnɔː/", cn: "v.忽视，不理" },
        { en: "professional", phonetic: "/prəˈfeʃ(ə)nəl/", cn: "adj.职业的，专业的" },
        { en: "suit", phonetic: "/suːt/", cn: "v.适合" },
        { en: "talent", phonetic: "/ˈtælənt/", cn: "n.天赋，才能" },
        { en: "option", phonetic: "/ˈɒpʃ(ə)n/", cn: "n.选择，可选择的东西" },
        { en: "sigh", phonetic: "/saɪ/", cn: "n.叹气，叹息" },
        { en: "curtain", phonetic: "/ˈkɜːtn/", cn: "n.（舞台上的）幕，帷幕" },
        { en: "generation", phonetic: "/ˌdʒenəˈreɪʃ(ə)n/", cn: "n.一代（人）" },
        { en: "gap", phonetic: "/ɡæp/", cn: "n.差距，差别" },
        { en: "currently", phonetic: "/ˈkʌrəntli/", cn: "adv.现时，当前" },
        { en: "regularly", phonetic: "/ˈreɡjʊləli/", cn: "adv.经常" },
        { en: "responsible", phonetic: "/rɪˈspɒnsɪb(ə)l/", cn: "adj.负有责任的" },
        { en: "memory", phonetic: "/ˈmem(ə)ri/", cn: "n.记忆，回忆" },
        { en: "nowadays", phonetic: "/ˈnaʊədeɪz/", cn: "adv.现今，现时" },
        { en: "jaw", phonetic: "/dʒɔː/", cn: "n.下巴，下颌" },
        { en: "beard", phonetic: "/bɪəd/", cn: "n.胡须" },
        { en: "skin", phonetic: "/skɪn/", cn: "n.皮肤" },
        { en: "jogging", phonetic: "/ˈdʒɒɡɪŋ/", cn: "n.慢跑锻炼" },
        { en: "slim", phonetic: "/slɪm/", cn: "adj.苗条的，修长的" },
        { en: "cheek", phonetic: "/tʃiːk/", cn: "n.面颊，脸颊" },
        { en: "nation", phonetic: "/ˈneɪʃ(ə)n/", cn: "n.国家" },
        { en: "aim", phonetic: "/eɪm/", cn: "v.力求达到" },
        { en: "issue", phonetic: "/ˈɪʃuː/", cn: "n.议题；争论的问题" },
        { en: "theme", phonetic: "/θiːm/", cn: "n.主题" },
        { en: "observe", phonetic: "/əbˈzɜːv/", cn: "v.庆祝，过（节日、生日等）" },
        { en: "range", phonetic: "/reɪndʒ/", cn: "n.一系列" },
        { en: "event", phonetic: "/ɪˈvent/", cn: "n.活动" },
        { en: "apologise", phonetic: "/əˈpɒlədʒaɪz/", cn: "v.道歉" },
        { en: "stress", phonetic: "/stres/", cn: "n.重音，重读" },
        { en: "impact", phonetic: "/ˈɪmpækt/", cn: "n.作用，影响" },
        { en: "strength", phonetic: "/streŋθ/", cn: "n.强烈程度" },
        { en: "admire", phonetic: "/ədˈmaɪə/", cn: "v.钦佩，赞美，羡慕" },
        { en: "judge", phonetic: "/dʒʌdʒ/", cn: "v.认为，判断" },
        { en: "settle", phonetic: "/ˈsetl/", cn: "v.和解，结束（争论）" },
        { en: "feature", phonetic: "/ˈfiːtʃə/", cn: "n.（报纸或杂志的）特写" },
        { en: "typically", phonetic: "/ˈtɪpɪkli/", cn: "adv.一般，通常" },
        { en: "individual", phonetic: "/ˌɪndɪˈvɪdʒuəl/", cn: "adj.独特的，与众不同的" },
        { en: "style", phonetic: "/staɪl/", cn: "n.风格" },
        { en: "extra", phonetic: "/ˈekstrə/", cn: "adj.额外的，另外的" },
        { en: "detail", phonetic: "/ˈdiːteɪl/", cn: "n.细节，细微之处" },
        { en: "contain", phonetic: "/kənˈteɪn/", cn: "v.包含，含有" },
        { en: "summary", phonetic: "/ˈsʌməri/", cn: "n.总结，概要" },
        { en: "powerful", phonetic: "/ˈpaʊəf(ə)l/", cn: "adj.强有力的" },
        { en: "triathlon", phonetic: "/traɪˈæθlən/", cn: "n.铁人三项运动" },
        { en: "series", phonetic: "/ˈsɪəriːz/", cn: "n.系列比赛" },
        { en: "track", phonetic: "/træk/", cn: "n.跑道" },
        { en: "media", phonetic: "/ˈmiːdiə/", cn: "n.新闻媒体，传媒" },
        { en: "obviously", phonetic: "/ˈɒbviəsli/", cn: "adv.明显地，显而易见地" },
        { en: "despite", phonetic: "/dɪˈspaɪt/", cn: "prep.尽管，虽然" },
        { en: "throughout", phonetic: "/θruːˈaʊt/", cn: "prep.在整个期间，自始至终" },
        { en: "entire", phonetic: "/ɪnˈtaɪə/", cn: "adj.全部的，整个的" },
        { en: "enormously", phonetic: "/ɪˈnɔːməsli/", cn: "adv.非常，极其" },
        { en: "positive", phonetic: "/ˈpɒzɪtɪv/", cn: "adj.好的，积极的" },
        { en: "million", phonetic: "/ˈmɪlɪʃn/", cn: "num.百万" },
        { en: "disqualify", phonetic: "/dɪsˈkwɒlɪfaɪ/", cn: "v.取消……的资格" },
        { en: "athlete", phonetic: "/ˈæθliːt/", cn: "n.运动员，田径运动员" },
        { en: "medal", phonetic: "/ˈmedl/", cn: "n.奖牌，勋章" },
        { en: "somehow", phonetic: "/ˈsʌmhaʊ/", cn: "adv.用某种方法，不知怎的" },
        { en: "indeed", phonetic: "/ɪnˈdiːd/", cn: "adv.当然，确实" },
        { en: "onto", phonetic: "/ˈɒntə/", cn: "prep.到……上，向……上" },
        // 短语
        { en: "settle for", phonetic: "", cn: "勉强接受，将就" },
        { en: "in the lead", phonetic: "", cn: "领先" }
    ],

    // =============================================
    //  Unit 4 — 科技与生活 / Technology & Life
    // =============================================
    "Unit 4": [
        { en: "forever", phonetic: "/fərˈevə/", cn: "adv.永远" },
        { en: "familiar", phonetic: "/fəˈmɪliə/", cn: "adj.熟悉的" },
        { en: "adventure", phonetic: "/ədˈventʃə/", cn: "n.历险（经历），奇遇" },
        { en: "prefer", phonetic: "/prɪˈfɜː/", cn: "v.更喜欢" },
        { en: "deliver", phonetic: "/dɪˈliːvə/", cn: "v.递送，传送" },
        { en: "advance", phonetic: "/ədˈvɑːns/", cn: "n.进步，进展" },
        { en: "significantly", phonetic: "/sɪɡˈnɪfɪkəntli/", cn: "adv.重大地，显著地" },
        { en: "maintain", phonetic: "/meɪnˈteɪn/", cn: "v.保持，维持" },
        { en: "wifi", phonetic: "/ˈwaɪ faɪ/", cn: "n.无线网络，无线上网" },
        { en: "click", phonetic: "/klɪk/", cn: "v.点击（鼠标）" },
        { en: "digital", phonetic: "/ˈdɪdʒɪtl/", cn: "adj.数字的，数码的" },
        { en: "enable", phonetic: "/ɪˈneɪb(ə)l/", cn: "v.使可能，使发生" },
        { en: "unusual", phonetic: "/ʌnˈjuːʒuəl/", cn: "adj.异常的，不平常的" },
        { en: "site", phonetic: "/saɪt/", cn: "n.网站" },
        { en: "tend", phonetic: "/tend/", cn: "v.易于做某事" },
        { en: "update", phonetic: "/ˈʌpdeɪt/", cn: "n.最新消息" },
        { en: "saying", phonetic: "/ˈseɪɪŋ/", cn: "n.格言，谚语，警句" },
        { en: "criminal", phonetic: "/ˈkrɪmɪn(ə)l/", cn: "n.罪犯" },
        { en: "bathwater", phonetic: "/ˈbɑːθwɔːtə/", cn: "n.浴水，洗澡水" },
        { en: "acquire", phonetic: "/əˈkwaɪə/", cn: "v.获得，得到" },
        { en: "goods", phonetic: "/ɡʊdz/", cn: "n.商品" },
        { en: "prove", phonetic: "/pruːv/", cn: "v.证明，证实" },
        { en: "illustrate", phonetic: "/ˈɪləstreɪt/", cn: "v.（举例）说明，阐明" },
        { en: "diagram", phonetic: "/ˈdaɪəɡræm/", cn: "n.图解，示意图" },
        { en: "inspiring", phonetic: "/ɪnˈspaɪərɪŋ/", cn: "adj.鼓舞人心的，启发灵感的" },
        { en: "teenager", phonetic: "/ˈtiːneɪdʒə/", cn: "n.青少年" },
        { en: "pour", phonetic: "/pɔː/", cn: "v.灌，注，倒" },
        { en: "pot", phonetic: "/pɒt/", cn: "n.锅" },
        { en: "gram", phonetic: "/ɡræm/", cn: "n.克" },
        { en: "pack", phonetic: "/pæk/", cn: "n.小盒，小包" },
        { en: "comfort", phonetic: "/ˈkʌmfət/", cn: "n.安慰，慰藉" },
        { en: "patience", phonetic: "/ˈpeɪʃ(ə)ns/", cn: "n.耐心" },
        { en: "passion", phonetic: "/ˈpæʃ(ə)n/", cn: "n.强烈的情感，激情" },
        { en: "generosity", phonetic: "/ˌdʒenəˈrɒsɪti/", cn: "n.慷慨，大方" },
        { en: "slice", phonetic: "/slaɪs/", cn: "n.片，薄片" },
        { en: "humour", phonetic: "/ˈhjuːmə/", cn: "n.幽默感" },
        { en: "quality", phonetic: "/ˈkwɒlɪti/", cn: "n.素质，品德" },
        { en: "anxious", phonetic: "/ˈæŋkʃəs/", cn: "adj.焦虑的，不安的" },
        { en: "distance", phonetic: "/ˈdɪstəns/", cn: "v.使与……保持距离，撇清和……的关系" },
        { en: "postpone", phonetic: "/pəʊstˈpəʊn/", cn: "v.延期，推迟" },
        { en: "ordinary", phonetic: "/ˈɔːd(ə)nəri/", cn: "adj.普通的，平常的" },
        { en: "scar", phonetic: "/skɑː/", cn: "n.伤疤" },
        { en: "dine", phonetic: "/daɪn/", cn: "v.进餐" },
        { en: "chum", phonetic: "/tʃʌm/", cn: "n.好朋友" },
        { en: "chap", phonetic: "/tʃæp/", cn: "n.小伙子，家伙" },
        { en: "fortune", phonetic: "/ˈfɔːtʃ(ə)n/", cn: "n.大笔的钱，巨款" },
        { en: "drag", phonetic: "/dræɡ/", cn: "v.拖，拉" },
        { en: "destiny", phonetic: "/ˈdestɪni/", cn: "n.命运，天命" },
        { en: "correspond", phonetic: "/ˌkɒrɪˈspɒnd/", cn: "v.通信" },
        { en: "proposition", phonetic: "/ˌprɒpəˈzɪʃ(ə)n/", cn: "n.事业，生意" },
        { en: "hustle", phonetic: "/ˈhʌs(ə)l/", cn: "v.拚命干，努力干" },
        { en: "staunch", phonetic: "/stɔːntʃ/", cn: "adj.坚定的，忠实可靠的" },
        { en: "partner", phonetic: "/ˈpɑːtnə/", cn: "n.伙伴，搭档" },
        { en: "excerpt", phonetic: "/ˈeksɜːpt/", cn: "n.摘录，节录" },
        { en: "appointed", phonetic: "/əˈpɔɪntɪd/", cn: "adj.约定的，指定的" },
        { en: "strike", phonetic: "/straɪk/", cn: "v.划（火柴）" },
        { en: "cigar", phonetic: "/sɪˈɡɑː/", cn: "n.雪茄烟" },
        { en: "plain", phonetic: "/pleɪn/", cn: "adj.简单的，朴素的" },
        { en: "scene", phonetic: "/siːn/", cn: "n.场景" },
        { en: "bitterly", phonetic: "/ˈbɪtəli/", cn: "adv.痛苦地，愤恨地" },
        { en: "ashamed", phonetic: "/əˈʃeɪmd/", cn: "adj.感到不好意思的，难为情的" },
        { en: "unfold", phonetic: "/ʌnˈfəʊld/", cn: "v.（卷着的东西）展开，打开" },
        { en: "location", phonetic: "/ləʊˈkeɪʃ(ə)n/", cn: "n.地点，位置" },
        { en: "surroundings", phonetic: "/səˈraʊndɪŋz/", cn: "n.周围的事物，环境" },
        { en: "personality", phonetic: "/ˌpɜːsəˈnælɪti/", cn: "n.个性，性格" },
        { en: "atmosphere", phonetic: "/ˈætməsfɪə/", cn: "n.气氛，氛围，环境" },
        // 短语
        { en: "lose track of", phonetic: "", cn: "不了解……的情况，不了解……的动态" },
        { en: "thanks to", phonetic: "", cn: "归功于……，多亏……" },
        { en: "throw the baby out with the bathwater", phonetic: "", cn: "不分良莠一起抛弃" },
        { en: "social media", phonetic: "", cn: "社交媒体" },
        { en: "make one's fortune", phonetic: "", cn: "发财" },
        { en: "ought to", phonetic: "", cn: "应该，应当" },
        { en: "turn up", phonetic: "", cn: "（意外地或终于）出现" }
    ],

    // =============================================
    //  Unit 5 — 自然与动物 / Nature
    // =============================================
    "Unit 5": [
        { en: "charity", phonetic: "/ˈtʃærɪti/", cn: "n.慈善机构，慈善团体" },
        { en: "monarch", phonetic: "/ˈmɒnək/", cn: "n.君主，国王" },
        { en: "Atlantic", phonetic: "/ətˈlæntɪk/", cn: "adj.大西洋的" },
        { en: "whale", phonetic: "/weɪl/", cn: "n.鲸" },
        { en: "annual", phonetic: "/ˈænjuəl/", cn: "adj.一年一度的，每年的" },
        { en: "migration", phonetic: "/maɪˈɡreɪʃ(ə)n/", cn: "n.迁徙" },
        { en: "migrate", phonetic: "/maɪˈɡreɪt/", cn: "v.移栖，迁徙" },
        { en: "seek", phonetic: "/siːk/", cn: "v.寻找，寻求" },
        { en: "professor", phonetic: "/prəˈfesə/", cn: "n.教授" },
        { en: "measure", phonetic: "/ˈmeʒə/", cn: "v.量，测量" },
        { en: "position", phonetic: "/pəˈzɪʃ(ə)n/", cn: "n.位置" },
        { en: "determine", phonetic: "/dɪˈtɜːmɪn/", cn: "v.测定，确定" },
        { en: "eventually", phonetic: "/ɪˈventʃuəli/", cn: "adv.终于，最终" },
        { en: "solution", phonetic: "/səˈluːʃ(ə)n/", cn: "n.解决，解决方法" },
        { en: "mystery", phonetic: "/ˈmɪst(ə)ri/", cn: "n.难以理解的事物，谜" },
        { en: "amazing", phonetic: "/əˈmeɪzɪŋ/", cn: "adj.惊人的，了不起的" },
        { en: "crash", phonetic: "/kræʃ/", cn: "v.暴跌" },
        { en: "per cent", phonetic: "/pəˈsent/", cn: "n.百分比" },
        { en: "destroy", phonetic: "/dɪˈstrɔɪ/", cn: "v.破坏，毁掉" },
        { en: "chemical", phonetic: "/ˈkemɪk(ə)l/", cn: "n.化学品" },
        { en: "caterpillar", phonetic: "/ˈkætəpɪlə/", cn: "n.毛虫" },
        { en: "creature", phonetic: "/ˈkriːtʃə/", cn: "n.生物，动物" },
        { en: "survive", phonetic: "/səˈvaɪv/", cn: "v.活下来，幸存" },
        { en: "effect", phonetic: "/ɪˈfekt/", cn: "n.影响，结果" },
        { en: "accommodation", phonetic: "/əˌkɒməˈdeɪʃ(ə)n/", cn: "n.住处，工作场所" },
        { en: "idiom", phonetic: "/ˈɪdiəm/", cn: "n.习语，成语" },
        { en: "authority", phonetic: "/ɔːˈθɒrɪti/", cn: "n.当权，权力" },
        { en: "source", phonetic: "/sɔːs/", cn: "n.来源，出处" },
        { en: "found", phonetic: "/faʊnd/", cn: "v.创立，创建" },
        { en: "photographer", phonetic: "/fəˈtɒɡrəfə/", cn: "n.摄影师" },
        { en: "button", phonetic: "/ˈbʌtn/", cn: "n.按钮" },
        { en: "recover", phonetic: "/rɪˈkʌvə/", cn: "v.（从糟糕经历中）恢复" },
        { en: "shock", phonetic: "/ʃɒk/", cn: "n.吃惊，震惊" },
        { en: "element", phonetic: "/ˈelɪmənt/", cn: "n.基本部分，要素" },
        { en: "variety", phonetic: "/vəˈraɪəti/", cn: "n.多样化，变化" },
        { en: "per", phonetic: "/pə/", cn: "prep.每" },
        { en: "encounter", phonetic: "/ɪnˈkaʊntə/", cn: "n.意外的相遇，邂逅" },
        { en: "path", phonetic: "/pɑːθ/", cn: "n.小径，小道" },
        { en: "breathtaking", phonetic: "/ˈbreθteɪkɪŋ/", cn: "adj.令人惊叹的" },
        { en: "eagle", phonetic: "/ˈiːɡ(ə)l/", cn: "n.鹰" },
        { en: "concentrate", phonetic: "/ˈkɒns(ə)ntreɪt/", cn: "v.专注，专心" },
        { en: "freeze", phonetic: "/friːz/", cn: "v.突然停止，呆住" },
        { en: "stare", phonetic: "/steə/", cn: "v.凝视，盯着看" },
        { en: "capture", phonetic: "/ˈkæptʃə/", cn: "v.（用文字或图片）记录，捕捉" },
        { en: "image", phonetic: "/ˈɪmɪdʒ/", cn: "n.图像，影像" },
        { en: "reaction", phonetic: "/riˈækʃən/", cn: "n.（对某一情形或事件的）反应" },
        { en: "file", phonetic: "/faɪl/", cn: "n.档案，文件" },
        // 短语
        { en: "monarch butterfly", phonetic: "", cn: "黑脉金斑蝶" },
        { en: "flow chart", phonetic: "", cn: "流程图，作业图" },
        { en: "kill two birds with one stone", phonetic: "", cn: "一举两得，一箭双雕" },
        { en: "when the cat's away (the mice will play)", phonetic: "", cn: "猫儿不在，老鼠作怪" },
        { en: "hold your horses", phonetic: "", cn: "慢点，别急" },
        { en: "rain cats and dogs", phonetic: "", cn: "下倾盆大雨" },
        { en: "the elements", phonetic: "", cn: "天气（尤指坏天气）" },
        { en: "brave the elements", phonetic: "", cn: "不顾天气恶劣，冒着风雨" },
        { en: "after all", phonetic: "", cn: "毕竟，终究" }
    ],

    // =============================================
    //  Unit 6 — 自然与环境 / Nature & Environment
    // =============================================
    "Unit 6": [
        { en: "wrap", phonetic: "/ræp/", cn: "v.包，裹" },
        { en: "sheet", phonetic: "/ʃiːt/", cn: "n.（冰或水等的）一大片" },
        { en: "frost", phonetic: "/frɒst/", cn: "n.霜" },
        { en: "terrace", phonetic: "/ˈterɪs/", cn: "n.梯田" },
        { en: "dynasty", phonetic: "/ˈdɪnəsti/", cn: "n.朝代" },
        { en: "completion", phonetic: "/kəmˈpliːʃ(ə)n/", cn: "n.完成，结束" },
        { en: "region", phonetic: "/ˈriːdʒ(ə)n/", cn: "n.地区，区域" },
        { en: "therefore", phonetic: "/ˈðeəfɔː/", cn: "adv.因此，由此" },
        { en: "steep", phonetic: "/stiːp/", cn: "adj.陡的，陡峭的" },
        { en: "soil", phonetic: "/sɔɪl/", cn: "n.土壤" },
        { en: "shallow", phonetic: "/ˈʃæləʊ/", cn: "adj.浅的" },
        { en: "prevent", phonetic: "/prɪˈvent/", cn: "v.阻挡，防止" },
        { en: "harmony", phonetic: "/ˈhɑːməni/", cn: "n.融洽相处，和谐" },
        { en: "design", phonetic: "/dɪˈzaɪn/", cn: "v.设计" },
        { en: "vapour", phonetic: "/ˈveɪpə/", cn: "n.蒸气" },
        { en: "harm", phonetic: "/hɑːm/", cn: "v.伤害，损害" },
        { en: "crop", phonetic: "/krɒp/", cn: "n.庄稼，作物" },
        { en: "agriculture", phonetic: "/ˈæɡrɪˌkʌltʃə/", cn: "n.农业" },
        { en: "replace", phonetic: "/rɪˈpleɪs/", cn: "v.以……替换，更换" },
        { en: "material", phonetic: "/məˈtɪəriəl/", cn: "n.材料" },
        { en: "mineral", phonetic: "/ˈmɪnərəl/", cn: "n.矿物，矿产" },
        { en: "consumer", phonetic: "/kənˈsjuːmə/", cn: "n.消费者" },
        { en: "priority", phonetic: "/praɪˈɒrɪti/", cn: "n.优先处理的事，当务之急" },
        { en: "beauty", phonetic: "/ˈbjuːti/", cn: "n.美，美丽" },
        { en: "barrier", phonetic: "/ˈbæriə/", cn: "n.障碍，壁垒" },
        { en: "reef", phonetic: "/riːf/", cn: "n.礁" },
        { en: "structure", phonetic: "/ˈstrʌktʃə/", cn: "n.结构，构造，组织" },
        { en: "living", phonetic: "/ˈlɪvɪŋ/", cn: "adj.活的，活着的" },
        { en: "organism", phonetic: "/ˈɔːɡənɪz(ə)m/", cn: "n.生物，有机体" },
        { en: "observatory", phonetic: "/əbˈzɜːvət(ə)ri/", cn: "n.天文台，观象台" },
        { en: "basin", phonetic: "/ˈbeɪs(ə)n/", cn: "n.盆地，低洼地" },
        { en: "grand", phonetic: "/ɡrænd/", cn: "adj.宏伟的，壮丽的" },
        { en: "canyon", phonetic: "/ˈkænjən/", cn: "n.峡谷" },
        { en: "valley", phonetic: "/ˈvæli/", cn: "n.谷，山谷" },
        { en: "narrow", phonetic: "/ˈnærəʊ/", cn: "adj.狭窄的，不宽的" },
        { en: "platform", phonetic: "/ˈplætfɔːm/", cn: "n.高台，平台" },
        { en: "waterfall", phonetic: "/ˈwɔːtəfɔːl/", cn: "n.瀑布" },
        { en: "thunder", phonetic: "/ˈθʌndə/", cn: "v.打雷" },
        { en: "channel", phonetic: "/ˈtʃænɪl/", cn: "n.海峡" },
        { en: "tunnel", phonetic: "/ˈtʌnl/", cn: "n.隧道" },
        { en: "camel", phonetic: "/ˈkæm(ə)l/", cn: "n.骆驼" },
        { en: "desert", phonetic: "/ˈdezət/", cn: "n.沙漠，荒漠" },
        { en: "sail", phonetic: "/seɪl/", cn: "v.（乘船）航行" },
        { en: "climate", phonetic: "/ˈklaɪmɪt/", cn: "n.气候" },
        { en: "inside", phonetic: "/ɪnˈsaɪd/", cn: "adv.在（建筑物、房间）内" },
        { en: "publish", phonetic: "/ˈpʌblɪʃ/", cn: "v.出版" },
        { en: "sunflower", phonetic: "/ˈsʌnflaʊə/", cn: "n.向日葵" },
        { en: "expert", phonetic: "/ˈekspɜːt/", cn: "adj.内行的，专家的" },
        { en: "branch", phonetic: "/brɑːntʃ/", cn: "n.树枝" },
        { en: "rent", phonetic: "/rent/", cn: "v.租用，租借" },
        { en: "rooftop", phonetic: "/ˈruːftɒp/", cn: "n.屋顶" },
        { en: "thistle", phonetic: "/ˈθɪsl/", cn: "n.蓟" },
        { en: "limited", phonetic: "/ˈlɪmɪtɪd/", cn: "adj.有限的" },
        { en: "benefit", phonetic: "/ˈbenɪfɪt/", cn: "n.好处，益处" },
        { en: "herb", phonetic: "/hɜːb/", cn: "n.（用于调味）香草" },
        { en: "pleasant", phonetic: "/ˈplez(ə)nt/", cn: "adj.令人愉快的" },
        { en: "flavour", phonetic: "/ˈfleɪvə/", cn: "n.味，味道" },
        { en: "energy", phonetic: "/ˈenədʒi/", cn: "n.力量，活力" },
        { en: "system", phonetic: "/ˈsɪstəm/", cn: "n.系统" },
        // 短语
        { en: "green fingers", phonetic: "", cn: "高超的种植技能" }
    ]

};