var wordBank = {
    "Think Starter": {
        "Welcome Unit": [
            // ========== 必会 ==========
            { en: "blue", cn: "蓝色，蓝色的", phonetic: "/bluː/" },
            { en: "brown", cn: "棕色，棕色的", phonetic: "/braʊn/" },
            { en: "green", cn: "绿色，绿色的", phonetic: "/ɡriːn/" },
            { en: "grey", cn: "灰色，灰色的", phonetic: "/ɡreɪ/" },
            { en: "orange", cn: "橘色，橘色的", phonetic: "/ˈɒrɪndʒ/" },
            { en: "purple", cn: "紫色，紫色的", phonetic: "/ˈpɜːpl/" },
            { en: "yellow", cn: "黄色，黄色的", phonetic: "/ˈjeləʊ/" },
            { en: "airport", cn: "机场", phonetic: "/ˈeəpɔːt/" },
            { en: "hotel", cn: "酒店，旅馆", phonetic: "/həʊˈtel/" },
            { en: "pizza", cn: "披萨", phonetic: "/ˈpiːtsə/" },
            { en: "restaurant", cn: "餐厅", phonetic: "/ˈrestrɒnt/" },
            { en: "taxi", cn: "出租车", phonetic: "/ˈtæksi/" },
            { en: "tablet", cn: "平板", phonetic: "/ˈtæblət/" },
            { en: "morning", cn: "早晨，上午", phonetic: "/ˈmɔːnɪŋ/" },
            { en: "afternoon", cn: "下午", phonetic: "/ˌɑːftəˈnuːn/" },
            { en: "evening", cn: "晚上", phonetic: "/ˈiːvnɪŋ/" },
            { en: "night", cn: "夜晚", phonetic: "/naɪt/" },
            { en: "man", cn: "男人", phonetic: "/mæn/" },
            { en: "woman", cn: "女人", phonetic: "/ˈwʊmən/" },
            { en: "person", cn: "人", phonetic: "/ˈpɜːsn/" },
            { en: "child", cn: "孩子，儿童", phonetic: "/tʃaɪld/" },
            // ========== 认读 ==========
            { en: "black", cn: "黑色，黑色的", phonetic: "/blæk/", spell: false },
            { en: "pink", cn: "粉色，粉色的", phonetic: "/pɪŋk/", spell: false },
            { en: "red", cn: "红色，红色的", phonetic: "/red/", spell: false },
            { en: "white", cn: "白色，白色的", phonetic: "/waɪt/", spell: false },
            { en: "bus", cn: "公交车", phonetic: "/bʌs/", spell: false },
            { en: "café", cn: "咖啡馆", phonetic: "/ˈkæfeɪ/", spell: false },
            { en: "football", cn: "足球", phonetic: "/ˈfʊtbɔːl/", spell: false },
            { en: "hamburger", cn: "汉堡", phonetic: "/ˈhæmbɜːɡə(r)/", spell: false },
            { en: "phone", cn: "电话", phonetic: "/fəʊn/", spell: false },
            { en: "sandwich", cn: "三明治", phonetic: "/ˈsænwɪtʃ/", spell: false },
            { en: "T-shirt", cn: "T恤衫", phonetic: "/ˈtiː ʃɜːt/", spell: false },
            { en: "city", cn: "城市", phonetic: "/ˈsɪti/", spell: false },
            { en: "board", cn: "黑板", phonetic: "/bɔːd/", spell: false },
            { en: "book", cn: "书", phonetic: "/bʊk/", spell: false },
            { en: "chair", cn: "椅子", phonetic: "/tʃeə(r)/", spell: false },
            { en: "computer", cn: "电脑", phonetic: "/kəmˈpjuːtə(r)/", spell: false },
            { en: "desk", cn: "书桌", phonetic: "/desk/", spell: false },
            { en: "door", cn: "门", phonetic: "/dɔː(r)/", spell: false },
            { en: "pen", cn: "钢笔", phonetic: "/pen/", spell: false },
            { en: "pencil", cn: "铅笔", phonetic: "/ˈpensl/", spell: false },
            { en: "projector", cn: "投影仪", phonetic: "/prəˈdʒektə(r)/", spell: false },
            { en: "window", cn: "窗户", phonetic: "/ˈwɪndəʊ/", spell: false },
            { en: "zero", cn: "0", phonetic: "/ˈzɪərəʊ/", spell: false },
            { en: "one", cn: "1", phonetic: "/wʌn/", spell: false },
            { en: "two", cn: "2", phonetic: "/tuː/", spell: false },
            { en: "three", cn: "3", phonetic: "/θriː/", spell: false },
            { en: "four", cn: "4", phonetic: "/fɔː(r)/", spell: false },
            { en: "five", cn: "5", phonetic: "/faɪv/", spell: false },
            { en: "six", cn: "6", phonetic: "/sɪks/", spell: false },
            { en: "seven", cn: "7", phonetic: "/ˈsevn/", spell: false },
            { en: "eight", cn: "8", phonetic: "/eɪt/", spell: false },
            { en: "nine", cn: "9", phonetic: "/naɪn/", spell: false },
            { en: "ten", cn: "10", phonetic: "/ten/", spell: false },
            { en: "eleven", cn: "11", phonetic: "/ɪˈlevn/", spell: false },
            { en: "twelve", cn: "12", phonetic: "/twelv/", spell: false },
            { en: "thirteen", cn: "13", phonetic: "/ˌθɜːˈtiːn/", spell: false },
            { en: "fourteen", cn: "14", phonetic: "/ˌfɔːˈtiːn/", spell: false },
            { en: "fifteen", cn: "15", phonetic: "/ˌfɪfˈtiːn/", spell: false },
            { en: "sixteen", cn: "16", phonetic: "/ˌsɪksˈtiːn/", spell: false },
            { en: "seventeen", cn: "17", phonetic: "/ˌsevnˈtiːn/", spell: false },
            { en: "eighteen", cn: "18", phonetic: "/ˌeɪˈtiːn/", spell: false },
            { en: "nineteen", cn: "19", phonetic: "/ˌnaɪnˈtiːn/", spell: false },
            { en: "twenty", cn: "20", phonetic: "/ˈtwenti/", spell: false },
            { en: "thirty", cn: "30", phonetic: "/ˈθɜːti/", spell: false },
            { en: "forty", cn: "40", phonetic: "/ˈfɔːti/", spell: false },
            { en: "fifty", cn: "50", phonetic: "/ˈfɪfti/", spell: false },
            { en: "sixty", cn: "60", phonetic: "/ˈsɪksti/", spell: false },
            { en: "seventy", cn: "70", phonetic: "/ˈsevnti/", spell: false },
            { en: "eighty", cn: "80", phonetic: "/ˈeɪti/", spell: false },
            { en: "ninety", cn: "90", phonetic: "/ˈnaɪnti/", spell: false },
            { en: "one hundred", cn: "100", phonetic: "/wʌn ˈhʌndrəd/", spell: false }
        ],
        "Unit 1": [
            // ========== 必会 ==========
            { en: "China", cn: "中国", phonetic: "/ˈtʃaɪnə/" },
            { en: "Chinese", cn: "中国人，中国的", phonetic: "/ˌtʃaɪˈniːz/" },
            { en: "Japan", cn: "日本", phonetic: "/dʒəˈpæn/" },
            { en: "Japanese", cn: "日本人，日本的", phonetic: "/ˌdʒæpəˈniːz/" },
            { en: "the UK", cn: "英国", phonetic: "/ðə juː keɪ/" },
            { en: "British", cn: "英国人，英国的", phonetic: "/ˈbrɪtɪʃ/" },
            { en: "the US", cn: "美国", phonetic: "/ðə juː es/" },
            { en: "American", cn: "美国人，美国的", phonetic: "/əˈmerɪkən/" },
            { en: "how", cn: "如何，怎么样", phonetic: "/haʊ/" },
            { en: "when", cn: "什么时候", phonetic: "/wen/" },
            { en: "singer", cn: "歌手", phonetic: "/ˈsɪŋə(r)/" },
            { en: "player", cn: "运动员", phonetic: "/ˈpleɪə(r)/" },
            { en: "pianist", cn: "钢琴家", phonetic: "/ˈpɪənɪst/" },
            { en: "great", cn: "伟大的，极好的", phonetic: "/ɡreɪt/" },
            { en: "awesome", cn: "了不起的，极好的", phonetic: "/ˈɔːsəm/" },
            { en: "musician", cn: "音乐家", phonetic: "/mjuːˈzɪʃn/" },
            { en: "website", cn: "网站", phonetic: "/ˈwebsaɪt/" },
            { en: "what", cn: "什么", phonetic: "/wɒt/" },
            { en: "where", cn: "在哪里", phonetic: "/weə(r)/" },
            { en: "who", cn: "谁", phonetic: "/huː/" },
            { en: "why", cn: "为什么", phonetic: "/waɪ/" },
            { en: "which", cn: "哪一个", phonetic: "/wɪtʃ/" },
            { en: "fast", cn: "快速的", phonetic: "/fɑːst/" },
            { en: "slow", cn: "慢的", phonetic: "/sləʊ/" },
            { en: "cheap", cn: "便宜的", phonetic: "/tʃiːp/" },
            { en: "expensive", cn: "昂贵的", phonetic: "/ɪkˈspensɪv/" },
            { en: "clean", cn: "干净的；打扫", phonetic: "/kliːn/" },
            { en: "dirty", cn: "脏的", phonetic: "/ˈdɜːti/" },
            { en: "big", cn: "大的", phonetic: "/bɪɡ/" },
            { en: "small", cn: "小的", phonetic: "/smɔːl/" },
            { en: "new", cn: "新的", phonetic: "/njuː/" },
            { en: "old", cn: "旧的，年老的", phonetic: "/əʊld/" },
            { en: "actor", cn: "男演员", phonetic: "/ˈæktə(r)/" },
            { en: "fan", cn: "粉丝；风扇", phonetic: "/fæn/" },
            { en: "nice", cn: "美好的", phonetic: "/naɪs/" },
            { en: "meet", cn: "遇见", phonetic: "/miːt/" },
            { en: "country", cn: "国家", phonetic: "/ˈkʌntri/" },
            { en: "flag", cn: "旗帜", phonetic: "/flæɡ/" },
            { en: "athlete", cn: "运动员", phonetic: "/ˈæθliːt/" },
            { en: "favourite", cn: "最喜欢的", phonetic: "/ˈfeɪvərɪt/" },
            { en: "excited", cn: "激动的", phonetic: "/ɪkˈsaɪtɪd/" },
            { en: "life", cn: "生活", phonetic: "/laɪf/" },
            { en: "lesson", cn: "课程，教训", phonetic: "/ˈlesn/" },
            { en: "important", cn: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
            { en: "wait", cn: "等候", phonetic: "/weɪt/" },
            { en: "tomorrow", cn: "明天", phonetic: "/təˈmɒrəʊ/" },
            { en: "trip", cn: "出行，旅行", phonetic: "/trɪp/" },
            { en: "stress", cn: "压力", phonetic: "/stres/" },
            { en: "if", cn: "如果，是否", phonetic: "/ɪf/" },
            { en: "hour", cn: "小时", phonetic: "/ˈaʊə(r)/" },
            { en: "film star", cn: "电影明星", phonetic: "/fɪlm stɑː(r)/" },
            { en: "How's it going?", cn: "最近怎么样？", phonetic: "/haʊz ɪt ˈɡəʊɪŋ/" },
            { en: "See you later.", cn: "回头见。", phonetic: "/siː juː ˈleɪtə(r)/" },
            { en: "That's awesome!", cn: "太棒了！", phonetic: "/ðæts ˈɔːsəm/" },
            { en: "I know!", cn: "我懂！", phonetic: "/aɪ nəʊ/" },
            // ========== 认读 ==========
            { en: "Brazil", cn: "巴西", phonetic: "/brəˈzɪl/", spell: false },
            { en: "Brazilian", cn: "巴西人", phonetic: "/brəˈzɪliən/", spell: false },
            { en: "Russia", cn: "俄罗斯", phonetic: "/ˈrʌʃə/", spell: false },
            { en: "Russian", cn: "俄罗斯人", phonetic: "/ˈrʌʃn/", spell: false },
            { en: "Africa", cn: "非洲", phonetic: "/ˈæfrɪkə/", spell: false },
            { en: "African", cn: "非洲人", phonetic: "/ˈæfrɪkən/", spell: false },
            { en: "Spain", cn: "西班牙", phonetic: "/speɪn/", spell: false },
            { en: "Spanish", cn: "西班牙人", phonetic: "/ˈspænɪʃ/", spell: false },
            { en: "Turkey", cn: "土耳其", phonetic: "/ˈtɜːki/", spell: false },
            { en: "Turkish", cn: "土耳其人", phonetic: "/ˈtɜːkɪʃ/", spell: false },
            { en: "guy", cn: "男人，家伙", phonetic: "/ɡaɪ/", spell: false },
            { en: "vlog", cn: "视频博客", phonetic: "/vlɒɡ/", spell: false },
            { en: "topic", cn: "主题，话题", phonetic: "/ˈtɒpɪk/", spell: false },
            { en: "patient", cn: "有耐心的", phonetic: "/ˈpeɪʃnt/", spell: false },
            { en: "next week", cn: "下周", phonetic: "/nekst wiːk/", spell: false },
            { en: "no problem", cn: "没问题", phonetic: "/nəʊ ˈprɒbləm/", spell: false },
            { en: "be calm", cn: "保持冷静", phonetic: "/bi kɑːm/", spell: false },
            { en: "no rush", cn: "别着急", phonetic: "/nəʊ rʌʃ/", spell: false },
            { en: "submarine", cn: "潜艇", phonetic: "/ˌsʌbməˈriːn/", spell: false }
        ],
        "Unit 2": [
            // ========== 必会 ==========
            { en: "excited", cn: "感到兴奋的", phonetic: "/ɪkˈsaɪtɪd/" },
            { en: "angry", cn: "生气的", phonetic: "/ˈæŋɡri/" },
            { en: "hungry", cn: "饥饿的", phonetic: "/ˈhʌŋɡri/" },
            { en: "thirsty", cn: "口渴的", phonetic: "/ˈθɜːsti/" },
            { en: "bored", cn: "无聊的", phonetic: "/bɔːd/" },
            { en: "worried", cn: "担心的", phonetic: "/ˈwʌrid/" },
            { en: "tired", cn: "疲惫的", phonetic: "/taɪəd/" },
            { en: "party", cn: "派对", phonetic: "/ˈpɑːti/" },
            { en: "school", cn: "学校", phonetic: "/skuːl/" },
            { en: "cinema", cn: "电影院", phonetic: "/ˈsɪnəmə/" },
            { en: "computer shop", cn: "电脑店", phonetic: "/kəmˈpjuːtə(r) ʃɒp/" },
            { en: "station", cn: "车站", phonetic: "/ˈsteɪʃn/" },
            { en: "at home", cn: "在家", phonetic: "/ət həʊm/" },
            { en: "at school", cn: "在学校", phonetic: "/ət skuːl/" },
            { en: "at the cinema", cn: "在电影院", phonetic: "/ət ðə ˈsɪnəmə/" },
            { en: "at the computer shop", cn: "在电脑店", phonetic: "/ət ðə kəmˈpjuːtə ʃɒp/" },
            { en: "at the station", cn: "在车站", phonetic: "/ət ðə ˈsteɪʃn/" },
            { en: "at the stadium", cn: "在体育馆", phonetic: "/ət ðə ˈsteɪdiəm/" },
            { en: "exciting", cn: "令人兴奋的", phonetic: "/ɪkˈsaɪtɪŋ/" },
            { en: "good", cn: "好的", phonetic: "/ɡʊd/" },
            { en: "funny", cn: "有趣的", phonetic: "/ˈfʌni/" },
            { en: "excellent", cn: "极好的", phonetic: "/ˈeksələnt/" },
            { en: "awful", cn: "极差的", phonetic: "/ˈɔːfl/" },
            { en: "terrible", cn: "糟糕的", phonetic: "/ˈterəbl/" },
            { en: "bad", cn: "坏的", phonetic: "/bæd/" },
            { en: "I", cn: "我", phonetic: "/aɪ/" },
            { en: "me", cn: "我", phonetic: "/miː/" },
            { en: "we", cn: "我们", phonetic: "/wiː/" },
            { en: "us", cn: "我们", phonetic: "/ʌs/" },
            { en: "you", cn: "你；你们", phonetic: "/juː/" },
            { en: "he", cn: "他", phonetic: "/hiː/" },
            { en: "him", cn: "他", phonetic: "/hɪm/" },
            { en: "she", cn: "她", phonetic: "/ʃiː/" },
            { en: "her", cn: "她", phonetic: "/hɜː(r)/" },
            { en: "it", cn: "它", phonetic: "/ɪt/" },
            { en: "they", cn: "他们；她们；它们", phonetic: "/ðeɪ/" },
            { en: "them", cn: "他们；她们；它们", phonetic: "/ðem/" },
            // ========== 认读 ==========
            { en: "home", cn: "家", phonetic: "/həʊm/", spell: false },
            { en: "stadium", cn: "体育馆", phonetic: "/ˈsteɪdiəm/", spell: false },
            { en: "hot", cn: "热的", phonetic: "/hɒt/", spell: false },
            { en: "cold", cn: "冷的", phonetic: "/kəʊld/", spell: false },
            { en: "sad", cn: "难过的", phonetic: "/sæd/", spell: false },
            { en: "sales assistant", cn: "销售员", phonetic: "/seɪlz əˈsɪstənt/", spell: false },
            { en: "war", cn: "战争", phonetic: "/wɔː(r)/", spell: false },
            { en: "late", cn: "晚的", phonetic: "/leɪt/", spell: false },
            { en: "tonight", cn: "今晚", phonetic: "/təˈnaɪt/", spell: false },
            { en: "a bit", cn: "有点儿", phonetic: "/ə bɪt/", spell: false },
            { en: "on holiday", cn: "在度假", phonetic: "/ɒn ˈhɒlədeɪ/", spell: false },
            { en: "difficult", cn: "困难的", phonetic: "/ˈdɪfɪkəlt/", spell: false },
            { en: "easy", cn: "简单的", phonetic: "/ˈiːzi/", spell: false },
            { en: "concert", cn: "演唱会", phonetic: "/ˈkɒnsət/", spell: false },
            { en: "surprise", cn: "惊喜", phonetic: "/səˈpraɪz/", spell: false },
            { en: "ticket", cn: "门票", phonetic: "/ˈtɪkɪt/", spell: false },
            { en: "festival", cn: "节日", phonetic: "/ˈfestɪvl/", spell: false },
            { en: "mask", cn: "面具，口罩", phonetic: "/mɑːsk/", spell: false },
            { en: "popular", cn: "受欢迎的", phonetic: "/ˈpɒpjələ(r)/", spell: false },
            { en: "medicine", cn: "药品", phonetic: "/ˈmedsn/", spell: false },
            { en: "different", cn: "不同的", phonetic: "/ˈdɪfrənt/", spell: false },
            { en: "Halloween", cn: "万圣节", phonetic: "/ˌhæləʊˈiːn/", spell: false }
        ],
        "Unit 3": [
            // ========== 必会 ==========
            { en: "actress", cn: "女演员", phonetic: "/ˈæktrəs/" },
            { en: "born", cn: "出生", phonetic: "/bɔːn/" },
            { en: "twins", cn: "双胞胎", phonetic: "/twɪnz/" },
            { en: "husband", cn: "丈夫", phonetic: "/ˈhʌzbənd/" },
            { en: "wife", cn: "妻子", phonetic: "/waɪf/" },
            { en: "son", cn: "儿子", phonetic: "/sʌn/" },
            { en: "daughter", cn: "女儿", phonetic: "/ˈdɔːtə(r)/" },
            { en: "aunt", cn: "阿姨，姑姨", phonetic: "/ɑːnt/" },
            { en: "uncle", cn: "叔叔，舅伯", phonetic: "/ˈʌŋkl/" },
            { en: "cousin", cn: "堂/表兄弟姐妹", phonetic: "/ˈkʌzn/" },
            { en: "mother", cn: "妈妈", phonetic: "/ˈmʌðə(r)/" },
            { en: "father", cn: "爸爸", phonetic: "/ˈfɑːðə(r)/" },
            { en: "brother", cn: "兄弟", phonetic: "/ˈbrʌðə(r)/" },
            { en: "sister", cn: "姐妹", phonetic: "/ˈsɪstə(r)/" },
            { en: "my", cn: "我的", phonetic: "/maɪ/" },
            { en: "mine", cn: "我的", phonetic: "/maɪn/" },
            { en: "your", cn: "你的；你们的", phonetic: "/jɔː(r)/" },
            { en: "yours", cn: "你的；你们的", phonetic: "/jɔːz/" },
            { en: "his", cn: "他的", phonetic: "/hɪz/" },
            { en: "her", cn: "她的", phonetic: "/hɜː(r)/" },
            { en: "hers", cn: "她的", phonetic: "/hɜːz/" },
            { en: "its", cn: "它的", phonetic: "/ɪts/" },
            { en: "our", cn: "我们的", phonetic: "/ˈaʊə(r)/" },
            { en: "ours", cn: "我们的", phonetic: "/ˈaʊəz/" },
            { en: "their", cn: "他们的；她们的；它们的", phonetic: "/ðeə(r)/" },
            { en: "theirs", cn: "他们的；她们的；它们的", phonetic: "/ðeəz/" },
            { en: "shower", cn: "淋浴器", phonetic: "/ˈʃaʊə(r)/" },
            { en: "cooker", cn: "炉灶", phonetic: "/ˈkʊkə(r)/" },
            { en: "bath", cn: "浴缸", phonetic: "/bɑːθ/" },
            { en: "armchair", cn: "扶手椅", phonetic: "/ˈɑːmtʃeə(r)/" },
            { en: "bed", cn: "床", phonetic: "/bed/" },
            { en: "toilet", cn: "马桶", phonetic: "/ˈtɔɪlət/" },
            { en: "sofa", cn: "沙发", phonetic: "/ˈsəʊfə/" },
            { en: "fridge", cn: "冰箱", phonetic: "/frɪdʒ/" },
            { en: "bathroom", cn: "卫生间", phonetic: "/ˈbɑːθruːm/" },
            { en: "bedroom", cn: "卧室", phonetic: "/ˈbedruːm/" },
            { en: "living room", cn: "客厅", phonetic: "/ˈlɪvɪŋ ruːm/" },
            { en: "garage", cn: "车库", phonetic: "/ˈɡærɑːʒ/" },
            { en: "hall", cn: "走廊，大厅", phonetic: "/hɔːl/" },
            { en: "kitchen", cn: "厨房", phonetic: "/ˈkɪtʃɪn/" },
            { en: "garden", cn: "花园", phonetic: "/ˈɡɑːdn/" },
            { en: "this", cn: "这个", phonetic: "/ðɪs/" },
            { en: "that", cn: "那个", phonetic: "/ðæt/" },
            { en: "these", cn: "这些", phonetic: "/ðiːz/" },
            { en: "those", cn: "那些", phonetic: "/ðəʊz/" },
            { en: "here", cn: "在这里", phonetic: "/hɪə(r)/" },
            { en: "there", cn: "在那里", phonetic: "/ðeə(r)/" },
            { en: "real", cn: "真实的", phonetic: "/rɪəl/" },
            { en: "perfect", cn: "完美的", phonetic: "/ˈpɜːfɪkt/" },
            { en: "comfortable", cn: "舒服的", phonetic: "/ˈkʌmftəbl/" },
            { en: "right", cn: "对的；右边", phonetic: "/raɪt/" },
            { en: "wrong", cn: "错的", phonetic: "/rɒŋ/" },
            { en: "Oh right.", cn: "哦，是的。", phonetic: "/əʊ raɪt/" },
            { en: "Really?", cn: "真的吗？", phonetic: "/ˈrɪəli/" },
            { en: "Just a minute.", cn: "稍等一下。", phonetic: "/dʒʌst ə ˈmɪnɪt/" },
            { en: "Let's go.", cn: "我们走吧。", phonetic: "/lets ɡəʊ/" },
            // ========== 认读 ==========
            { en: "ambassador", cn: "大使", phonetic: "/æmˈbæsədə(r)/", spell: false },
            { en: "Australia", cn: "澳大利亚", phonetic: "/ɒˈstreɪliə/", spell: false },
            { en: "Australian", cn: "澳大利亚人", phonetic: "/ɒˈstreɪliən/", spell: false }
        ],
        "Unit 4": [
            // ========== 必会 ==========
            { en: "local", cn: "当地的", phonetic: "/ˈləʊkl/" },
            { en: "palace", cn: "宫殿", phonetic: "/ˈpæləs/" },
            { en: "park", cn: "公园", phonetic: "/pɑːk/" },
            { en: "square", cn: "广场", phonetic: "/skweə(r)/" },
            { en: "statue", cn: "雕像", phonetic: "/ˈstætʃuː/" },
            { en: "bank", cn: "银行", phonetic: "/bæŋk/" },
            { en: "chemist", cn: "药店，药房", phonetic: "/ˈkemɪst/" },
            { en: "library", cn: "图书馆", phonetic: "/ˈlaɪbrəri/" },
            { en: "museum", cn: "博物馆", phonetic: "/mjuˈziːəm/" },
            { en: "restaurant", cn: "餐厅", phonetic: "/ˈrestrɒnt/" },
            { en: "supermarket", cn: "超市", phonetic: "/ˈsuːpəmɑːkɪt/" },
            { en: "train station", cn: "火车站", phonetic: "/treɪn ˈsteɪʃn/" },
            { en: "in front of", cn: "在……前面", phonetic: "/ɪn frʌnt ɒv/" },
            { en: "behind", cn: "在……后面", phonetic: "/bɪˈhaɪnd/" },
            { en: "between", cn: "在……中间", phonetic: "/bɪˈtwiːn/" },
            { en: "next to", cn: "在……旁边", phonetic: "/nekst tuː/" },
            { en: "opposite", cn: "在……对面", phonetic: "/ˈɒpəzɪt/" },
            { en: "on the corner of", cn: "在……的角落", phonetic: "/ɒn ðə ˈkɔːnə(r) ɒv/" },
            { en: "on the left", cn: "在左边", phonetic: "/ɒn ðə left/" },
            { en: "on the right", cn: "在右边", phonetic: "/ɒn ðə raɪt/" },
            { en: "turn", cn: "转向", phonetic: "/tɜːn/" },
            { en: "street", cn: "街道", phonetic: "/striːt/" },
            { en: "eleven", cn: "11", phonetic: "/ɪˈlevn/" },
            { en: "twelve", cn: "12", phonetic: "/twelv/" },
            { en: "thirteen", cn: "13", phonetic: "/ˌθɜːˈtiːn/" },
            { en: "fifteen", cn: "15", phonetic: "/ˌfɪfˈtiːn/" },
            { en: "twenty", cn: "20", phonetic: "/ˈtwenti/" },
            { en: "thirty", cn: "30", phonetic: "/ˈθɜːti/" },
            { en: "forty", cn: "40", phonetic: "/ˈfɔːti/" },
            { en: "fifty", cn: "50", phonetic: "/ˈfɪfti/" },
            { en: "hundred", cn: "百", phonetic: "/ˈhʌndrəd/" },
            { en: "thousand", cn: "千", phonetic: "/ˈθaʊznd/" },
            { en: "path", cn: "小路", phonetic: "/pɑːθ/" },
            { en: "view", cn: "风景", phonetic: "/vjuː/" },
            { en: "public", cn: "公共的", phonetic: "/ˈpʌblɪk/" },
            { en: "lovely", cn: "可爱的，美丽的", phonetic: "/ˈlʌvli/" },
            { en: "modern", cn: "现代的", phonetic: "/ˈmɒdn/" },
            { en: "visit", cn: "参观，拜访", phonetic: "/ˈvɪzɪt/" },
            { en: "visitor", cn: "参观者，游客", phonetic: "/ˈvɪzɪtə(r)/" },
            { en: "building", cn: "建筑", phonetic: "/ˈbɪldɪŋ/" },
            { en: "adult", cn: "成年人", phonetic: "/ˈædʌlt/" },
            { en: "change", cn: "零钱；改变", phonetic: "/tʃeɪndʒ/" },
            { en: "trainers", cn: "球鞋", phonetic: "/ˈtreɪnəz/" },
            { en: "machine", cn: "机器", phonetic: "/məˈʃiːn/" },
            { en: "interesting", cn: "有趣的", phonetic: "/ˈɪntrəstɪŋ/" },
            { en: "important", cn: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
            // ========== 认读 ==========
            { en: "fountain", cn: "喷泉", phonetic: "/ˈfaʊntən/", spell: false },
            { en: "castle", cn: "城堡", phonetic: "/ˈkɑːsl/", spell: false },
            { en: "bridge", cn: "桥", phonetic: "/brɪdʒ/", spell: false },
            { en: "cable car", cn: "缆车", phonetic: "/ˈkeɪbl kɑː(r)/", spell: false }
        ]
    },

    "必修1": {

        "Unit 1": [
            { en: "exchange",           phonetic: "/ɪksˈtʃeɪndʒ/",       cn: "n.&vt.交换;交流;交易;兑换" },
            { en: "lecture",            phonetic: "/ˈlektʃə(r)/",         cn: "n.讲座;讲课 vi.(开)讲座" },
            { en: "registration",       phonetic: "/ˌredʒɪˈstreɪʃn/",    cn: "n.登记;注册;挂号" },
            { en: "register",           phonetic: "/ˈredʒɪstə(r)/",      cn: "vt.&vi.登记;注册" },
            { en: "sex",                phonetic: "/seks/",               cn: "n.性别" },
            { en: "female",             phonetic: "/ˈfi:meɪl/",           cn: "adj.女(性)的;雌的 n.雌性" },
            { en: "male",               phonetic: "/meɪl/",               cn: "adj.男(性)的;雄的 n.雄性" },
            { en: "nationality",        phonetic: "/ˌnæʃəˈnæləti/",      cn: "n.国籍;民族" },
            { en: "nation",             phonetic: "/ˈneɪʃn/",             cn: "n.国家;民族;国民" },
            { en: "designer",           phonetic: "/dɪˈzaɪnə(r)/",       cn: "n.设计者" },
            { en: "design",             phonetic: "/dɪˈzaɪn/",            cn: "n.设计;设计方案 vt.设计" },
            { en: "campus",             phonetic: "/ˈkæmpəs/",            cn: "n.校园;校区" },
            { en: "formal",             phonetic: "/ˈfɔ:ml/",             cn: "adj.正式的;正规的" },
            { en: "anxious",            phonetic: "/ˈæŋkʃəs/",            cn: "adj.焦虑的;不安的" },
            { en: "annoyed",            phonetic: "/əˈnɔɪd/",             cn: "adj.恼怒的;生气的" },
            { en: "annoy",              phonetic: "/əˈnɔɪ/",              cn: "vt.使恼怒;打扰" },
            { en: "frightened",         phonetic: "/ˈfraɪtnd/",           cn: "adj.惊吓的;害怕的" },
            { en: "p.m.",               phonetic: "/pi: em/",             cn: "abbr.(源自拉丁)下午;午后" },
            { en: "a.m.",               phonetic: "/ə em/",               cn: "abbr.(源自拉丁)上午;午前" },
            { en: "senior",             phonetic: "/ˈsi:niə(r)/",         cn: "adj.级别高的 n.较年长的人" },
            { en: "senior high school", phonetic: "/ˈsi:niə(r) haɪ sku:l/", cn: "(美国)高中" },
            { en: "at last",            phonetic: "/ət lɑ:st/",           cn: "终于;最终" },
            { en: "outgoing",           phonetic: "/ˈaʊtgəʊɪŋ/",         cn: "adj.爱交际的;外向的" },
            { en: "impression",         phonetic: "/ɪmˈpreʃn/",           cn: "n.印象;感想" },
            { en: "impress",            phonetic: "/ɪmˈpres/",            cn: "vt.使钦佩 vi.留下印象" },
            { en: "Make an impression", phonetic: "/meɪk ən ɪmˈpreʃn/",  cn: "留下好印象" },
            { en: "what if",            phonetic: "/wɒt ɪf/",             cn: "要是……会怎么样呢？" },
            { en: "guy",                phonetic: "/gaɪ/",                cn: "n.小伙子;男人;家伙" },
            { en: "concentrate",        phonetic: "/ˈkɒnsntreɪt/",       cn: "vi.&vt.集中注意;聚精会神" },
            { en: "concentrate on",     phonetic: "/ˈkɒnsntreɪt ɒn/",    cn: "集中精力于" },
            { en: "experiment",         phonetic: "/ɪkˈsperɪmənt/",      cn: "n.实验;试验" },
            { en: "leave ... alone",    phonetic: "/li:v əˈləʊn/",       cn: "不打扰;不惊动" },
            { en: "awkward",            phonetic: "/ˈɔ:kwəd/",            cn: "adj.令人尴尬的;难对付的" },
            { en: "junior",             phonetic: "/ˈdʒu:niə(r)/",        cn: "adj.地位低的 n.职位较低者" },
            { en: "junior high school", phonetic: "/ˈdʒu:niə(r) haɪ sku:l/", cn: "(美国)初级中学" },
            { en: "explore",            phonetic: "/ɪkˈsplɔ:(r)/",       cn: "vt.&vi.搜索;勘探" },
            { en: "confident",          phonetic: "/ˈkɒnfɪdənt/",        cn: "adj.自信的;有把握的" },
            { en: "confidence",         phonetic: "/ˈkɒnfɪdəns/",        cn: "n.信心;信任" },
            { en: "forward",            phonetic: "/ˈfɔ:wəd/",            cn: "adv.向前;前进 adj.向前的" },
            { en: "look forward to",    phonetic: "/lʊk ˈfɔ:wəd tə/",    cn: "盼望;期待" },
            { en: "take notes",         phonetic: "/teɪk nəuts/",        cn: "记笔记" },
            { en: "flash",              phonetic: "/flæʃ/",               cn: "n.光;信号 vi.闪耀;闪光" },
            { en: "flash card",         phonetic: "/flæʃ kɑ:d/",         cn: "教学卡片;识字卡" },
            { en: "organise",           phonetic: "/ˈɔ:gənaɪz/",         cn: "vt.组织;筹备 vi.组建;成立" },
            { en: "organisation",       phonetic: "/ˌɔ:gənaɪˈzeɪʃən/",  cn: "n.组织;团体;机构" },
            { en: "goal",               phonetic: "/gəʊl/",               cn: "n.目标;球门;射门" },
            { en: "strategy",           phonetic: "/ˈstrætədʒi/",        cn: "n.策略;策划" },
            { en: "partner",            phonetic: "/ˈpɑ:tnə(r)/",        cn: "n.同伴;配偶;合伙人" },
            { en: "improve",            phonetic: "/ɪmˈpru:v/",           cn: "vi.&vt.改进;改善" },
            { en: "curious",            phonetic: "/ˈkjʊəriəs/",         cn: "adj.好奇的;求知欲强的" },
            { en: "company",            phonetic: "/ˈkʌmpəni/",           cn: "n.公司;商行;陪伴" },
            { en: "personality",        phonetic: "/ˌpɜ:səˈnæləti/",     cn: "n.性格;个性" },
            { en: "style",              phonetic: "/staɪl/",              cn: "n.方式;作风" },
            { en: "revise",             phonetic: "/rɪˈvaɪz/",            cn: "vt.&vi.修改;修订;复习" }
        ],

        "Unit 2": [
            { en: "teenage",            phonetic: "/ˈti:neɪdʒ/",          cn: "adj.十几岁的;青少年的" },
            { en: "teenager",           phonetic: "/ˈti:neɪdʒə(r)/",     cn: "n.(13至19岁之间的)青少年" },
            { en: "ballet",             phonetic: "/ˈbæleɪ/",             cn: "n.芭蕾舞" },
            { en: "volunteer",          phonetic: "/ˌvɒlənˈtɪə(r)/",     cn: "n.志愿者" },
            { en: "debate",             phonetic: "/dɪˈbeɪt/",            cn: "n.辩论;争论 vt.&vi.辩论" },
            { en: "prefer",             phonetic: "/prɪˈfɜ:(r)/",        cn: "vt.较喜欢" },
            { en: "prefer ... to ...",  phonetic: "/prɪˈfɜ:(r) tə/",     cn: "喜欢……多于……" },
            { en: "content",            phonetic: "/ˈkɒntent/",           cn: "n.内容;[pl.]目录" },
            { en: "movement",           phonetic: "/ˈmu:vmənt/",          cn: "n.动作;运动;活动" },
            { en: "greenhouse",         phonetic: "/ˈgri:nhaʊs/",         cn: "n.温室;暖房" },
            { en: "clean up",           phonetic: "/kli:n ʌp/",           cn: "打扫(或清除)干净" },
            { en: "suitable",           phonetic: "/ˈsu:təbl/",           cn: "adj.合适的;适用的" },
            { en: "suitable for",       phonetic: "/ˈsu:təbl fə(r)/",    cn: "对……适合的" },
            { en: "actually",           phonetic: "/ˈæktʃuəli/",          cn: "adv.事实上;的确" },
            { en: "challenge",          phonetic: "/ˈtʃæləndʒ/",         cn: "n.挑战;艰巨任务 vt.怀疑" },
            { en: "title",              phonetic: "/ˈtaɪtl/",             cn: "n.(书、诗歌等)名称;标题" },
            { en: "topic",              phonetic: "/ˈtɒpɪk/",             cn: "n.话题;标题" },
            { en: "freshman",           phonetic: "/ˈfreʃmən/",           cn: "n.中学九年级学生;大学新生" },
            { en: "confusing",          phonetic: "/kənˈfju:zɪŋ/",       cn: "adj.难以理解的;不清楚的" },
            { en: "confuse",            phonetic: "/kənˈfju:z/",         cn: "vt.使糊涂;使迷惑" },
            { en: "Confused",           phonetic: "/kənˈfju:zd/",        cn: "adj.糊涂的;迷惑的" },
            { en: "fluent",             phonetic: "/ˈflu:ənt/",           cn: "adj.(外语)流利的;熟练的" },
            { en: "graduate",           phonetic: "/ˈgrædʒuət/",         cn: "vi.&vt.毕业 n.毕业生" },
            { en: "recommend",          phonetic: "/ˌrekəˈmend/",        cn: "vt.建议;推荐;介绍" },
            { en: "sign up for sth.",   phonetic: "/saɪn ʌp fə(r) ˈsʌmθɪŋ/", cn: "报名参加课程" },
            { en: "advanced",           phonetic: "/ədˈvɑ:nst/",          cn: "adj.高级的;高等的;先进的" },
            { en: "advance",            phonetic: "/ədˈvɑ:ns/",           cn: "n.&vi.&vt.前进;发展;促进" },
            { en: "literature",         phonetic: "/ˈlɪtrətʃə(r)/",      cn: "n.文学;文学作品" },
            { en: "extra-curricular",   phonetic: "/ˈekstrə kəˈrɪkjələ(r)/", cn: "adj.课外的;课程以外的" },
            { en: "extra",              phonetic: "/ˈekstrə/",            cn: "adj.额外的;附加的" },
            { en: "obviously",          phonetic: "/ˈɒbviəsli/",          cn: "adv.显然;明显地" },
            { en: "quit",               phonetic: "/kwɪt/",               cn: "vi.&vt.停止;戒掉;离开" },
            { en: "responsible",        phonetic: "/rɪˈspɒnsəbl/",       cn: "adj.负责的;有责任的" },
            { en: "responsibility",     phonetic: "/rɪˌspɒnsəˈbɪləti/",  cn: "n.责任;义务" },
            { en: "be responsible for", phonetic: "/bi rɪˈspɒnsəbl fə(r)/", cn: "对……负责" },
            { en: "solution",           phonetic: "/səˈlu:ʃn/",           cn: "n.解决办法;答案" },
            { en: "schedule",           phonetic: "/ˈʃedju:l/",           cn: "n.工作计划 vt.安排;预定" },
            { en: "editor",             phonetic: "/ˈedɪtə(r)/",         cn: "n.主编;编辑;编者" },
            { en: "plate",              phonetic: "/pleɪt/",              cn: "n.盘子;碟子" },
            { en: "adventure",          phonetic: "/ədˈventʃə(r)/",      cn: "n.冒险;奇遇" },
            { en: "youth",              phonetic: "/ju:θ/",               cn: "n.青年时期;青春" },
            { en: "expert",             phonetic: "/ˈekspɜ:t/",           cn: "n.专家;行家 adj.熟练的" },
            { en: "behaviour",          phonetic: "/bɪˈheɪvjə(r)/",      cn: "n.行为;举止" },
            { en: "generation",         phonetic: "/ˌdʒenəˈreɪʃn/",     cn: "n.一代(人)" },
            { en: "attract",            phonetic: "/əˈtrækt/",            cn: "vt.吸引;引起…注意(兴趣)" },
            { en: "be attracted to",    phonetic: "/bi əˈtræktid tə/",   cn: "喜爱" },
            { en: "focus",              phonetic: "/ˈfəʊkəs/",            cn: "vi.&vt.集中精力等 n.焦点" },
            { en: "focus on",           phonetic: "/ˈfəʊkəs ɒn/",        cn: "集中;特别关注" },
            { en: "addicted",           phonetic: "/əˈdɪktɪd/",           cn: "adj.有瘾的;上瘾的;入迷的" },
            { en: "addict",             phonetic: "/ˈædɪkt/",             cn: "n.对…入迷的人;吸毒成瘾者" },
            { en: "addicted to",        phonetic: "/əˈdɪktɪd tə/",       cn: "对……很入迷" },
            { en: "adult",              phonetic: "/ˈædʌlt/",             cn: "n.成年人 adj.成年的" },
            { en: "Chicago",            phonetic: "/ʃɪˈkɑ:gəʊ/",         cn: "芝加哥(美国城市)" },
            { en: "Seoul",              phonetic: "/səʊl/",               cn: "首尔(韩国首都)" }
        ],

        "Unit 3": [
            { en: "castle",             phonetic: "/ˈkɑ:sl/",             cn: "n.城堡;堡垒" },
            { en: "apply",              phonetic: "/əˈplaɪ/",             cn: "vi.&vt.申请;请求 vt.应用" },
            { en: "apply for",          phonetic: "/əˈplaɪ fə(r)/",      cn: "申请" },
            { en: "visa",               phonetic: "/ˈvi:zə/",             cn: "n.签证" },
            { en: "rent",               phonetic: "/rent/",               cn: "vt.&vi.租用;出租 n.租金" },
            { en: "pack",               phonetic: "/pæk/",                cn: "vi.&vt.收拾(行李);包装" },
            { en: "amazing",            phonetic: "/əˈmeɪzɪŋ/",           cn: "adj.令人惊奇的;令人惊喜的" },
            { en: "amazed",             phonetic: "/əˈmeɪzd/",            cn: "adj.惊奇的;惊喜的" },
            { en: "arrangement",        phonetic: "/əˈreɪndʒmənt/",      cn: "n.安排;筹备" },
            { en: "extremely",          phonetic: "/ɪkˈstri:mli/",        cn: "adv.极其;非常" },
            { en: "source",             phonetic: "/sɔ:s/",               cn: "n.来源;出处" },
            { en: "narrow",             phonetic: "/ˈnærəʊ/",             cn: "adj.狭窄的 vi.&vt.使变窄" },
            { en: "flat",               phonetic: "/flæt/",               cn: "adj.平坦的;扁平的 n.公寓" },
            { en: "powerful",           phonetic: "/ˈpaʊəfl/",            cn: "adj.强有力的;有权势的" },
            { en: "empire",             phonetic: "/ˈempaɪə(r)/",        cn: "n.帝国" },
            { en: "emperor",            phonetic: "/ˈempərə(r)/",        cn: "n.皇帝" },
            { en: "site",               phonetic: "/saɪt/",               cn: "n.地点;位置;现场" },
            { en: "take control of",    phonetic: "/teɪk kənˈtrəʊl əv/", cn: "控制;接管" },
            { en: "official",           phonetic: "/əˈfɪʃl/",             cn: "adj.官方的;正式的 n.官员" },
            { en: "recognise",          phonetic: "/ˈrekəgnaɪz/",        cn: "vt.辨别出;承认;认可" },
            { en: "type",               phonetic: "/taɪp/",               cn: "n.类型;种类 vi.&vt.打字" },
            { en: "flight",             phonetic: "/flaɪt/",              cn: "n.空中航行;航班;航程" },
            { en: "accommodation",      phonetic: "/əˌkɒməˈdeɪʃn/",     cn: "n.住处;停留处;膳宿" },
            { en: "unique",             phonetic: "/juˈni:k/",            cn: "adj.唯一的;独特的;特有的" },
            { en: "path",               phonetic: "/pɑ:θ/",               cn: "n.小路;路线;道路" },
            { en: "destination",        phonetic: "/ˌdestɪˈneɪʃn/",     cn: "n.目的地;终点" },
            { en: "other than",         phonetic: "/ˈʌðə(r) ðən/",      cn: "除……以外" },
            { en: "admire",             phonetic: "/ədˈmaɪə(r)/",        cn: "vt.钦佩;赞赏" },
            { en: "architecture",       phonetic: "/ˈɑ:kɪtektʃə(r)/",   cn: "n.建筑设计;建筑学" },
            { en: "architect",          phonetic: "/ˈɑ:kɪtekt/",         cn: "n.建筑设计师" },
            { en: "brochure",           phonetic: "/ˈbrəʊʃə(r)/",        cn: "n.资料(或广告)手册" },
            { en: "package",            phonetic: "/ˈpækɪdʒ/",            cn: "n.包裹;包装盒 vt.将…包装" },
            { en: "package tour",       phonetic: "/ˈpækɪdʒ tʊə(r)/",   cn: "包价旅游" },
            { en: "contact",            phonetic: "/ˈkɒntækt/",           cn: "vt.联络;联系 n.联系;接触" },
            { en: "civilisation",       phonetic: "/sɪvɪlaɪˈzeɪʃən/",   cn: "n.文明;文明世界" },
            { en: "make up",            phonetic: "/meɪk ʌp/",            cn: "构成;形成" },
            { en: "soldier",            phonetic: "/ˈsəʊldʒə(r)/",       cn: "n.士兵;军人" },
            { en: "transport",          phonetic: "/ˈtrænspɔ:t/",        cn: "n.交通运输系统 vt.运输" },
            { en: "hike",               phonetic: "/haɪk/",               cn: "vi.徒步旅行 vt.去……远足" },
            { en: "economy",            phonetic: "/ɪˈkɒnəmi/",           cn: "n.经济;节约" },
            { en: "economic",           phonetic: "/ˌi:kəˈnɒmɪk/",      cn: "adj.经济(上)的;经济学的" },
            { en: "credit",             phonetic: "/ˈkredɪt/",            cn: "n.借款;信用;称赞;学分" },
            { en: "credit card",        phonetic: "/ˈkredɪt kɑ:d/",      cn: "信用卡" },
            { en: "detail",             phonetic: "/ˈdi:teɪl/",           cn: "n.细节;详情;细微之处" },
            { en: "check in",           phonetic: "/tʃek ɪn/",            cn: "(在旅馆、机场等)登记" },
            { en: "check out",          phonetic: "/tʃek aʊt/",           cn: "结账离开(旅馆等)" },
            { en: "request",            phonetic: "/rɪˈkwest/",           cn: "n.&vi.(正式的)要求;请求" },
            { en: "view",               phonetic: "/vju:/",               cn: "n.视野;景色;看法" },
            { en: "sight",              phonetic: "/saɪt/",               cn: "n.景象;视野;视力" },
            { en: "statue",             phonetic: "/ˈstætʃu:/",           cn: "n.雕塑;雕像" },
            { en: "BCE",                phonetic: "/bi:si:ˈi:/",          cn: "abbr.公元前" },
            { en: "tomb",               phonetic: "/tu:m/",               cn: "n.坟墓" },
            { en: "unearth",            phonetic: "/ʌnˈɜ:θ/",            cn: "vt.挖掘;发掘" },
            { en: "comment",            phonetic: "/ˈkɒment/",            cn: "n.&vi.&vt.议论;评论" },
            { en: "the Eiffel Tower",   phonetic: "/ðə ˈaɪfəl ˈtaʊə(r)/", cn: "埃菲尔铁塔" },
            { en: "Neuschwanstein Castle", phonetic: "",                  cn: "新天鹅堡" },
            { en: "Iceland",            phonetic: "/ˈaɪslənd/",           cn: "冰岛(国家名)" },
            { en: "Disneyland",         phonetic: "/ˈdɪznilænd/",        cn: "迪士尼乐园" },
            { en: "Peru",               phonetic: "/pəˈrʊ:/",            cn: "秘鲁(国家名)" },
            { en: "the Andes Mountains", phonetic: "/ðə ˈændiːz ˈmaʊntɪns/", cn: "安第斯山脉" },
            { en: "the Amazon rainforest", phonetic: "/ðə ˈæməzən ˈreɪnfɒrɪst/", cn: "亚马孙雨林" },
            { en: "the Inca Empire",    phonetic: "/ðə ˈiŋkə ˈempaɪə(r)/", cn: "印加帝国" },
            { en: "Machu Picchu",       phonetic: "",                      cn: "马丘比丘" },
            { en: "Spain",              phonetic: "/speɪn/",               cn: "西班牙" },
            { en: "Spanish",            phonetic: "/ˈspænɪʃ/",            cn: "n.&adj.西班牙(语/人)的" },
            { en: "Cusco",              phonetic: "/ˈku:skəu/",           cn: "库斯科(秘鲁城市)" },
            { en: "Lake Titicaca",      phonetic: "/leɪk ˌtitiˈkaka/",   cn: "的的喀喀湖" },
            { en: "the Uros",           phonetic: "",                      cn: "乌鲁斯人" },
            { en: "the Terracotta Army", phonetic: "/ðə ˌterəˈkɒtə ˈɑ:mi/", cn: "兵马俑" }
        ],

        "Unit 4": [
            { en: "fitness",            phonetic: "/ˈfɪtnəs/",            cn: "n.健康;健壮;适合" },
            { en: "soccer",             phonetic: "/ˈsɒkə(r)/",          cn: "n.足球" },
            { en: "stadium",            phonetic: "/ˈsteɪdiəm/",          cn: "n.体育场;运动场" },
            { en: "boxing",             phonetic: "/ˈbɒksɪŋ/",            cn: "n.拳击(运动)" },
            { en: "badminton",          phonetic: "/ˈbædmɪntən/",        cn: "n.羽毛球运动" },
            { en: "marathon",           phonetic: "/ˈmærəθən/",           cn: "n.马拉松赛跑" },
            { en: "event",              phonetic: "/ɪˈevent/",             cn: "n.比赛项目;大事;公开活动" },
            { en: "come along",         phonetic: "/kʌm əˈlɒŋ/",        cn: "跟随;到达;进步;赶快" },
            { en: "ski",                phonetic: "/ski:/",               cn: "adj.滑雪的 vi.滑雪" },
            { en: "host",               phonetic: "/həʊst/",              cn: "vt.主办;主持 n.主持人" },
            { en: "track",              phonetic: "/træk/",               cn: "n.跑道;足迹 vt.&vi.追踪" },
            { en: "track and field",    phonetic: "/træk ənd fi:ld/",    cn: "田径" },
            { en: "gym",                phonetic: "/dʒɪm/",               cn: "n.健身房;体育馆" },
            { en: "gymnastics",         phonetic: "/dʒɪmˈnæstɪks/",      cn: "n.体操(训练)" },
            { en: "work out",           phonetic: "/wɜ:k aʊt/",          cn: "锻炼;计算出;解决" },
            { en: "sweat",              phonetic: "/swet/",               cn: "vt.&vi.使出汗;流汗 n.汗水" },
            { en: "make it",            phonetic: "/meɪk ɪt/",            cn: "获得成功;准时到达" },
            { en: "legend",             phonetic: "/ˈledʒənd/",           cn: "n.传奇故事(或人物);传说" },
            { en: "athlete",            phonetic: "/ˈæθli:t/",            cn: "n.运动员;运动健儿" },
            { en: "master",             phonetic: "/ˈmɑ:stə(r)/",        cn: "n.高手;主人 vt.精通;掌握" },
            { en: "set an example",     phonetic: "/set ən ɪgˈzɑ:mpl/",  cn: "树立榜样" },
            { en: "honour",             phonetic: "/ˈɒnə(r)/",            cn: "n.荣誉;尊敬;荣幸" },
            { en: "glory",              phonetic: "/ˈglɔ:ri/",            cn: "n.荣誉;光荣;赞美" },
            { en: "medal",              phonetic: "/ˈmedl/",              cn: "n.奖章;勋章" },
            { en: "championship",       phonetic: "/ˈtʃæmpiənʃɪp/",     cn: "n.锦标赛;冠军赛;冠军称号" },
            { en: "champion",           phonetic: "/ˈtʃæmpiən/",         cn: "n.冠军;优胜者" },
            { en: "determination",      phonetic: "/dɪˌtɜ:mɪˈneɪʃn/",   cn: "n.决心;决定" },
            { en: "apart",              phonetic: "/əˈpɑ:t/",             cn: "adv.分离;分开;成碎片" },
            { en: "fall apart",         phonetic: "/fɔ:l əˈpɑ:t/",      cn: "破裂;破碎;崩溃" },
            { en: "injure",             phonetic: "/ˈɪndʒə(r)/",         cn: "vt.使受伤;损害" },
            { en: "injured",            phonetic: "/ˈɪndʒəd/",            cn: "adj.受伤的;有伤的" },
            { en: "injury",             phonetic: "/ˈɪndʒəri/",           cn: "n.伤害;损伤" },
            { en: "captain",            phonetic: "/ˈkæptɪn/",            cn: "n.(运动队)队长;船长;机长" },
            { en: "lose heart",         phonetic: "/lu:z hɑ:t/",         cn: "丧失信心;泄气" },
            { en: "graceful",           phonetic: "/ˈgreɪsfl/",           cn: "adj.优美的;优雅的" },
            { en: "strength",           phonetic: "/streŋθ/",             cn: "n.力量;体力" },
            { en: "failure",            phonetic: "/ˈfeɪljə(r)/",        cn: "n.失败;失败的人(或事物)" },
            { en: "give up",            phonetic: "/gɪv ʌp/",             cn: "放弃;投降" },
            { en: "compete",            phonetic: "/kəmˈpi:t/",           cn: "vi.竞争;对抗" },
            { en: "make sense",         phonetic: "/meɪk sens/",         cn: "有道理;合乎情理;表述清楚" },
            { en: "pretend",            phonetic: "/prɪˈtend/",           cn: "vi.&vt.假装;装扮" },
            { en: "pretend to do sth.", phonetic: "/prɪˈtend tə du ˈsʌmθɪŋ/", cn: "假装做某事" },
            { en: "even if",            phonetic: "/ˈi:vn ɪf/",           cn: "即使;虽然" },
            { en: "million",            phonetic: "/ˈmɪljən/",            cn: "num.一百万" },
            { en: "cheat",              phonetic: "/tʃi:t/",              cn: "vi.作弊;舞弊 vt.欺骗;蒙骗" },
            { en: "audience",           phonetic: "/ˈɔ:diəns/",           cn: "n.观众;听众" },
            { en: "positive",           phonetic: "/ˈpɒzətɪv/",          cn: "adj.积极的;正面的;乐观的" },
            { en: "slim",               phonetic: "/slɪm/",               cn: "adj.苗条的;单薄的" },
            { en: "diet",               phonetic: "/ˈdaɪət/",             cn: "n.规定饮食 vi.节食" },
            { en: "make a difference",  phonetic: "/meɪk ə ˈdɪfrəns/",   cn: "有作用或影响" },
            { en: "rather",             phonetic: "/ˈrɑ:ðə(r)/",         cn: "adv.相当;有点儿" },
            { en: "rather than",        phonetic: "/ˈrɑ:ðə(r) ðən/",    cn: "而不是" },
            { en: "push-up",            phonetic: "/pʊʃ ʌp/",             cn: "n.俯卧撑" },
            { en: "cut ... out",        phonetic: "/kʌt aʊt/",           cn: "停止做(或使用、食用);剪下" },
            { en: "now and then",       phonetic: "/naʊ ənd ðen/",      cn: "有时;偶尔" },
            { en: "compare ... with ...", phonetic: "/kəmˈpeə(r) wɪð/", cn: "与……比较" },
            { en: "jog",                phonetic: "/dʒɒg/",               cn: "vi.慢跑 n.慢跑" },
            { en: "stress",             phonetic: "/stres/",              cn: "n.压力;紧张 vt.强调;重读" },
            { en: "error",              phonetic: "/ˈerə(r)/",            cn: "n.错误;差错" }
        ],

        "Unit 5": [
            { en: "disaster",           phonetic: "/dɪˈzɑ:stə(r)/",     cn: "n.灾难;灾害" },
            { en: "tornado",            phonetic: "/tɔ:ˈneɪdʒʊ/",        cn: "n.龙卷风;旋风" },
            { en: "drought",            phonetic: "/draʊt/",              cn: "n.旱灾;久旱" },
            { en: "landslide",          phonetic: "/ˈlændslaɪd/",        cn: "n.(山地或悬崖的)崩塌;滑坡" },
            { en: "slide",              phonetic: "/slaɪd/",              cn: "vi.&vt.(使)滑行;滑动" },
            { en: "tsunami",            phonetic: "/tsu:ˈnɑ:mi/",        cn: "n.海啸" },
            { en: "flood",              phonetic: "/flʌd/",               cn: "n.洪水;大量 vi.淹没" },
            { en: "volcanic eruption",  phonetic: "/vɒlˈkænɪk ɪˈrʌpʃn/", cn: "火山喷发" },
            { en: "magnitude",          phonetic: "/ˈmægnɪtju:d/",       cn: "n.(地)震级;重大" },
            { en: "rescue",             phonetic: "/ˈreskju:/",           cn: "n.&vt.营救;救援" },
            { en: "damage",             phonetic: "/ˈdæmɪdʒ/",           cn: "vt.损害;破坏 n.损坏;损失" },
            { en: "destroy",            phonetic: "/dɪˈstrɔɪ/",          cn: "vt.摧毁;毁灭" },
            { en: "evacuate",           phonetic: "/ɪˈvækjueɪt/",       cn: "vt.疏散;撤出 vi.撤离" },
            { en: "helicopter",         phonetic: "/ˈhelɪkɒptə(r)/",    cn: "n.直升机" },
            { en: "death",              phonetic: "/deθ/",                cn: "n.死;死亡" },
            { en: "affect",             phonetic: "/əˈfekt/",             cn: "vt.影响;(疾病)侵袭" },
            { en: "shelter",            phonetic: "/ˈʃeltə(r)/",         cn: "n.避难处;居所 vt.保护" },
            { en: "crack",              phonetic: "/kræk/",               cn: "n.裂纹;裂缝 vi.&vt.使破裂" },
            { en: "gas",                phonetic: "/ɡæs/",                cn: "n.气体;燃气;汽油" },
            { en: "as if",              phonetic: "/əz ɪf/",              cn: "似乎;好像;仿佛" },
            { en: "ruin",               phonetic: "/ˈru:ɪn/",             cn: "n.&vt.破坏;毁坏" },
            { en: "in ruins",           phonetic: "/ɪn ˈru:ɪnz/",        cn: "严重受损;破败不堪" },
            { en: "percent",            phonetic: "/pəˈsent/",            cn: "n.百分之… adv.每一百中" },
            { en: "brick",              phonetic: "/brɪk/",               cn: "n.砖;砖块" },
            { en: "metal",              phonetic: "/ˈmetl/",              cn: "n.金属" },
            { en: "shock",              phonetic: "/ʃɒk/",                cn: "n.震惊;休克 vt.(使)震惊" },
            { en: "in shock",           phonetic: "/ɪn ʃɒk/",             cn: "震惊;吃惊" },
            { en: "electricity",        phonetic: "/ɪˌlekˈtrɪsəti/",    cn: "n.电;电能" },
            { en: "trap",               phonetic: "/træp/",               cn: "vt.使落入险境 n.险境;陷阱" },
            { en: "bury",               phonetic: "/ˈberi/",              cn: "vt.埋葬;安葬" },
            { en: "breathe",            phonetic: "/bri:ð/",              cn: "vi.&vt.呼吸" },
            { en: "revive",             phonetic: "/rɪˈvaɪv/",            cn: "vi.&vt.复活;(使)苏醒" },
            { en: "revival",            phonetic: "/rɪˈvaɪvl/",           cn: "n.振兴;复苏" },
            { en: "effort",             phonetic: "/ˈefət/",              cn: "n.努力;艰难的尝试;尽力" },
            { en: "unify",              phonetic: "/ˈju:nɪfaɪ/",          cn: "vi.&vt.统一;(使)成一体" },
            { en: "wisdom",             phonetic: "/ˈwɪzdəm/",            cn: "n.智慧;才智" },
            { en: "context",            phonetic: "/ˈkɒntekst/",          cn: "n.上下文;语境;背景" },
            { en: "suffer",             phonetic: "/ˈsʌfə(r)/",          cn: "vt.遭受;蒙受 vi.受苦" },
            { en: "volcano",            phonetic: "/vɒlˈkeɪnəʊ/",        cn: "n.火山" },
            { en: "erupt",              phonetic: "/ɪˈrʌpt/",             cn: "vi.&vt.火山爆发;岩浆喷出" },
            { en: "supply",             phonetic: "/səˈplaɪ/",            cn: "n.供应;补给 vt.供应;供给" },
            { en: "typhoon",            phonetic: "/taɪˈfu:n/",           cn: "n.台风" },
            { en: "in the open air",    phonetic: "/ɪn ðə ˈəʊpən eə(r)/", cn: "露天;在户外" },
            { en: "hurricane",          phonetic: "/ˈhʌrɪkən/",          cn: "n.(尤指西大西洋的)飓风" },
            { en: "survive",            phonetic: "/səˈvaɪv/",            cn: "vi.生存;存活 vt.幸存" },
            { en: "power",              phonetic: "/ˈpaʊə(r)/",          cn: "n.电力供应;能量;力量" },
            { en: "tap",                phonetic: "/tæp/",                cn: "vi.&vt.轻叩;轻敲 n.水龙头" },
            { en: "pipe",               phonetic: "/paɪp/",               cn: "n.管子;管道" },
            { en: "whistle",            phonetic: "/ˈwɪsl/",              cn: "vi.&vt.吹口哨 n.哨子(声)" },
            { en: "emergency",          phonetic: "/iˈmɜ:dʒənsi/",       cn: "n.突发事件;紧急情况" },
            { en: "calm",               phonetic: "/kɑ:m/",               cn: "adj.镇静的;沉着的 vt.使平静" },
            { en: "aid",                phonetic: "/eɪd/",                cn: "n.援助;帮助 vi.&vt.帮助" },
            { en: "kit",                phonetic: "/kɪt/",                cn: "n.成套工具;成套设备" },
            { en: "first aid kit",      phonetic: "/fɜ:st eɪd kɪt/",    cn: "急救箱" },
            { en: "on hand",            phonetic: "/ɒn hænd/",            cn: "现有(尤指帮助)" },
            { en: "crash",              phonetic: "/kræʃ/",               cn: "vt.&vi.碰撞;撞击 n.撞车" },
            { en: "sweep",              phonetic: "/swi:p/",              cn: "vt.&vi.打扫;清扫" },
            { en: "sweep away",         phonetic: "/swi:p əˈweɪ/",      cn: "消灭;彻底消除" },
            { en: "wave",               phonetic: "/weɪv/",               cn: "n.海浪;波浪 vi.&vt.挥手" },
            { en: "strike",             phonetic: "/straɪk/",             cn: "vi.&vt.侵袭;突击 n.罢工" },
            { en: "deliver",            phonetic: "/dɪˈlɪvə(r)/",       cn: "vi.&vt.传递;传达 vt.发表" },
            { en: "summary",            phonetic: "/ˈsʌməri/",            cn: "n.总结;概括;概要" },
            { en: "effect",             phonetic: "/ɪˈfekt/",             cn: "n.影响;结果;效果" },
            { en: "length",             phonetic: "/leŋθ/",               cn: "n.长;长度" },
            { en: "Ecuador",            phonetic: "/ˈekwədɔ:(r)/",       cn: "厄瓜多尔(国家名)" },
            { en: "Memphis",            phonetic: "/ˈmemfis/",            cn: "孟菲斯(美国城市)" },
            { en: "Alberta",            phonetic: "/ælˈbɜ:tə/",          cn: "艾伯塔省(加拿大省份)" },
            { en: "Colombo",            phonetic: "/kəˈlʌmbəu/",         cn: "科伦坡(斯里兰卡首都)" },
            { en: "Sri Lanka",          phonetic: "/sri: ˈlɑːŋkə/",     cn: "斯里兰卡(国家名)" },
            { en: "Indonesia",          phonetic: "/ˌɪndəʊˈni:zjə/",    cn: "印度尼西亚(国家名)" },
            { en: "Thailand",           phonetic: "/ˈtaɪlænd/",           cn: "泰国(国家名)" },
            { en: "Malaysia",           phonetic: "/məˈleɪʒə/",          cn: "马来西亚(国家名)" },
            { en: "Sumatra Island",     phonetic: "/sʊˈmɑːtrə ˈaɪlənd/", cn: "苏门答腊岛" },
            { en: "Chandra Theeravit",  phonetic: "",                     cn: "钱德拉·特拉维" }
        ],

        "Unit 6": [
            { en: "billion",            phonetic: "/ˈbɪljən/",            cn: "n.十亿" },
            { en: "native",             phonetic: "/ˈneɪtɪv/",            cn: "adj.本地的;土著的 n.本地人" },
            { en: "attitude",           phonetic: "/ˈætɪtju:d/",         cn: "n.态度;看法" },
            { en: "reference",          phonetic: "/ˈrefrəns/",           cn: "n.指称关系;参考" },
            { en: "refer",              phonetic: "/rɪˈfɜ:(r)/",         cn: "vi.提到;参考;查阅 vt.查询" },
            { en: "refer to",           phonetic: "/rɪˈfɜ:(r) tə/",      cn: "指的是;描述;提到;查阅" },
            { en: "system",             phonetic: "/ˈsɪstəm/",            cn: "n.体系;制度;系统" },
            { en: "despite",            phonetic: "/dɪˈspaɪt/",           cn: "prep.即使;尽管" },
            { en: "ups and downs",      phonetic: "/ʌps ənd daʊnz/",    cn: "浮沉;兴衰;荣辱" },
            { en: "factor",             phonetic: "/ˈfæktə(r)/",         cn: "n.因素;要素" },
            { en: "based",              phonetic: "/beɪst/",              cn: "adj.以(某事)为基础的" },
            { en: "base",               phonetic: "/beɪs/",               cn: "vt.以…为据点 n.底部;根据" },
            { en: "date back to ...",   phonetic: "/deɪt bæk tə/",      cn: "追溯到" },
            { en: "bone",               phonetic: "/bəʊn/",               cn: "n.骨头;骨(质)" },
            { en: "shell",              phonetic: "/ʃel/",                cn: "n.壳;壳状物" },
            { en: "symbol",             phonetic: "/ˈsɪmbl/",             cn: "n.符号;象征" },
            { en: "carve",              phonetic: "/kɑ:v/",               cn: "vt.&vi.雕刻" },
            { en: "dynasty",            phonetic: "/ˈdɪnəsti/",           cn: "n.王朝;朝代" },
            { en: "variety",            phonetic: "/vəˈraɪəti/",          cn: "n.(植物、语言等)变体;异体" },
            { en: "major",              phonetic: "/ˈmeɪdʒə(r)/",       cn: "adj.主要的;重要的 n.主修课" },
            { en: "no matter ...",      phonetic: "/nəʊ ˈmætə(r)/",     cn: "不论……;不管……" },
            { en: "dialect",            phonetic: "/ˈdaɪəlekt/",          cn: "n.地方话;方言" },
            { en: "means",              phonetic: "/mi:nz/",              cn: "n.方式;方法;途径" },
            { en: "classic",            phonetic: "/ˈklæsɪk/",            cn: "adj.传统的;最优秀的 n.名著" },
            { en: "regard",             phonetic: "/rɪˈgɑ:d/",           cn: "n.尊重;关注 vt.把……视为" },
            { en: "character",          phonetic: "/ˈkærəktə(r)/",      cn: "n.文字;符号;角色;品质" },
            { en: "calligraphy",        phonetic: "/kəˈlɪgrəfi/",        cn: "n.书法;书法艺术" },
            { en: "global",             phonetic: "/ˈgləʊbl/",            cn: "adj.全球的;全世界的" },
            { en: "affair",             phonetic: "/əˈfeə(r)/",          cn: "n.公共事务;事件;关系" },
            { en: "appreciate",         phonetic: "/əˈpri:ʃieɪt/",       cn: "vt.欣赏;重视;感激 vi.增值" },
            { en: "specific",           phonetic: "/spəˈsɪfɪk/",         cn: "adj.特定的;明确的;具体的" },
            { en: "CE",                 phonetic: "/si:ˈi:/",             cn: "abbr.(源自拉丁语)公元" },
            { en: "struggle",           phonetic: "/ˈstrʌgl/",            cn: "n.&vi.斗争;奋斗;搏斗" },
            { en: "tongue",             phonetic: "/tʌŋ/",                cn: "n.舌头;语言" },
            { en: "point of view",      phonetic: "/pɔɪnt əv vju:/",    cn: "观点;看法" },
            { en: "semester",           phonetic: "/sɪˈmestə(r)/",      cn: "n.学期" },
            { en: "petrol",             phonetic: "/ˈpetrəl/",            cn: "n.汽油" },
            { en: "subway",             phonetic: "/ˈsʌbweɪ/",            cn: "n.地铁" },
            { en: "apartment",          phonetic: "/əˈpɑ:tmənt/",        cn: "n.公寓套房" },
            { en: "pants",              phonetic: "/pænts/",              cn: "n.[pl.]内裤;短裤;裤子" },
            { en: "beg",                phonetic: "/beg/",                cn: "vt.恳求;祈求;哀求" },
            { en: "equal",              phonetic: "/ˈi:kwəl/",            cn: "n.同等人;相等物 adj.相同的" },
            { en: "gap",                phonetic: "/gæp/",                cn: "n.间隔;开口;差距" },
            { en: "demand",             phonetic: "/dɪˈmɑ:nd/",          cn: "n.要求;需求 vt.强烈要求" },
            { en: "vocabulary",         phonetic: "/vəˈkæbjələri/",      cn: "n.词汇" },
            { en: "description",        phonetic: "/dɪˈskrɪpʃn/",       cn: "n.描写(文字);形容" },
            { en: "relate",             phonetic: "/rɪˈleɪt/",            cn: "vt.联系;讲述" },
            { en: "relate to",          phonetic: "/rɪˈleɪt tə/",        cn: "与……相关;涉及;谈到" },
            { en: "Korean",             phonetic: "/kəˈrɪən/",           cn: "n.&adj.(朝鲜/韩国)(语/人)" },
            { en: "Danish",             phonetic: "/ˈdeɪnɪʃ/",           cn: "n.丹麦语;丹麦人 adj.丹麦的" },
            { en: "Denmark",            phonetic: "/ˈdenmɑ:k/",           cn: "丹麦(国家名)" },
            { en: "Arabic",             phonetic: "/ˈærəbɪk/",           cn: "n.&adj.阿拉伯语/文学(的)" },
            { en: "FIFA",               phonetic: "/ˈfi:fə/",             cn: "abbr.(源自法语)国际足联" }
        ]

    }

};
