var wordBank = wordBank || {};

wordBank["Think Starter"] = {

    "Welcome Unit": [
        // ---- 需掌握 ----
        { en: "blue", cn: "蓝色，蓝色的", phonetic: "/bluː/" },
        { en: "brown", cn: "棕色，棕色的", phonetic: "/braʊn/" },
        { en: "green", cn: "绿色，绿色的", phonetic: "/ɡriːn/" },
        { en: "grey", cn: "灰色，灰色的", phonetic: "/ɡreɪ/" },
        { en: "orange", cn: "橘色，橘色的", phonetic: "/ˈɒrɪndʒ/" },
        { en: "purple", cn: "紫色，紫色的", phonetic: "/ˈpɜːpl/" },
        { en: "yellow", cn: "黄色，黄色的", phonetic: "/ˈjeləʊ/" },
        { en: "airport", cn: "机场", phonetic: "/ˈeəpɔːt/" },
        { en: "hotel", cn: "酒店，旅馆", phonetic: "/həʊˈtel/" },
        { en: "pizza", cn: "披萨", phonetic: "/ˈpiːtsə/" },
        { en: "restaurant", cn: "餐厅", phonetic: "/ˈrestrɒnt/" },
        { en: "taxi", cn: "出租车", phonetic: "/ˈtæksi/" },
        { en: "tablet", cn: "平板", phonetic: "/ˈtæblət/" },
        { en: "morning", cn: "早晨，上午", phonetic: "/ˈmɔːnɪŋ/" },
        { en: "afternoon", cn: "下午", phonetic: "/ˌɑːftəˈnuːn/" },
        { en: "evening", cn: "晚上", phonetic: "/ˈiːvnɪŋ/" },
        { en: "night", cn: "夜晚", phonetic: "/naɪt/" },
        { en: "man", cn: "男人", phonetic: "/mæn/" },
        { en: "woman", cn: "女人", phonetic: "/ˈwʊmən/" },
        { en: "person", cn: "人", phonetic: "/ˈpɜːsn/" },
        { en: "child", cn: "孩子，儿童", phonetic: "/tʃaɪld/" },
        // ---- 只认读 ----
        { en: "black", cn: "黑色，黑色的", phonetic: "/blæk/", spell: false },
        { en: "pink", cn: "粉色，粉色的", phonetic: "/pɪŋk/", spell: false },
        { en: "red", cn: "红色，红色的", phonetic: "/red/", spell: false },
        { en: "white", cn: "白色，白色的", phonetic: "/waɪt/", spell: false },
        { en: "bus", cn: "公交车", phonetic: "/bʌs/", spell: false },
        { en: "café", cn: "咖啡馆", phonetic: "/ˈkæfeɪ/", spell: false },
        { en: "football", cn: "足球", phonetic: "/ˈfʊtbɔːl/", spell: false },
        { en: "hamburger", cn: "汉堡", phonetic: "/ˈhæmbɜːɡə(r)/", spell: false },
        { en: "phone", cn: "电话", phonetic: "/fəʊn/", spell: false },
        { en: "sandwich", cn: "三明治", phonetic: "/ˈsænwɪtʃ/", spell: false },
        { en: "T-shirt", cn: "T恤衫", phonetic: "/ˈtiː ʃɜːt/", spell: false },
        { en: "city", cn: "城市", phonetic: "/ˈsɪti/", spell: false },
        { en: "board", cn: "黑板", phonetic: "/bɔːd/", spell: false },
        { en: "book", cn: "书", phonetic: "/bʊk/", spell: false },
        { en: "chair", cn: "椅子", phonetic: "/tʃeə(r)/", spell: false },
        { en: "computer", cn: "电脑", phonetic: "/kəmˈpjuːtə(r)/", spell: false },
        { en: "desk", cn: "书桌", phonetic: "/desk/", spell: false },
        { en: "door", cn: "门", phonetic: "/dɔː(r)/", spell: false },
        { en: "pen", cn: "钢笔", phonetic: "/pen/", spell: false },
        { en: "pencil", cn: "铅笔", phonetic: "/ˈpensl/", spell: false },
        { en: "projector", cn: "投影仪", phonetic: "/prəˈdʒektə(r)/", spell: false },
        { en: "window", cn: "窗户", phonetic: "/ˈwɪndəʊ/", spell: false },
        { en: "zero", cn: "0", phonetic: "/ˈzɪərəʊ/", spell: false },
        { en: "one", cn: "1", phonetic: "/wʌn/", spell: false },
        { en: "two", cn: "2", phonetic: "/tuː/", spell: false },
        { en: "three", cn: "3", phonetic: "/θriː/", spell: false },
        { en: "four", cn: "4", phonetic: "/fɔː(r)/", spell: false },
        { en: "five", cn: "5", phonetic: "/faɪv/", spell: false },
        { en: "six", cn: "6", phonetic: "/sɪks/", spell: false },
        { en: "seven", cn: "7", phonetic: "/ˈsevn/", spell: false },
        { en: "eight", cn: "8", phonetic: "/eɪt/", spell: false },
        { en: "nine", cn: "9", phonetic: "/naɪn/", spell: false },
        { en: "ten", cn: "10", phonetic: "/ten/", spell: false },
        { en: "fourteen", cn: "14", phonetic: "/ˌfɔːˈtiːn/", spell: false },
        { en: "sixteen", cn: "16", phonetic: "/ˌsɪksˈtiːn/", spell: false },
        { en: "seventeen", cn: "17", phonetic: "/ˌsevnˈtiːn/", spell: false },
        { en: "eighteen", cn: "18", phonetic: "/ˌeɪˈtiːn/", spell: false },
        { en: "nineteen", cn: "19", phonetic: "/ˌnaɪnˈtiːn/", spell: false },
        { en: "sixty", cn: "60", phonetic: "/ˈsɪksti/", spell: false },
        { en: "seventy", cn: "70", phonetic: "/ˈsevnti/", spell: false },
        { en: "eighty", cn: "80", phonetic: "/ˈeɪti/", spell: false },
        { en: "ninety", cn: "90", phonetic: "/ˈnaɪnti/", spell: false },
        { en: "one hundred", cn: "100", phonetic: "/wʌn ˈhʌndrəd/", spell: false }
    ],

    "Unit 1": [
        // ---- 需掌握 ----
        { en: "China", cn: "中国", phonetic: "/ˈtʃaɪnə/" },
        { en: "Chinese", cn: "中国人，中国的", phonetic: "/ˌtʃaɪˈniːz/" },
        { en: "Japan", cn: "日本", phonetic: "/dʒəˈpæn/" },
        { en: "Japanese", cn: "日本人，日本的", phonetic: "/ˌdʒæpəˈniːz/" },
        { en: "the UK", cn: "英国", phonetic: "/ðə juː ˈkeɪ/" },
        { en: "British", cn: "英国人，英国的", phonetic: "/ˈbrɪtɪʃ/" },
        { en: "the US", cn: "美国", phonetic: "/ðə juː ˈes/" },
        { en: "American", cn: "美国人，美国的", phonetic: "/əˈmerɪkən/" },
        { en: "how", cn: "如何，怎么样", phonetic: "/haʊ/" },
        { en: "when", cn: "什么时候", phonetic: "/wen/" },
        { en: "singer", cn: "歌手", phonetic: "/ˈsɪŋə(r)/" },
        { en: "player", cn: "运动员", phonetic: "/ˈpleɪə(r)/" },
        { en: "pianist", cn: "钢琴家", phonetic: "/ˈpiːənɪst/" },
        { en: "great", cn: "伟大的，极好的", phonetic: "/ɡreɪt/" },
        { en: "awesome", cn: "了不起的，极好的", phonetic: "/ˈɔːsəm/" },
        { en: "musician", cn: "音乐家", phonetic: "/mjuˈzɪʃn/" },
        { en: "website", cn: "网站", phonetic: "/ˈwebsaɪt/" },
        { en: "what", cn: "什么", phonetic: "/wɒt/" },
        { en: "where", cn: "在哪里", phonetic: "/weə(r)/" },
        { en: "who", cn: "谁", phonetic: "/huː/" },
        { en: "why", cn: "为什么", phonetic: "/waɪ/" },
        { en: "which", cn: "哪一个", phonetic: "/wɪtʃ/" },
        { en: "fast", cn: "快速的", phonetic: "/fɑːst/" },
        { en: "slow", cn: "慢的", phonetic: "/sləʊ/" },
        { en: "cheap", cn: "便宜的", phonetic: "/tʃiːp/" },
        { en: "expensive", cn: "昂贵的", phonetic: "/ɪkˈspensɪv/" },
        { en: "clean", cn: "干净的；打扫", phonetic: "/kliːn/" },
        { en: "dirty", cn: "脏的", phonetic: "/ˈdɜːti/" },
        { en: "big", cn: "大的", phonetic: "/bɪɡ/" },
        { en: "small", cn: "小的", phonetic: "/smɔːl/" },
        { en: "new", cn: "新的", phonetic: "/njuː/" },
        { en: "old", cn: "旧的，年老的", phonetic: "/əʊld/" },
        { en: "actor", cn: "男演员", phonetic: "/ˈæktə(r)/" },
        { en: "fan", cn: "粉丝；风扇", phonetic: "/fæn/" },
        { en: "nice", cn: "美好的", phonetic: "/naɪs/" },
        { en: "meet", cn: "遇见", phonetic: "/miːt/" },
        { en: "country", cn: "国家", phonetic: "/ˈkʌntri/" },
        { en: "flag", cn: "旗帜", phonetic: "/flæɡ/" },
        { en: "athlete", cn: "运动员", phonetic: "/ˈæθliːt/" },
        { en: "favourite", cn: "最喜欢的", phonetic: "/ˈfeɪvərɪt/" },
        { en: "excited", cn: "激动的", phonetic: "/ɪkˈsaɪtɪd/" },
        { en: "life", cn: "生活", phonetic: "/laɪf/" },
        { en: "lesson", cn: "课程，教训", phonetic: "/ˈlesn/" },
        { en: "important", cn: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
        { en: "wait", cn: "等候", phonetic: "/weɪt/" },
        { en: "tomorrow", cn: "明天", phonetic: "/təˈmɒrəʊ/" },
        { en: "trip", cn: "出行，旅行", phonetic: "/trɪp/" },
        { en: "stress", cn: "压力", phonetic: "/stres/" },
        { en: "if", cn: "如果，是否", phonetic: "/ɪf/" },
        { en: "hour", cn: "小时", phonetic: "/ˈaʊə(r)/" },
        { en: "film star", cn: "电影明星", phonetic: "/ˈfɪlm stɑː(r)/" },
        { en: "How's it going?", cn: "最近怎么样？", phonetic: "" },
        { en: "See you later.", cn: "回头见。", phonetic: "" },
        { en: "That's awesome!", cn: "太棒了！", phonetic: "" },
        { en: "I know!", cn: "我懂！", phonetic: "" },
        // ---- 只认读 ----
        { en: "Brazil", cn: "巴西", phonetic: "/brəˈzɪl/", spell: false },
        { en: "Brazilian", cn: "巴西人", phonetic: "/brəˈzɪliən/", spell: false },
        { en: "Russia", cn: "俄罗斯", phonetic: "/ˈrʌʃə/", spell: false },
        { en: "Russian", cn: "俄罗斯人", phonetic: "/ˈrʌʃn/", spell: false },
        { en: "Africa", cn: "非洲", phonetic: "/ˈæfrɪkə/", spell: false },
        { en: "African", cn: "非洲人", phonetic: "/ˈæfrɪkən/", spell: false },
        { en: "Spain", cn: "西班牙", phonetic: "/speɪn/", spell: false },
        { en: "Spanish", cn: "西班牙人", phonetic: "/ˈspænɪʃ/", spell: false },
        { en: "Turkey", cn: "土耳其", phonetic: "/ˈtɜːki/", spell: false },
        { en: "Turkish", cn: "土耳其人", phonetic: "/ˈtɜːkɪʃ/", spell: false },
        { en: "guy", cn: "男人，家伙", phonetic: "/ɡaɪ/", spell: false },
        { en: "vlog", cn: "视频博客", phonetic: "/vlɒɡ/", spell: false },
        { en: "topic", cn: "主题，话题", phonetic: "/ˈtɒpɪk/", spell: false },
        { en: "patient", cn: "有耐心的", phonetic: "/ˈpeɪʃnt/", spell: false },
        { en: "next week", cn: "下周", phonetic: "/nekst wiːk/", spell: false },
        { en: "no problem", cn: "没问题", phonetic: "/nəʊ ˈprɒbləm/", spell: false },
        { en: "be calm", cn: "保持冷静", phonetic: "/biː kɑːm/", spell: false },
        { en: "no rush", cn: "别着急", phonetic: "/nəʊ rʌʃ/", spell: false },
        { en: "submarine", cn: "潜艇", phonetic: "/ˌsʌbməˈriːn/", spell: false }
    ],

    "Unit 2": [
        // ---- 需掌握 ----
        { en: "excited", cn: "感到兴奋的", phonetic: "/ɪkˈsaɪtɪd/" },
        { en: "angry", cn: "生气的", phonetic: "/ˈæŋɡri/" },
        { en: "hungry", cn: "饥饿的", phonetic: "/ˈhʌŋɡri/" },
        { en: "thirsty", cn: "口渴的", phonetic: "/ˈθɜːsti/" },
        { en: "bored", cn: "无聊的", phonetic: "/bɔːd/" },
        { en: "worried", cn: "担心的", phonetic: "/ˈwʌrid/" },
        { en: "tired", cn: "疲惫的", phonetic: "/ˈtaɪəd/" },
        { en: "party", cn: "派对", phonetic: "/ˈpɑːti/" },
        { en: "school", cn: "学校", phonetic: "/skuːl/" },
        { en: "cinema", cn: "电影院", phonetic: "/ˈsɪnəmə/" },
        { en: "computer shop", cn: "电脑店", phonetic: "/kəmˈpjuːtə ʃɒp/" },
        { en: "station", cn: "车站", phonetic: "/ˈsteɪʃn/" },
        { en: "at home", cn: "在家", phonetic: "/ət həʊm/" },
        { en: "at school", cn: "在学校", phonetic: "/ət skuːl/" },
        { en: "at the cinema", cn: "在电影院", phonetic: "/ət ðə ˈsɪnəmə/" },
        { en: "at the computer shop", cn: "在电脑店", phonetic: "/ət ðə kəmˈpjuːtə ʃɒp/" },
        { en: "at the station", cn: "在车站", phonetic: "/ət ðə ˈsteɪʃn/" },
        { en: "at the stadium", cn: "在体育馆", phonetic: "/ət ðə ˈsteɪdiəm/" },
        { en: "exciting", cn: "令人兴奋的", phonetic: "/ɪkˈsaɪtɪŋ/" },
        { en: "good", cn: "好的", phonetic: "/ɡʊd/" },
        { en: "funny", cn: "有趣的", phonetic: "/ˈfʌni/" },
        { en: "excellent", cn: "极好的", phonetic: "/ˈeksələnt/" },
        { en: "awful", cn: "极差的", phonetic: "/ˈɔːfl/" },
        { en: "terrible", cn: "糟糕的", phonetic: "/ˈterəbl/" },
        { en: "bad", cn: "坏的", phonetic: "/bæd/" },
        { en: "I", cn: "我", phonetic: "/aɪ/" },
        { en: "me", cn: "我", phonetic: "/miː/" },
        { en: "we", cn: "我们", phonetic: "/wiː/" },
        { en: "us", cn: "我们", phonetic: "/ʌs/" },
        { en: "you", cn: "你；你们", phonetic: "/juː/" },
        { en: "he", cn: "他", phonetic: "/hiː/" },
        { en: "him", cn: "他", phonetic: "/hɪm/" },
        { en: "she", cn: "她", phonetic: "/ʃiː/" },
        { en: "her", cn: "她", phonetic: "/hɜː(r)/" },
        { en: "it", cn: "它", phonetic: "/ɪt/" },
        { en: "they", cn: "他们；她们；它们", phonetic: "/ðeɪ/" },
        { en: "them", cn: "他们；她们；它们", phonetic: "/ðəm/" },
        // ---- 只认读 ----
        { en: "home", cn: "家", phonetic: "/həʊm/", spell: false },
        { en: "stadium", cn: "体育馆", phonetic: "/ˈsteɪdiəm/", spell: false },
        { en: "hot", cn: "热的", phonetic: "/hɒt/", spell: false },
        { en: "cold", cn: "冷的", phonetic: "/kəʊld/", spell: false },
        { en: "sad", cn: "难过的", phonetic: "/sæd/", spell: false },
        { en: "sales assistant", cn: "销售员", phonetic: "/ˈseɪlz əˈsɪstənt/", spell: false },
        { en: "war", cn: "战争", phonetic: "/wɔː(r)/", spell: false },
        { en: "late", cn: "晚的", phonetic: "/leɪt/", spell: false },
        { en: "tonight", cn: "今晚", phonetic: "/təˈnaɪt/", spell: false },
        { en: "a bit", cn: "有点儿", phonetic: "/ə bɪt/", spell: false },
        { en: "on holiday", cn: "在度假", phonetic: "/ɒn ˈhɒlədeɪ/", spell: false },
        { en: "difficult", cn: "困难的", phonetic: "/ˈdɪfɪkəlt/", spell: false },
        { en: "easy", cn: "简单的", phonetic: "/ˈiːzi/", spell: false },
        { en: "concert", cn: "演唱会", phonetic: "/ˈkɒnsət/", spell: false },
        { en: "surprise", cn: "惊喜", phonetic: "/səˈpraɪz/", spell: false },
        { en: "ticket", cn: "门票", phonetic: "/ˈtɪkɪt/", spell: false },
        { en: "festival", cn: "节日", phonetic: "/ˈfestɪvl/", spell: false },
        { en: "mask", cn: "面具，口罩", phonetic: "/mɑːsk/", spell: false },
        { en: "popular", cn: "受欢迎的", phonetic: "/ˈpɒpjələ(r)/", spell: false },
        { en: "medicine", cn: "药品", phonetic: "/ˈmedsn/", spell: false },
        { en: "different", cn: "不同的", phonetic: "/ˈdɪfrənt/", spell: false },
        { en: "Halloween", cn: "万圣节", phonetic: "/ˌhæləʊˈiːn/", spell: false }
    ],

    "Unit 3": [
        // ---- 需掌握 ----
        { en: "actress", cn: "女演员", phonetic: "/ˈæktrəs/" },
        { en: "born", cn: "出生", phonetic: "/bɔːn/" },
        { en: "twins", cn: "双胞胎", phonetic: "/twɪnz/" },
        { en: "husband", cn: "丈夫", phonetic: "/ˈhʌzbənd/" },
        { en: "wife", cn: "妻子", phonetic: "/waɪf/" },
        { en: "son", cn: "儿子", phonetic: "/sʌn/" },
        { en: "daughter", cn: "女儿", phonetic: "/ˈdɔːtə(r)/" },
        { en: "aunt", cn: "阿姨，姑姨", phonetic: "/ɑːnt/" },
        { en: "uncle", cn: "叔叔，舅伯", phonetic: "/ˈʌŋkl/" },
        { en: "cousin", cn: "堂/表兄弟姐妹", phonetic: "/ˈkʌzn/" },
        { en: "mother", cn: "妈妈", phonetic: "/ˈmʌðə(r)/" },
        { en: "father", cn: "爸爸", phonetic: "/ˈfɑːðə(r)/" },
        { en: "brother", cn: "兄弟", phonetic: "/ˈbrʌðə(r)/" },
        { en: "sister", cn: "姐妹", phonetic: "/ˈsɪstə(r)/" },
        { en: "my", cn: "我的", phonetic: "/maɪ/" },
        { en: "mine", cn: "我的", phonetic: "/maɪn/" },
        { en: "your", cn: "你的；你们的", phonetic: "/jɔː(r)/" },
        { en: "yours", cn: "你的；你们的", phonetic: "/jɔːz/" },
        { en: "his", cn: "他的", phonetic: "/hɪz/" },
        { en: "her", cn: "她的", phonetic: "/hɜː(r)/" },
        { en: "hers", cn: "她的", phonetic: "/hɜːz/" },
        { en: "its", cn: "它的", phonetic: "/ɪts/" },
        { en: "our", cn: "我们的", phonetic: "/ˈaʊə(r)/" },
        { en: "ours", cn: "我们的", phonetic: "/ˈaʊəz/" },
        { en: "their", cn: "他们的；她们的；它们的", phonetic: "/ðeə(r)/" },
        { en: "theirs", cn: "他们的；她们的；它们的", phonetic: "/ðeəz/" },
        { en: "shower", cn: "淋浴器", phonetic: "/ˈʃaʊə(r)/" },
        { en: "cooker", cn: "炉灶", phonetic: "/ˈkʊkə(r)/" },
        { en: "bath", cn: "浴缸", phonetic: "/bɑːθ/" },
        { en: "armchair", cn: "扶手椅", phonetic: "/ˈɑːmtʃeə(r)/" },
        { en: "bed", cn: "床", phonetic: "/bed/" },
        { en: "toilet", cn: "马桶", phonetic: "/ˈtɔɪlət/" },
        { en: "sofa", cn: "沙发", phonetic: "/ˈsəʊfə/" },
        { en: "fridge", cn: "冰箱", phonetic: "/frɪdʒ/" },
        { en: "bathroom", cn: "卫生间", phonetic: "/ˈbɑːθruːm/" },
        { en: "bedroom", cn: "卧室", phonetic: "/ˈbedruːm/" },
        { en: "living room", cn: "客厅", phonetic: "/ˈlɪvɪŋ ruːm/" },
        { en: "garage", cn: "车库", phonetic: "/ˈɡærɑːʒ/" },
        { en: "hall", cn: "走廊，大厅", phonetic: "/hɔːl/" },
        { en: "kitchen", cn: "厨房", phonetic: "/ˈkɪtʃɪn/" },
        { en: "garden", cn: "花园", phonetic: "/ˈɡɑːdn/" },
        { en: "this", cn: "这个", phonetic: "/ðɪs/" },
        { en: "that", cn: "那个", phonetic: "/ðæt/" },
        { en: "these", cn: "这些", phonetic: "/ðiːz/" },
        { en: "those", cn: "那些", phonetic: "/ðəʊz/" },
        { en: "here", cn: "在这里", phonetic: "/hɪə(r)/" },
        { en: "there", cn: "在那里", phonetic: "/ðeə(r)/" },
        { en: "real", cn: "真实的", phonetic: "/rɪəl/" },
        { en: "perfect", cn: "完美的", phonetic: "/ˈpɜːfɪkt/" },
        { en: "comfortable", cn: "舒服的", phonetic: "/ˈkʌmftəbl/" },
        { en: "right", cn: "对的；右边", phonetic: "/raɪt/" },
        { en: "wrong", cn: "错的", phonetic: "/rɒŋ/" },
        { en: "Oh right.", cn: "哦，是的。", phonetic: "" },
        { en: "Really?", cn: "真的吗？", phonetic: "" },
        { en: "Just a minute.", cn: "稍等一下。", phonetic: "" },
        { en: "Let's go.", cn: "我们走吧。", phonetic: "" },
        // ---- 只认读 ----
        { en: "ambassador", cn: "大使", phonetic: "/æmˈbæsədə(r)/", spell: false },
        { en: "Australia", cn: "澳大利亚", phonetic: "/ɒˈstreɪliə/", spell: false },
        { en: "Australian", cn: "澳大利亚人", phonetic: "/ɒˈstreɪliən/", spell: false }
    ],

    "Unit 4": [
        // ---- 需掌握 ----
        { en: "local", cn: "当地的", phonetic: "/ˈləʊkl/" },
        { en: "palace", cn: "宫殿", phonetic: "/ˈpæləs/" },
        { en: "park", cn: "公园", phonetic: "/pɑːk/" },
        { en: "square", cn: "广场", phonetic: "/skweə(r)/" },
        { en: "statue", cn: "雕像", phonetic: "/ˈstætʃuː/" },
        { en: "bank", cn: "银行", phonetic: "/bæŋk/" },
        { en: "chemist", cn: "药店，药房", phonetic: "/ˈkemɪst/" },
        { en: "library", cn: "图书馆", phonetic: "/ˈlaɪbrəri/" },
        { en: "museum", cn: "博物馆", phonetic: "/mjuˈziːəm/" },
        { en: "restaurant", cn: "餐厅", phonetic: "/ˈrestrɒnt/" },
        { en: "supermarket", cn: "超市", phonetic: "/ˈsuːpəmɑːkɪt/" },
        { en: "train station", cn: "火车站", phonetic: "/treɪn ˈsteɪʃn/" },
        { en: "in front of", cn: "在……前面", phonetic: "/ɪn frʌnt ɒv/" },
        { en: "behind", cn: "在……后面", phonetic: "/bɪˈhaɪnd/" },
        { en: "between", cn: "在……中间", phonetic: "/bɪˈtwiːn/" },
        { en: "next to", cn: "在……旁边", phonetic: "/nekst tuː/" },
        { en: "opposite", cn: "在……对面", phonetic: "/ˈɒpəzɪt/" },
        { en: "on the corner of", cn: "在……的角落", phonetic: "/ɒn ðə ˈkɔːnə(r) ɒv/" },
        { en: "on the left", cn: "在左边", phonetic: "/ɒn ðə left/" },
        { en: "on the right", cn: "在右边", phonetic: "/ɒn ðə raɪt/" },
        { en: "turn", cn: "转向", phonetic: "/tɜːn/" },
        { en: "street", cn: "街道", phonetic: "/striːt/" },
        { en: "eleven", cn: "11", phonetic: "/ɪˈlevn/" },
        { en: "twelve", cn: "12", phonetic: "/twelv/" },
        { en: "thirteen", cn: "13", phonetic: "/ˌθɜːˈtiːn/" },
        { en: "fifteen", cn: "15", phonetic: "/ˌfɪfˈtiːn/" },
        { en: "twenty", cn: "20", phonetic: "/ˈtwenti/" },
        { en: "thirty", cn: "30", phonetic: "/ˈθɜːti/" },
        { en: "forty", cn: "40", phonetic: "/ˈfɔːti/" },
        { en: "fifty", cn: "50", phonetic: "/ˈfɪfti/" },
        { en: "hundred", cn: "百", phonetic: "/ˈhʌndrəd/" },
        { en: "thousand", cn: "千", phonetic: "/ˈθaʊznd/" },
        { en: "path", cn: "小路", phonetic: "/pɑːθ/" },
        { en: "view", cn: "风景", phonetic: "/vjuː/" },
        { en: "public", cn: "公共的", phonetic: "/ˈpʌblɪk/" },
        { en: "lovely", cn: "可爱的，美丽的", phonetic: "/ˈlʌvli/" },
        { en: "modern", cn: "现代的", phonetic: "/ˈmɒdn/" },
        { en: "visit", cn: "参观，拜访", phonetic: "/ˈvɪzɪt/" },
        { en: "visitor", cn: "参观者，游客", phonetic: "/ˈvɪzɪtə(r)/" },
        { en: "building", cn: "建筑", phonetic: "/ˈbɪldɪŋ/" },
        { en: "adult", cn: "成年人", phonetic: "/ˈædʌlt/" },
        { en: "change", cn: "零钱；改变", phonetic: "/tʃeɪndʒ/" },
        { en: "trainers", cn: "球鞋", phonetic: "/ˈtreɪnəz/" },
        { en: "machine", cn: "机器", phonetic: "/məˈʃiːn/" },
        { en: "interesting", cn: "有趣的", phonetic: "/ˈɪntrəstɪŋ/" },
        { en: "important", cn: "重要的", phonetic: "/ɪmˈpɔːtnt/" },
        // ---- 只认读 ----
        { en: "fountain", cn: "喷泉", phonetic: "/ˈfaʊntən/", spell: false },
        { en: "castle", cn: "城堡", phonetic: "/ˈkɑːsl/", spell: false },
        { en: "bridge", cn: "桥", phonetic: "/brɪdʒ/", spell: false },
        { en: "cable car", cn: "缆车", phonetic: "/ˈkeɪbl kɑː(r)/", spell: false }
    ]

};