// ============================================
//  背单词 · 单词数据文件（必修一·完整版）
// ============================================

const wordBank = {

    "必修1": {

        "Unit 1": [
            { en: "exchange",           phonetic: "/ɪksˈtʃeɪndʒ/",       cn: "n.&vt.交换;交流;交易;兑换" },
            { en: "lecture",            phonetic: "/ˈlektʃə(r)/",         cn: "n.讲座;讲课 vi.(开)讲座" },
            { en: "registration",       phonetic: "/ˌredʒɪˈstreɪʃn/",    cn: "n.登记;注册;挂号" },
            { en: "register",           phonetic: "/ˈredʒɪstə(r)/",      cn: "vt.&vi.登记;注册" },
            { en: "sex",                phonetic: "/seks/",               cn: "n.性别" },
            { en: "female",             phonetic: "/ˈfi:meɪl/",           cn: "adj.女(性)的;雌的 n.雌性" },
            { en: "male",               phonetic: "/meɪl/",               cn: "adj.男(性)的;雄的 n.雄性" },
            { en: "nationality",        phonetic: "/ˌnæʃəˈnæləti/",      cn: "n.国籍;民族" },
            { en: "nation",             phonetic: "/ˈneɪʃn/",             cn: "n.国家;民族;国民" },
            { en: "designer",           phonetic: "/dɪˈzaɪnə(r)/",       cn: "n.设计者" },
            { en: "design",             phonetic: "/dɪˈzaɪn/",            cn: "n.设计;设计方案 vt.设计" },
            { en: "campus",             phonetic: "/ˈkæmpəs/",            cn: "n.校园;校区" },
            { en: "formal",             phonetic: "/ˈfɔ:ml/",             cn: "adj.正式的;正规的" },
            { en: "anxious",            phonetic: "/ˈæŋkʃəs/",            cn: "adj.焦虑的;不安的" },
            { en: "annoyed",            phonetic: "/əˈnɔɪd/",             cn: "adj.恼怒的;生气的" },
            { en: "annoy",              phonetic: "/əˈnɔɪ/",              cn: "vt.使恼怒;打扰" },
            { en: "frightened",         phonetic: "/ˈfraɪtnd/",           cn: "adj.惊吓的;害怕的" },
            { en: "p.m.",               phonetic: "/pi: em/",             cn: "abbr.(源自拉丁)下午;午后" },
            { en: "a.m.",               phonetic: "/ə em/",               cn: "abbr.(源自拉丁)上午;午前" },
            { en: "senior",             phonetic: "/ˈsi:niə(r)/",         cn: "adj.级别高的 n.较年长的人" },
            { en: "senior high school", phonetic: "/ˈsi:niə(r) haɪ sku:l/", cn: "(美国)高中" },
            { en: "at last",            phonetic: "/ət lɑ:st/",           cn: "终于;最终" },
            { en: "outgoing",           phonetic: "/ˈaʊtgəʊɪŋ/",         cn: "adj.爱交际的;外向的" },
            { en: "impression",         phonetic: "/ɪmˈpreʃn/",           cn: "n.印象;感想" },
            { en: "impress",            phonetic: "/ɪmˈpres/",            cn: "vt.使钦佩 vi.留下印象" },
            { en: "Make an impression", phonetic: "/meɪk ən ɪmˈpreʃn/",  cn: "留下好印象" },
            { en: "what if",            phonetic: "/wɒt ɪf/",             cn: "要是……会怎么样呢？" },
            { en: "guy",                phonetic: "/gaɪ/",                cn: "n.小伙子;男人;家伙" },
            { en: "concentrate",        phonetic: "/ˈkɒnsntreɪt/",       cn: "vi.&vt.集中注意;聚精会神" },
            { en: "concentrate on",     phonetic: "/ˈkɒnsntreɪt ɒn/",    cn: "集中精力于" },
            { en: "experiment",         phonetic: "/ɪkˈsperɪmənt/",      cn: "n.实验;试验" },
            { en: "leave ... alone",    phonetic: "/li:v əˈləʊn/",       cn: "不打扰;不惊动" },
            { en: "awkward",            phonetic: "/ˈɔ:kwəd/",            cn: "adj.令人尴尬的;难对付的" },
            { en: "junior",             phonetic: "/ˈdʒu:niə(r)/",        cn: "adj.地位低的 n.职位较低者" },
            { en: "junior high school", phonetic: "/ˈdʒu:niə(r) haɪ sku:l/", cn: "(美国)初级中学" },
            { en: "explore",            phonetic: "/ɪkˈsplɔ:(r)/",       cn: "vt.&vi.搜索;勘探" },
            { en: "confident",          phonetic: "/ˈkɒnfɪdənt/",        cn: "adj.自信的;有把握的" },
            { en: "confidence",         phonetic: "/ˈkɒnfɪdəns/",        cn: "n.信心;信任" },
            { en: "forward",            phonetic: "/ˈfɔ:wəd/",            cn: "adv.向前;前进 adj.向前的" },
            { en: "look forward to",    phonetic: "/lʊk ˈfɔ:wəd tə/",    cn: "盼望;期待" },
            { en: "take notes",         phonetic: "/teɪk nəuts/",        cn: "记笔记" },
            { en: "flash",              phonetic: "/flæʃ/",               cn: "n.光;信号 vi.闪耀;闪光" },
            { en: "flash card",         phonetic: "/flæʃ kɑ:d/",         cn: "教学卡片;识字卡" },
            { en: "organise",           phonetic: "/ˈɔ:gənaɪz/",         cn: "vt.组织;筹备 vi.组建;成立" },
            { en: "organisation",       phonetic: "/ˌɔ:gənaɪˈzeɪʃən/",  cn: "n.组织;团体;机构" },
            { en: "goal",               phonetic: "/gəʊl/",               cn: "n.目标;球门;射门" },
            { en: "strategy",           phonetic: "/ˈstrætədʒi/",        cn: "n.策略;策划" },
            { en: "partner",            phonetic: "/ˈpɑ:tnə(r)/",        cn: "n.同伴;配偶;合伙人" },
            { en: "improve",            phonetic: "/ɪmˈpru:v/",           cn: "vi.&vt.改进;改善" },
            { en: "curious",            phonetic: "/ˈkjʊəriəs/",         cn: "adj.好奇的;求知欲强的" },
            { en: "company",            phonetic: "/ˈkʌmpəni/",           cn: "n.公司;商行;陪伴" },
            { en: "personality",        phonetic: "/ˌpɜ:səˈnæləti/",     cn: "n.性格;个性" },
            { en: "style",              phonetic: "/staɪl/",              cn: "n.方式;作风" },
            { en: "revise",             phonetic: "/rɪˈvaɪz/",            cn: "vt.&vi.修改;修订;复习" }
        ],

        "Unit 2": [
            { en: "teenage",            phonetic: "/ˈti:neɪdʒ/",          cn: "adj.十几岁的;青少年的" },
            { en: "teenager",           phonetic: "/ˈti:neɪdʒə(r)/",     cn: "n.(13至19岁之间的)青少年" },
            { en: "ballet",             phonetic: "/ˈbæleɪ/",             cn: "n.芭蕾舞" },
            { en: "volunteer",          phonetic: "/ˌvɒlənˈtɪə(r)/",     cn: "n.志愿者" },
            { en: "debate",             phonetic: "/dɪˈbeɪt/",            cn: "n.辩论;争论 vt.&vi.辩论" },
            { en: "prefer",             phonetic: "/prɪˈfɜ:(r)/",        cn: "vt.较喜欢" },
            { en: "prefer ... to ...",  phonetic: "/prɪˈfɜ:(r) tə/",     cn: "喜欢……多于……" },
            { en: "content",            phonetic: "/ˈkɒntent/",           cn: "n.内容;[pl.]目录" },
            { en: "movement",           phonetic: "/ˈmu:vmənt/",          cn: "n.动作;运动;活动" },
            { en: "greenhouse",         phonetic: "/ˈgri:nhaʊs/",         cn: "n.温室;暖房" },
            { en: "clean up",           phonetic: "/kli:n ʌp/",           cn: "打扫(或清除)干净" },
            { en: "suitable",           phonetic: "/ˈsu:təbl/",           cn: "adj.合适的;适用的" },
            { en: "suitable for",       phonetic: "/ˈsu:təbl fə(r)/",    cn: "对……适合的" },
            { en: "actually",           phonetic: "/ˈæktʃuəli/",          cn: "adv.事实上;的确" },
            { en: "challenge",          phonetic: "/ˈtʃæləndʒ/",         cn: "n.挑战;艰巨任务 vt.怀疑" },
            { en: "title",              phonetic: "/ˈtaɪtl/",             cn: "n.(书、诗歌等)名称;标题" },
            { en: "topic",              phonetic: "/ˈtɒpɪk/",             cn: "n.话题;标题" },
            { en: "freshman",           phonetic: "/ˈfreʃmən/",           cn: "n.中学九年级学生;大学新生" },
            { en: "confusing",          phonetic: "/kənˈfju:zɪŋ/",       cn: "adj.难以理解的;不清楚的" },
            { en: "confuse",            phonetic: "/kənˈfju:z/",         cn: "vt.使糊涂;使迷惑" },
            { en: "Confused",           phonetic: "/kənˈfju:zd/",        cn: "adj.糊涂的;迷惑的" },
            { en: "fluent",             phonetic: "/ˈflu:ənt/",           cn: "adj.(外语)流利的;熟练的" },
            { en: "graduate",           phonetic: "/ˈgrædʒuət/",         cn: "vi.&vt.毕业 n.毕业生" },
            { en: "recommend",          phonetic: "/ˌrekəˈmend/",        cn: "vt.建议;推荐;介绍" },
            { en: "sign up for sth.",   phonetic: "/saɪn ʌp fə(r) ˈsʌmθɪŋ/", cn: "报名参加课程" },
            { en: "advanced",           phonetic: "/ədˈvɑ:nst/",          cn: "adj.高级的;高等的;先进的" },
            { en: "advance",            phonetic: "/ədˈvɑ:ns/",           cn: "n.&vi.&vt.前进;发展;促进" },
            { en: "literature",         phonetic: "/ˈlɪtrətʃə(r)/",      cn: "n.文学;文学作品" },
            { en: "extra-curricular",   phonetic: "/ˈekstrə kəˈrɪkjələ(r)/", cn: "adj.课外的;课程以外的" },
            { en: "extra",              phonetic: "/ˈekstrə/",            cn: "adj.额外的;附加的" },
            { en: "obviously",          phonetic: "/ˈɒbviəsli/",          cn: "adv.显然;明显地" },
            { en: "quit",               phonetic: "/kwɪt/",               cn: "vi.&vt.停止;戒掉;离开" },
            { en: "responsible",        phonetic: "/rɪˈspɒnsəbl/",       cn: "adj.负责的;有责任的" },
            { en: "responsibility",     phonetic: "/rɪˌspɒnsəˈbɪləti/",  cn: "n.责任;义务" },
            { en: "be responsible for", phonetic: "/bi rɪˈspɒnsəbl fə(r)/", cn: "对……负责" },
            { en: "solution",           phonetic: "/səˈlu:ʃn/",           cn: "n.解决办法;答案" },
            { en: "schedule",           phonetic: "/ˈʃedju:l/",           cn: "n.工作计划 vt.安排;预定" },
            { en: "editor",             phonetic: "/ˈedɪtə(r)/",         cn: "n.主编;编辑;编者" },
            { en: "plate",              phonetic: "/pleɪt/",              cn: "n.盘子;碟子" },
            { en: "adventure",          phonetic: "/ədˈventʃə(r)/",      cn: "n.冒险;奇遇" },
            { en: "youth",              phonetic: "/ju:θ/",               cn: "n.青年时期;青春" },
            { en: "expert",             phonetic: "/ˈekspɜ:t/",           cn: "n.专家;行家 adj.熟练的" },
            { en: "behaviour",          phonetic: "/bɪˈheɪvjə(r)/",      cn: "n.行为;举止" },
            { en: "generation",         phonetic: "/ˌdʒenəˈreɪʃn/",     cn: "n.一代(人)" },
            { en: "attract",            phonetic: "/əˈtrækt/",            cn: "vt.吸引;引起…注意(兴趣)" },
            { en: "be attracted to",    phonetic: "/bi əˈtræktid tə/",   cn: "喜爱" },
            { en: "focus",              phonetic: "/ˈfəʊkəs/",            cn: "vi.&vt.集中精力等 n.焦点" },
            { en: "focus on",           phonetic: "/ˈfəʊkəs ɒn/",        cn: "集中;特别关注" },
            { en: "addicted",           phonetic: "/əˈdɪktɪd/",           cn: "adj.有瘾的;上瘾的;入迷的" },
            { en: "addict",             phonetic: "/ˈædɪkt/",             cn: "n.对…入迷的人;吸毒成瘾者" },
            { en: "addicted to",        phonetic: "/əˈdɪktɪd tə/",       cn: "对……很入迷" },
            { en: "adult",              phonetic: "/ˈædʌlt/",             cn: "n.成年人 adj.成年的" },
            { en: "Chicago",            phonetic: "/ʃɪˈkɑ:gəʊ/",         cn: "芝加哥(美国城市)" },
            { en: "Seoul",              phonetic: "/səʊl/",               cn: "首尔(韩国首都)" }
        ],

        "Unit 3": [
            { en: "castle",             phonetic: "/ˈkɑ:sl/",             cn: "n.城堡;堡垒" },
            { en: "apply",              phonetic: "/əˈplaɪ/",             cn: "vi.&vt.申请;请求 vt.应用" },
            { en: "apply for",          phonetic: "/əˈplaɪ fə(r)/",      cn: "申请" },
            { en: "visa",               phonetic: "/ˈvi:zə/",             cn: "n.签证" },
            { en: "rent",               phonetic: "/rent/",               cn: "vt.&vi.租用;出租 n.租金" },
            { en: "pack",               phonetic: "/pæk/",                cn: "vi.&vt.收拾(行李);包装" },
            { en: "amazing",            phonetic: "/əˈmeɪzɪŋ/",           cn: "adj.令人惊奇的;令人惊喜的" },
            { en: "amazed",             phonetic: "/əˈmeɪzd/",            cn: "adj.惊奇的;惊喜的" },
            { en: "arrangement",        phonetic: "/əˈreɪndʒmənt/",      cn: "n.安排;筹备" },
            { en: "extremely",          phonetic: "/ɪkˈstri:mli/",        cn: "adv.极其;非常" },
            { en: "source",             phonetic: "/sɔ:s/",               cn: "n.来源;出处" },
            { en: "narrow",             phonetic: "/ˈnærəʊ/",             cn: "adj.狭窄的 vi.&vt.使变窄" },
            { en: "flat",               phonetic: "/flæt/",               cn: "adj.平坦的;扁平的 n.公寓" },
            { en: "powerful",           phonetic: "/ˈpaʊəfl/",            cn: "adj.强有力的;有权势的" },
            { en: "empire",             phonetic: "/ˈempaɪə(r)/",        cn: "n.帝国" },
            { en: "emperor",            phonetic: "/ˈempərə(r)/",        cn: "n.皇帝" },
            { en: "site",               phonetic: "/saɪt/",               cn: "n.地点;位置;现场" },
            { en: "take control of",    phonetic: "/teɪk kənˈtrəʊl əv/", cn: "控制;接管" },
            { en: "official",           phonetic: "/əˈfɪʃl/",             cn: "adj.官方的;正式的 n.官员" },
            { en: "recognise",          phonetic: "/ˈrekəgnaɪz/",        cn: "vt.辨别出;承认;认可" },
            { en: "type",               phonetic: "/taɪp/",               cn: "n.类型;种类 vi.&vt.打字" },
            { en: "flight",             phonetic: "/flaɪt/",              cn: "n.空中航行;航班;航程" },
            { en: "accommodation",      phonetic: "/əˌkɒməˈdeɪʃn/",     cn: "n.住处;停留处;膳宿" },
            { en: "unique",             phonetic: "/juˈni:k/",            cn: "adj.唯一的;独特的;特有的" },
            { en: "path",               phonetic: "/pɑ:θ/",               cn: "n.小路;路线;道路" },
            { en: "destination",        phonetic: "/ˌdestɪˈneɪʃn/",     cn: "n.目的地;终点" },
            { en: "other than",         phonetic: "/ˈʌðə(r) ðən/",      cn: "除……以外" },
            { en: "admire",             phonetic: "/ədˈmaɪə(r)/",        cn: "vt.钦佩;赞赏" },
            { en: "architecture",       phonetic: "/ˈɑ:kɪtektʃə(r)/",   cn: "n.建筑设计;建筑学" },
            { en: "architect",          phonetic: "/ˈɑ:kɪtekt/",         cn: "n.建筑设计师" },
            { en: "brochure",           phonetic: "/ˈbrəʊʃə(r)/",        cn: "n.资料(或广告)手册" },
            { en: "package",            phonetic: "/ˈpækɪdʒ/",            cn: "n.包裹;包装盒 vt.将…包装" },
            { en: "package tour",       phonetic: "/ˈpækɪdʒ tʊə(r)/",   cn: "包价旅游" },
            { en: "contact",            phonetic: "/ˈkɒntækt/",           cn: "vt.联络;联系 n.联系;接触" },
            { en: "civilisation",       phonetic: "/sɪvɪlaɪˈzeɪʃən/",   cn: "n.文明;文明世界" },
            { en: "make up",            phonetic: "/meɪk ʌp/",            cn: "构成;形成" },
            { en: "soldier",            phonetic: "/ˈsəʊldʒə(r)/",       cn: "n.士兵;军人" },
            { en: "transport",          phonetic: "/ˈtrænspɔ:t/",        cn: "n.交通运输系统 vt.运输" },
            { en: "hike",               phonetic: "/haɪk/",               cn: "vi.徒步旅行 vt.去……远足" },
            { en: "economy",            phonetic: "/ɪˈkɒnəmi/",           cn: "n.经济;节约" },
            { en: "economic",           phonetic: "/ˌi:kəˈnɒmɪk/",      cn: "adj.经济(上)的;经济学的" },
            { en: "credit",             phonetic: "/ˈkredɪt/",            cn: "n.借款;信用;称赞;学分" },
            { en: "credit card",        phonetic: "/ˈkredɪt kɑ:d/",      cn: "信用卡" },
            { en: "detail",             phonetic: "/ˈdi:teɪl/",           cn: "n.细节;详情;细微之处" },
            { en: "check in",           phonetic: "/tʃek ɪn/",            cn: "(在旅馆、机场等)登记" },
            { en: "check out",          phonetic: "/tʃek aʊt/",           cn: "结账离开(旅馆等)" },
            { en: "request",            phonetic: "/rɪˈkwest/",           cn: "n.&vi.(正式的)要求;请求" },
            { en: "view",               phonetic: "/vju:/",               cn: "n.视野;景色;看法" },
            { en: "sight",              phonetic: "/saɪt/",               cn: "n.景象;视野;视力" },
            { en: "statue",             phonetic: "/ˈstætʃu:/",           cn: "n.雕塑;雕像" },
            { en: "BCE",                phonetic: "/bi:si:ˈi:/",          cn: "abbr.公元前" },
            { en: "tomb",               phonetic: "/tu:m/",               cn: "n.坟墓" },
            { en: "unearth",            phonetic: "/ʌnˈɜ:θ/",            cn: "vt.挖掘;发掘" },
            { en: "comment",            phonetic: "/ˈkɒment/",            cn: "n.&vi.&vt.议论;评论" },
            { en: "the Eiffel Tower",   phonetic: "/ðə ˈaɪfəl ˈtaʊə(r)/", cn: "埃菲尔铁塔" },
            { en: "Neuschwanstein Castle", phonetic: "",                  cn: "新天鹅堡" },
            { en: "Iceland",            phonetic: "/ˈaɪslənd/",           cn: "冰岛(国家名)" },
            { en: "Disneyland",         phonetic: "/ˈdɪznilænd/",        cn: "迪士尼乐园" },
            { en: "Peru",               phonetic: "/pəˈrʊ:/",            cn: "秘鲁(国家名)" },
            { en: "the Andes Mountains", phonetic: "/ðə ˈændiːz ˈmaʊntɪns/", cn: "安第斯山脉" },
            { en: "the Amazon rainforest", phonetic: "/ðə ˈæməzən ˈreɪnfɒrɪst/", cn: "亚马孙雨林" },
            { en: "the Inca Empire",    phonetic: "/ðə ˈiŋkə ˈempaɪə(r)/", cn: "印加帝国" },
            { en: "Machu Picchu",       phonetic: "",                      cn: "马丘比丘" },
            { en: "Spain",              phonetic: "/speɪn/",               cn: "西班牙" },
            { en: "Spanish",            phonetic: "/ˈspænɪʃ/",            cn: "n.&adj.西班牙(语/人)的" },
            { en: "Cusco",              phonetic: "/ˈku:skəu/",           cn: "库斯科(秘鲁城市)" },
            { en: "Lake Titicaca",      phonetic: "/leɪk ˌtitiˈkaka/",   cn: "的的喀喀湖" },
            { en: "the Uros",           phonetic: "",                      cn: "乌鲁斯人" },
            { en: "the Terracotta Army", phonetic: "/ðə ˌterəˈkɒtə ˈɑ:mi/", cn: "兵马俑" }
        ],

        "Unit 4": [
            { en: "fitness",            phonetic: "/ˈfɪtnəs/",            cn: "n.健康;健壮;适合" },
            { en: "soccer",             phonetic: "/ˈsɒkə(r)/",          cn: "n.足球" },
            { en: "stadium",            phonetic: "/ˈsteɪdiəm/",          cn: "n.体育场;运动场" },
            { en: "boxing",             phonetic: "/ˈbɒksɪŋ/",            cn: "n.拳击(运动)" },
            { en: "badminton",          phonetic: "/ˈbædmɪntən/",        cn: "n.羽毛球运动" },
            { en: "marathon",           phonetic: "/ˈmærəθən/",           cn: "n.马拉松赛跑" },
            { en: "event",              phonetic: "/ɪˈvent/",             cn: "n.比赛项目;大事;公开活动" },
            { en: "come along",         phonetic: "/kʌm əˈlɒŋ/",        cn: "跟随;到达;进步;赶快" },
            { en: "ski",                phonetic: "/ski:/",               cn: "adj.滑雪的 vi.滑雪" },
            { en: "host",               phonetic: "/həʊst/",              cn: "vt.主办;主持 n.主持人" },
            { en: "track",              phonetic: "/træk/",               cn: "n.跑道;足迹 vt.&vi.追踪" },
            { en: "track and field",    phonetic: "/træk ənd fi:ld/",    cn: "田径" },
            { en: "gym",                phonetic: "/dʒɪm/",               cn: "n.健身房;体育馆" },
            { en: "gymnastics",         phonetic: "/dʒɪmˈnæstɪks/",      cn: "n.体操(训练)" },
            { en: "work out",           phonetic: "/wɜ:k aʊt/",          cn: "锻炼;计算出;解决" },
            { en: "sweat",              phonetic: "/swet/",               cn: "vt.&vi.使出汗;流汗 n.汗水" },
            { en: "make it",            phonetic: "/meɪk ɪt/",            cn: "获得成功;准时到达" },
            { en: "legend",             phonetic: "/ˈledʒənd/",           cn: "n.传奇故事(或人物);传说" },
            { en: "athlete",            phonetic: "/ˈæθli:t/",            cn: "n.运动员;运动健儿" },
            { en: "master",             phonetic: "/ˈmɑ:stə(r)/",        cn: "n.高手;主人 vt.精通;掌握" },
            { en: "set an example",     phonetic: "/set ən ɪgˈzɑ:mpl/",  cn: "树立榜样" },
            { en: "honour",             phonetic: "/ˈɒnə(r)/",            cn: "n.荣誉;尊敬;荣幸" },
            { en: "glory",              phonetic: "/ˈglɔ:ri/",            cn: "n.荣誉;光荣;赞美" },
            { en: "medal",              phonetic: "/ˈmedl/",              cn: "n.奖章;勋章" },
            { en: "championship",       phonetic: "/ˈtʃæmpiənʃɪp/",     cn: "n.锦标赛;冠军赛;冠军称号" },
            { en: "champion",           phonetic: "/ˈtʃæmpiən/",         cn: "n.冠军;优胜者" },
            { en: "determination",      phonetic: "/dɪˌtɜ:mɪˈneɪʃn/",   cn: "n.决心;决定" },
            { en: "apart",              phonetic: "/əˈpɑ:t/",             cn: "adv.分离;分开;成碎片" },
            { en: "fall apart",         phonetic: "/fɔ:l əˈpɑ:t/",      cn: "破裂;破碎;崩溃" },
            { en: "injure",             phonetic: "/ˈɪndʒə(r)/",         cn: "vt.使受伤;损害" },
            { en: "injured",            phonetic: "/ˈɪndʒəd/",            cn: "adj.受伤的;有伤的" },
            { en: "injury",             phonetic: "/ˈɪndʒəri/",           cn: "n.伤害;损伤" },
            { en: "captain",            phonetic: "/ˈkæptɪn/",            cn: "n.(运动队)队长;船长;机长" },
            { en: "lose heart",         phonetic: "/lu:z hɑ:t/",         cn: "丧失信心;泄气" },
            { en: "graceful",           phonetic: "/ˈgreɪsfl/",           cn: "adj.优美的;优雅的" },
            { en: "strength",           phonetic: "/streŋθ/",             cn: "n.力量;体力" },
            { en: "failure",            phonetic: "/ˈfeɪljə(r)/",        cn: "n.失败;失败的人(或事物)" },
            { en: "give up",            phonetic: "/gɪv ʌp/",             cn: "放弃;投降" },
            { en: "compete",            phonetic: "/kəmˈpi:t/",           cn: "vi.竞争;对抗" },
            { en: "make sense",         phonetic: "/meɪk sens/",         cn: "有道理;合乎情理;表述清楚" },
            { en: "pretend",            phonetic: "/prɪˈtend/",           cn: "vi.&vt.假装;装扮" },
            { en: "pretend to do sth.", phonetic: "/prɪˈtend tə du ˈsʌmθɪŋ/", cn: "假装做某事" },
            { en: "even if",            phonetic: "/ˈi:vn ɪf/",           cn: "即使;虽然" },
            { en: "million",            phonetic: "/ˈmɪljən/",            cn: "num.一百万" },
            { en: "cheat",              phonetic: "/tʃi:t/",              cn: "vi.作弊;舞弊 vt.欺骗;蒙骗" },
            { en: "audience",           phonetic: "/ˈɔ:diəns/",           cn: "n.观众;听众" },
            { en: "positive",           phonetic: "/ˈpɒzətɪv/",          cn: "adj.积极的;正面的;乐观的" },
            { en: "slim",               phonetic: "/slɪm/",               cn: "adj.苗条的;单薄的" },
            { en: "diet",               phonetic: "/ˈdaɪət/",             cn: "n.规定饮食 vi.节食" },
            { en: "make a difference",  phonetic: "/meɪk ə ˈdɪfrəns/",   cn: "有作用或影响" },
            { en: "rather",             phonetic: "/ˈrɑ:ðə(r)/",         cn: "adv.相当;有点儿" },
            { en: "rather than",        phonetic: "/ˈrɑ:ðə(r) ðən/",    cn: "而不是" },
            { en: "push-up",            phonetic: "/pʊʃ ʌp/",             cn: "n.俯卧撑" },
            { en: "cut ... out",        phonetic: "/kʌt aʊt/",           cn: "停止做(或使用、食用);剪下" },
            { en: "now and then",       phonetic: "/naʊ ənd ðen/",      cn: "有时;偶尔" },
            { en: "compare ... with ...", phonetic: "/kəmˈpeə(r) wɪð/", cn: "与……比较" },
            { en: "jog",                phonetic: "/dʒɒg/",               cn: "vi.慢跑 n.慢跑" },
            { en: "stress",             phonetic: "/stres/",              cn: "n.压力;紧张 vt.强调;重读" },
            { en: "error",              phonetic: "/ˈerə(r)/",            cn: "n.错误;差错" }
        ],

        "Unit 5": [
            { en: "disaster",           phonetic: "/dɪˈzɑ:stə(r)/",     cn: "n.灾难;灾害" },
            { en: "tornado",            phonetic: "/tɔ:ˈneɪdəʊ/",        cn: "n.龙卷风;旋风" },
            { en: "drought",            phonetic: "/draʊt/",              cn: "n.旱灾;久旱" },
            { en: "landslide",          phonetic: "/ˈlændslaɪd/",        cn: "n.(山地或悬崖的)崩塌;滑坡" },
            { en: "slide",              phonetic: "/slaɪd/",              cn: "vi.&vt.(使)滑行;滑动" },
            { en: "tsunami",            phonetic: "/tsu:ˈnɑ:mi/",        cn: "n.海啸" },
            { en: "flood",              phonetic: "/flʌd/",               cn: "n.洪水;大量 vi.淹没" },
            { en: "volcanic eruption",  phonetic: "/vɒlˈkænɪk ɪˈrʌpʃn/", cn: "火山喷发" },
            { en: "magnitude",          phonetic: "/ˈmægnɪtju:d/",       cn: "n.(地)震级;重大" },
            { en: "rescue",             phonetic: "/ˈreskju:/",           cn: "n.&vt.营救;救援" },
            { en: "damage",             phonetic: "/ˈdæmɪdʒ/",           cn: "vt.损害;破坏 n.损坏;损失" },
            { en: "destroy",            phonetic: "/dɪˈstrɔɪ/",          cn: "vt.摧毁;毁灭" },
            { en: "evacuate",           phonetic: "/ɪˈvækjueɪt/",       cn: "vt.疏散;撤出 vi.撤离" },
            { en: "helicopter",         phonetic: "/ˈhelɪkɒptə(r)/",    cn: "n.直升机" },
            { en: "death",              phonetic: "/deθ/",                cn: "n.死;死亡" },
            { en: "affect",             phonetic: "/əˈfekt/",             cn: "vt.影响;(疾病)侵袭" },
            { en: "shelter",            phonetic: "/ˈʃeltə(r)/",         cn: "n.避难处;居所 vt.保护" },
            { en: "crack",              phonetic: "/kræk/",               cn: "n.裂纹;裂缝 vi.&vt.使破裂" },
            { en: "gas",                phonetic: "/ɡæs/",                cn: "n.气体;燃气;汽油" },
            { en: "as if",              phonetic: "/əz ɪf/",              cn: "似乎;好像;仿佛" },
            { en: "ruin",               phonetic: "/ˈru:ɪn/",             cn: "n.&vt.破坏;毁坏" },
            { en: "in ruins",           phonetic: "/ɪn ˈru:ɪnz/",        cn: "严重受损;破败不堪" },
            { en: "percent",            phonetic: "/pəˈsent/",            cn: "n.百分之… adv.每一百中" },
            { en: "brick",              phonetic: "/brɪk/",               cn: "n.砖;砖块" },
            { en: "metal",              phonetic: "/ˈmetl/",              cn: "n.金属" },
            { en: "shock",              phonetic: "/ʃɒk/",                cn: "n.震惊;休克 vt.(使)震惊" },
            { en: "in shock",           phonetic: "/ɪn ʃɒk/",             cn: "震惊;吃惊" },
            { en: "electricity",        phonetic: "/ɪˌlekˈtrɪsəti/",    cn: "n.电;电能" },
            { en: "trap",               phonetic: "/træp/",               cn: "vt.使落入险境 n.险境;陷阱" },
            { en: "bury",               phonetic: "/ˈberi/",              cn: "vt.埋葬;安葬" },
            { en: "breathe",            phonetic: "/bri:ð/",              cn: "vi.&vt.呼吸" },
            { en: "revive",             phonetic: "/rɪˈvaɪv/",            cn: "vi.&vt.复活;(使)苏醒" },
            { en: "revival",            phonetic: "/rɪˈvaɪvl/",           cn: "n.振兴;复苏" },
            { en: "effort",             phonetic: "/ˈefət/",              cn: "n.努力;艰难的尝试;尽力" },
            { en: "unify",              phonetic: "/ˈju:nɪfaɪ/",          cn: "vi.&vt.统一;(使)成一体" },
            { en: "wisdom",             phonetic: "/ˈwɪzdəm/",            cn: "n.智慧;才智" },
            { en: "context",            phonetic: "/ˈkɒntekst/",          cn: "n.上下文;语境;背景" },
            { en: "suffer",             phonetic: "/ˈsʌfə(r)/",          cn: "vt.遭受;蒙受 vi.受苦" },
            { en: "volcano",            phonetic: "/vɒlˈkeɪnəʊ/",        cn: "n.火山" },
            { en: "erupt",              phonetic: "/ɪˈrʌpt/",             cn: "vi.&vt.火山爆发;岩浆喷出" },
            { en: "supply",             phonetic: "/səˈplaɪ/",            cn: "n.供应;补给 vt.供应;供给" },
            { en: "typhoon",            phonetic: "/taɪˈfu:n/",           cn: "n.台风" },
            { en: "in the open air",    phonetic: "/ɪn ðə ˈəʊpən eə(r)/", cn: "露天;在户外" },
            { en: "hurricane",          phonetic: "/ˈhʌrɪkən/",          cn: "n.(尤指西大西洋的)飓风" },
            { en: "survive",            phonetic: "/səˈvaɪv/",            cn: "vi.生存;存活 vt.幸存" },
            { en: "power",              phonetic: "/ˈpaʊə(r)/",          cn: "n.电力供应;能量;力量" },
            { en: "tap",                phonetic: "/tæp/",                cn: "vi.&vt.轻叩;轻敲 n.水龙头" },
            { en: "pipe",               phonetic: "/paɪp/",               cn: "n.管子;管道" },
            { en: "whistle",            phonetic: "/ˈwɪsl/",              cn: "vi.&vt.吹口哨 n.哨子(声)" },
            { en: "emergency",          phonetic: "/iˈmɜ:dʒənsi/",       cn: "n.突发事件;紧急情况" },
            { en: "calm",               phonetic: "/kɑ:m/",               cn: "adj.镇静的;沉着的 vt.使平静" },
            { en: "aid",                phonetic: "/eɪd/",                cn: "n.援助;帮助 vi.&vt.帮助" },
            { en: "kit",                phonetic: "/kɪt/",                cn: "n.成套工具;成套设备" },
            { en: "first aid kit",      phonetic: "/fɜ:st eɪd kɪt/",    cn: "急救箱" },
            { en: "on hand",            phonetic: "/ɒn hænd/",            cn: "现有(尤指帮助)" },
            { en: "crash",              phonetic: "/kræʃ/",               cn: "vt.&vi.碰撞;撞击 n.撞车" },
            { en: "sweep",              phonetic: "/swi:p/",              cn: "vt.&vi.打扫;清扫" },
            { en: "sweep away",         phonetic: "/swi:p əˈweɪ/",      cn: "消灭;彻底消除" },
            { en: "wave",               phonetic: "/weɪv/",               cn: "n.海浪;波浪 vi.&vt.挥手" },
            { en: "strike",             phonetic: "/straɪk/",             cn: "vi.&vt.侵袭;突击 n.罢工" },
            { en: "deliver",            phonetic: "/dɪˈlɪvə(r)/",       cn: "vi.&vt.传递;传达 vt.发表" },
            { en: "summary",            phonetic: "/ˈsʌməri/",            cn: "n.总结;概括;概要" },
            { en: "effect",             phonetic: "/ɪˈfekt/",             cn: "n.影响;结果;效果" },
            { en: "length",             phonetic: "/leŋθ/",               cn: "n.长;长度" },
            { en: "Ecuador",            phonetic: "/ˈekwədɔ:(r)/",       cn: "厄瓜多尔(国家名)" },
            { en: "Memphis",            phonetic: "/ˈmemfis/",            cn: "孟菲斯(美国城市)" },
            { en: "Alberta",            phonetic: "/ælˈbɜ:tə/",          cn: "艾伯塔省(加拿大省份)" },
            { en: "Colombo",            phonetic: "/kəˈlʌmbəu/",         cn: "科伦坡(斯里兰卡首都)" },
            { en: "Sri Lanka",          phonetic: "/sri: ˈlɑːŋkə/",     cn: "斯里兰卡(国家名)" },
            { en: "Indonesia",          phonetic: "/ˌɪndəʊˈni:zjə/",    cn: "印度尼西亚(国家名)" },
            { en: "Thailand",           phonetic: "/ˈtaɪlænd/",           cn: "泰国(国家名)" },
            { en: "Malaysia",           phonetic: "/məˈleɪʒə/",          cn: "马来西亚(国家名)" },
            { en: "Sumatra Island",     phonetic: "/sʊˈmɑːtrə ˈaɪlənd/", cn: "苏门答腊岛" },
            { en: "Chandra Theeravit",  phonetic: "",                     cn: "钱德拉·特拉维" }
        ],

        "Unit 6": [
            { en: "billion",            phonetic: "/ˈbɪljən/",            cn: "n.十亿" },
            { en: "native",             phonetic: "/ˈneɪtɪv/",            cn: "adj.本地的;土著的 n.本地人" },
            { en: "attitude",           phonetic: "/ˈætɪtju:d/",         cn: "n.态度;看法" },
            { en: "reference",          phonetic: "/ˈrefrəns/",           cn: "n.指称关系;参考" },
            { en: "refer",              phonetic: "/rɪˈfɜ:(r)/",         cn: "vi.提到;参考;查阅 vt.查询" },
            { en: "refer to",           phonetic: "/rɪˈfɜ:(r) tə/",      cn: "指的是;描述;提到;查阅" },
            { en: "system",             phonetic: "/ˈsɪstəm/",            cn: "n.体系;制度;系统" },
            { en: "despite",            phonetic: "/dɪˈspaɪt/",           cn: "prep.即使;尽管" },
            { en: "ups and downs",      phonetic: "/ʌps ənd daʊnz/",    cn: "浮沉;兴衰;荣辱" },
            { en: "factor",             phonetic: "/ˈfæktə(r)/",         cn: "n.因素;要素" },
            { en: "based",              phonetic: "/beɪst/",              cn: "adj.以(某事)为基础的" },
            { en: "base",               phonetic: "/beɪs/",               cn: "vt.以…为据点 n.底部;根据" },
            { en: "date back to ...",   phonetic: "/deɪt bæk tə/",      cn: "追溯到" },
            { en: "bone",               phonetic: "/bəʊn/",               cn: "n.骨头;骨(质)" },
            { en: "shell",              phonetic: "/ʃel/",                cn: "n.壳;壳状物" },
            { en: "symbol",             phonetic: "/ˈsɪmbl/",             cn: "n.符号;象征" },
            { en: "carve",              phonetic: "/kɑ:v/",               cn: "vt.&vi.雕刻" },
            { en: "dynasty",            phonetic: "/ˈdɪnəsti/",           cn: "n.王朝;朝代" },
            { en: "variety",            phonetic: "/vəˈraɪəti/",          cn: "n.(植物、语言等)变体;异体" },
            { en: "major",              phonetic: "/ˈmeɪdʒə(r)/",       cn: "adj.主要的;重要的 n.主修课" },
            { en: "no matter ...",      phonetic: "/nəʊ ˈmætə(r)/",     cn: "不论……;不管……" },
            { en: "dialect",            phonetic: "/ˈdaɪəlekt/",          cn: "n.地方话;方言" },
            { en: "means",              phonetic: "/mi:nz/",              cn: "n.方式;方法;途径" },
            { en: "classic",            phonetic: "/ˈklæsɪk/",            cn: "adj.传统的;最优秀的 n.名著" },
            { en: "regard",             phonetic: "/rɪˈgɑ:d/",           cn: "n.尊重;关注 vt.把……视为" },
            { en: "character",          phonetic: "/ˈkærəktə(r)/",      cn: "n.文字;符号;角色;品质" },
            { en: "calligraphy",        phonetic: "/kəˈlɪgrəfi/",        cn: "n.书法;书法艺术" },
            { en: "global",             phonetic: "/ˈgləʊbl/",            cn: "adj.全球的;全世界的" },
            { en: "affair",             phonetic: "/əˈfeə(r)/",          cn: "n.公共事务;事件;关系" },
            { en: "appreciate",         phonetic: "/əˈpri:ʃieɪt/",       cn: "vt.欣赏;重视;感激 vi.增值" },
            { en: "specific",           phonetic: "/spəˈsɪfɪk/",         cn: "adj.特定的;明确的;具体的" },
            { en: "CE",                 phonetic: "/si:ˈi:/",             cn: "abbr.(源自拉丁语)公元" },
            { en: "struggle",           phonetic: "/ˈstrʌgl/",            cn: "n.&vi.斗争;奋斗;搏斗" },
            { en: "tongue",             phonetic: "/tʌŋ/",                cn: "n.舌头;语言" },
            { en: "point of view",      phonetic: "/pɔɪnt əv vju:/",    cn: "观点;看法" },
            { en: "semester",           phonetic: "/sɪˈmestə(r)/",      cn: "n.学期" },
            { en: "petrol",             phonetic: "/ˈpetrəl/",            cn: "n.汽油" },
            { en: "subway",             phonetic: "/ˈsʌbweɪ/",            cn: "n.地铁" },
            { en: "apartment",          phonetic: "/əˈpɑ:tmənt/",        cn: "n.公寓套房" },
            { en: "pants",              phonetic: "/pænts/",              cn: "n.[pl.]内裤;短裤;裤子" },
            { en: "beg",                phonetic: "/beg/",                cn: "vt.恳求;祈求;哀求" },
            { en: "equal",              phonetic: "/ˈi:kwəl/",            cn: "n.同等人;相等物 adj.相同的" },
            { en: "gap",                phonetic: "/gæp/",                cn: "n.间隔;开口;差距" },
            { en: "demand",             phonetic: "/dɪˈmɑ:nd/",          cn: "n.要求;需求 vt.强烈要求" },
            { en: "vocabulary",         phonetic: "/vəˈkæbjələri/",      cn: "n.词汇" },
            { en: "description",        phonetic: "/dɪˈskrɪpʃn/",       cn: "n.描写(文字);形容" },
            { en: "relate",             phonetic: "/rɪˈleɪt/",            cn: "vt.联系;讲述" },
            { en: "relate to",          phonetic: "/rɪˈleɪt tə/",        cn: "与……相关;涉及;谈到" },
            { en: "Korean",             phonetic: "/kəˈrɪən/",           cn: "n.&adj.(朝鲜/韩国)(语/人)" },
            { en: "Danish",             phonetic: "/ˈdeɪnɪʃ/",           cn: "n.丹麦语;丹麦人 adj.丹麦的" },
            { en: "Denmark",            phonetic: "/ˈdenmɑ:k/",           cn: "丹麦(国家名)" },
            { en: "Arabic",             phonetic: "/ˈærəbɪk/",           cn: "n.&adj.阿拉伯语/文学(的)" },
            { en: "FIFA",               phonetic: "/ˈfi:fə/",             cn: "abbr.(源自法语)国际足联" }
        ]

    }

};