var wordBank = wordBank || {};

wordBank["外研版高中词库"] = {

    // ==================== B2 级 ====================

    "B2级 Unit 1": [
        // 只认读（英译中）
        { en: "discussion", cn: "讨论", phonetic: "/dɪˈskʌʃn/", spell: false },
        { en: "nation", cn: "国家，民族", phonetic: "/ˈneɪʃn/", spell: false },
        { en: "born", cn: "出生", phonetic: "/bɔːn/", spell: false },
        { en: "flash", cn: "闪光；闪现", phonetic: "/flæʃ/", spell: false },
        { en: "outdoor", cn: "户外的", phonetic: "/ˈaʊtdɔː(r)/", spell: false },
        { en: "northern", cn: "北方的", phonetic: "/ˈnɔːðən/", spell: false },
        { en: "website", cn: "网站", phonetic: "/ˈwebsaɪt/", spell: false },
        { en: "mad", cn: "生气的；疯狂的", phonetic: "/mæd/", spell: false },
        { en: "trade", cn: "贸易", phonetic: "/treɪd/", spell: false },
        { en: "towards", cn: "朝向", phonetic: "/təˈwɔːdz/", spell: false },
        { en: "low", cn: "低的", phonetic: "/ləʊ/", spell: false },
        { en: "German", cn: "德国人，德语", phonetic: "/ˈdʒɜːmən/", spell: false },
        { en: "childhood", cn: "童年", phonetic: "/ˈtʃaɪldhʊd/", spell: false },
        { en: "simply", cn: "仅仅；简单地", phonetic: "/ˈsɪmpli/", spell: false },
        { en: "degree", cn: "度；程度；学位", phonetic: "/dɪˈɡriː/", spell: false },
        { en: "musician", cn: "音乐家", phonetic: "/mjuˈzɪʃn/", spell: false },
        { en: "frog", cn: "青蛙", phonetic: "/frɒɡ/", spell: false },
        { en: "spread", cn: "传播", phonetic: "/spred/", spell: false },
        { en: "final", cn: "最终的；决赛", phonetic: "/ˈfaɪnl/", spell: false },
        { en: "scene", cn: "场景", phonetic: "/siːn/", spell: false },
        { en: "earthquake", cn: "地震", phonetic: "/ˈɜːθkweɪk/", spell: false },
        { en: "airplane", cn: "飞机", phonetic: "/ˈeəpleɪn/", spell: false },
        { en: "remind", cn: "提醒", phonetic: "/rɪˈmaɪnd/", spell: false },
        { en: "effort", cn: "努力", phonetic: "/ˈefət/", spell: false },
        { en: "coach", cn: "教练", phonetic: "/kəʊtʃ/", spell: false },
        { en: "primary", cn: "首要的；初级的；小学的", phonetic: "/ˈpraɪməri/", spell: false },
        { en: "repeat", cn: "重复", phonetic: "/rɪˈpiːt/", spell: false },
        { en: "society", cn: "社会", phonetic: "/səˈsaɪəti/", spell: false }
    ],

    "B2级 Unit 2": [
        { en: "enemy", cn: "敌人", phonetic: "/ˈenəmi/", spell: false },
        { en: "lock", cn: "锁", phonetic: "/lɒk/", spell: false },
        { en: "corn", cn: "玉米", phonetic: "/kɔːn/", spell: false },
        { en: "basic", cn: "基础的", phonetic: "/ˈbeɪsɪk/", spell: false },
        { en: "ugly", cn: "丑陋的", phonetic: "/ˈʌɡli/", spell: false },
        { en: "tower", cn: "塔", phonetic: "/ˈtaʊə(r)/", spell: false },
        { en: "alive", cn: "活着的", phonetic: "/əˈlaɪv/", spell: false },
        { en: "available", cn: "可获得的；有空的", phonetic: "/əˈveɪləbl/", spell: false },
        { en: "protection", cn: "保护，防护", phonetic: "/prəˈtekʃn/", spell: false },
        { en: "president", cn: "总统", phonetic: "/ˈprezɪdənt/", spell: false },
        { en: "refer to", cn: "参考；涉及；指的是", phonetic: "/rɪˈfɜː(r) tuː/", spell: false },
        { en: "immediately", cn: "立刻", phonetic: "/ɪˈmiːdiətli/", spell: false },
        { en: "itself", cn: "它自己", phonetic: "/ɪtˈself/", spell: false },
        { en: "nor", cn: "也不", phonetic: "/nɔː(r)/", spell: false },
        { en: "electronic", cn: "电子的", phonetic: "/ɪˌlekˈtrɒnɪk/", spell: false },
        { en: "industry", cn: "行业；工业", phonetic: "/ˈɪndəstri/", spell: false },
        { en: "till", cn: "直到……为止", phonetic: "/tɪl/", spell: false },
        { en: "confident", cn: "自信的", phonetic: "/ˈkɒnfɪdənt/", spell: false },
        { en: "agreement", cn: "同意，协议", phonetic: "/əˈɡriːmənt/", spell: false },
        { en: "nearby", cn: "在附近", phonetic: "/ˌnɪəˈbaɪ/", spell: false },
        { en: "gas", cn: "煤气，气体", phonetic: "/ɡæs/", spell: false },
        { en: "doubt", cn: "怀疑；疑惑", phonetic: "/daʊt/", spell: false },
        { en: "afford", cn: "负担得起", phonetic: "/əˈfɔːd/", spell: false },
        { en: "physical", cn: "物理的；身体的", phonetic: "/ˈfɪzɪkl/", spell: false },
        { en: "survey", cn: "调查；测量", phonetic: "/ˈsɜːveɪ/", spell: false },
        { en: "organization", cn: "组织", phonetic: "/ˌɔːɡənaɪˈzeɪʃn/", spell: false },
        { en: "boss", cn: "老板", phonetic: "/bɒs/", spell: false },
        { en: "law", cn: "法律", phonetic: "/lɔː/", spell: false }
    ],

    "B2级 Unit 3": [
        { en: "underground", cn: "地下的；地铁", phonetic: "/ˈʌndəɡraʊnd/", spell: false },
        { en: "method", cn: "方法", phonetic: "/ˈmeθəd/", spell: false },
        { en: "attend", cn: "参加，出席", phonetic: "/əˈtend/", spell: false },
        { en: "fashion", cn: "时尚", phonetic: "/ˈfæʃn/", spell: false },
        { en: "crowd", cn: "人群；拥挤", phonetic: "/kraʊd/", spell: false },
        { en: "file", cn: "文件；档案", phonetic: "/faɪl/", spell: false },
        { en: "anybody", cn: "任何人", phonetic: "/ˈenibɒdi/", spell: false },
        { en: "wine", cn: "酒", phonetic: "/waɪn/", spell: false },
        { en: "nowadays", cn: "当今", phonetic: "/ˈnaʊədeɪz/", spell: false },
        { en: "apartment", cn: "公寓", phonetic: "/əˈpɑːtmənt/", spell: false },
        { en: "metal", cn: "金属", phonetic: "/ˈmetl/", spell: false },
        { en: "manage", cn: "管理", phonetic: "/ˈmænɪdʒ/", spell: false },
        { en: "cancel", cn: "取消", phonetic: "/ˈkænsl/", spell: false },
        { en: "importance", cn: "重要性", phonetic: "/ɪmˈpɔːtns/", spell: false },
        { en: "period", cn: "一段时间；时期", phonetic: "/ˈpɪəriəd/", spell: false },
        { en: "stomach", cn: "胃", phonetic: "/ˈstʌmək/", spell: false },
        { en: "director", cn: "导演；主管", phonetic: "/dɪˈrektə(r)/", spell: false },
        { en: "valuable", cn: "有价值的", phonetic: "/ˈvæljuəbl/", spell: false },
        { en: "church", cn: "教堂", phonetic: "/tʃɜːtʃ/", spell: false },
        { en: "southern", cn: "南方的", phonetic: "/ˈsʌðən/", spell: false },
        { en: "percent", cn: "百分之", phonetic: "/pəˈsent/", spell: false },
        { en: "desert", cn: "沙漠", phonetic: "/ˈdezət/", spell: false },
        { en: "amount", cn: "数量", phonetic: "/əˈmaʊnt/", spell: false },
        { en: "board", cn: "上（船/飞机/火车等）；木板", phonetic: "/bɔːd/", spell: false },
        { en: "service", cn: "服务", phonetic: "/ˈsɜːvɪs/", spell: false },
        { en: "couple", cn: "一对；夫妇；几个", phonetic: "/ˈkʌpl/", spell: false },
        { en: "badly", cn: "严重地；非常", phonetic: "/ˈbædli/", spell: false },
        { en: "trust", cn: "信任", phonetic: "/trʌst/", spell: false }
    ],

    "B2级 Unit 4": [
        { en: "forgetful", cn: "健忘的", phonetic: "/fəˈɡetfl/", spell: false },
        { en: "citizen", cn: "公民", phonetic: "/ˈsɪtɪzn/", spell: false },
        { en: "glue", cn: "胶水；粘贴", phonetic: "/ɡluː/", spell: false },
        { en: "risk", cn: "风险", phonetic: "/rɪsk/", spell: false },
        { en: "rubbish", cn: "垃圾", phonetic: "/ˈrʌbɪʃ/", spell: false },
        { en: "allow", cn: "允许", phonetic: "/əˈlaʊ/", spell: false },
        { en: "VR", cn: "虚拟现实", phonetic: "/ˌviː ˈɑː(r)/", spell: false },
        { en: "caring", cn: "体贴的", phonetic: "/ˈkeərɪŋ/", spell: false },
        { en: "pride", cn: "骄傲，自豪", phonetic: "/praɪd/", spell: false },
        { en: "private", cn: "私人的", phonetic: "/ˈpraɪvət/", spell: false },
        { en: "actress", cn: "女演员", phonetic: "/ˈæktrəs/", spell: false },
        { en: "warn", cn: "警告", phonetic: "/wɔːn/", spell: false },
        { en: "speaker", cn: "发言者", phonetic: "/ˈspiːkə(r)/", spell: false },
        { en: "best-selling", cn: "畅销", phonetic: "/ˌbest ˈselɪŋ/", spell: false },
        { en: "kangaroo", cn: "袋鼠", phonetic: "/ˌkæŋɡəˈruː/", spell: false },
        { en: "exhibition", cn: "展览", phonetic: "/ˌeksɪˈbɪʃn/", spell: false },
        { en: "elder", cn: "年长的", phonetic: "/ˈeldə(r)/", spell: false },
        { en: "discovery", cn: "发现", phonetic: "/dɪˈskʌvəri/", spell: false },
        { en: "sometime", cn: "某一时刻", phonetic: "/ˈsʌmtaɪm/", spell: false },
        { en: "college", cn: "大学，学院", phonetic: "/ˈkɒlɪdʒ/", spell: false },
        { en: "PRC", cn: "中华人民共和国", phonetic: "/ˌpiː ɑːr ˈsiː/", spell: false },
        { en: "site", cn: "地点；场所；网站", phonetic: "/saɪt/", spell: false },
        { en: "contribution", cn: "贡献", phonetic: "/ˌkɒntrɪˈbjuːʃn/", spell: false },
        { en: "fee", cn: "费", phonetic: "/fiː/", spell: false },
        { en: "experiment", cn: "实验", phonetic: "/ɪkˈsperɪmənt/", spell: false },
        { en: "saw", cn: "锯；锯子（see的过去式）", phonetic: "/sɔː/", spell: false },
        { en: "include", cn: "包括", phonetic: "/ɪnˈkluːd/", spell: false },
        { en: "re", cn: "关于，事由", phonetic: "/reɪ/", spell: false }
    ],

    "B2级 Unit 5": [
        { en: "sweetness", cn: "甜蜜；可爱", phonetic: "/ˈswiːtnəs/", spell: false },
        { en: "congratulate", cn: "祝贺", phonetic: "/kənˈɡrætʃuleɪt/", spell: false },
        { en: "measure", cn: "措施；测量", phonetic: "/ˈmeʒə(r)/", spell: false },
        { en: "mess", cn: "杂乱；混乱", phonetic: "/mes/", spell: false },
        { en: "pocket", cn: "口袋；把…放进口袋", phonetic: "/ˈpɒkɪt/", spell: false },
        { en: "develop", cn: "发展，开发", phonetic: "/dɪˈveləp/", spell: false },
        { en: "AI", cn: "人工智能", phonetic: "/ˌeɪ ˈaɪ/", spell: false },
        { en: "riddle", cn: "谜语", phonetic: "/ˈrɪdl/", spell: false },
        { en: "anxious", cn: "忧虑的", phonetic: "/ˈæŋkʃəs/", spell: false },
        { en: "steel", cn: "钢", phonetic: "/stiːl/", spell: false },
        { en: "net", cn: "网", phonetic: "/net/", spell: false },
        { en: "listener", cn: "倾听者", phonetic: "/ˈlɪsənə(r)/", spell: false },
        { en: "accident", cn: "事故", phonetic: "/ˈæksɪdənt/", spell: false },
        { en: "ice cream", cn: "冰激凌", phonetic: "/ˌaɪs ˈkriːm/", spell: false },
        { en: "tiring", cn: "使人疲惫的", phonetic: "/ˈtaɪərɪŋ/", spell: false },
        { en: "apologize", cn: "道歉", phonetic: "/əˈpɒlədʒaɪz/", spell: false },
        { en: "chain", cn: "链子", phonetic: "/tʃeɪn/", spell: false },
        { en: "background", cn: "背景", phonetic: "/ˈbækɡraʊnd/", spell: false },
        { en: "photograph", cn: "照片；拍照", phonetic: "/ˈfəʊtəɡrɑːf/", spell: false },
        { en: "African", cn: "非洲的；非洲人", phonetic: "/ˈæfrɪkən/", spell: false },
        { en: "wisely", cn: "明智地；充满智慧地", phonetic: "/ˈwaɪzli/", spell: false },
        { en: "stormy", cn: "暴风雨的", phonetic: "/ˈstɔːmi/", spell: false },
        { en: "major", cn: "主要的", phonetic: "/ˈmeɪdʒə(r)/", spell: false },
        { en: "daytime", cn: "白天", phonetic: "/ˈdeɪtaɪm/", spell: false },
        { en: "effect", cn: "影响；效果", phonetic: "/ɪˈfekt/", spell: false },
        { en: "railway", cn: "铁路", phonetic: "/ˈreɪlweɪ/", spell: false },
        { en: "Olympic", cn: "奥林匹克的", phonetic: "/əˈlɪmpɪk/", spell: false },
        { en: "worry about", cn: "担心", phonetic: "/ˈwʌri əˈbaʊt/", spell: false }
    ],

    "B2级 Unit 6": [
        { en: "volunteer", cn: "志愿者", phonetic: "/ˌvɒlənˈtɪə(r)/", spell: false },
        { en: "overcome", cn: "克服", phonetic: "/ˌəʊvəˈkʌm/", spell: false },
        { en: "pianist", cn: "钢琴师", phonetic: "/ˈpiːənɪst/", spell: false },
        { en: "force", cn: "强迫", phonetic: "/fɔːs/", spell: false },
        { en: "cough", cn: "咳嗽", phonetic: "/kɒf/", spell: false },
        { en: "safety", cn: "安全；安全性", phonetic: "/ˈseɪfti/", spell: false },
        { en: "fortieth", cn: "第四十", phonetic: "/ˈfɔːtiəθ/", spell: false },
        { en: "honey", cn: "蜂蜜", phonetic: "/ˈhʌni/", spell: false },
        { en: "disagree", cn: "不同意", phonetic: "/ˌdɪsəˈɡriː/", spell: false },
        { en: "custom", cn: "习惯；风俗", phonetic: "/ˈkʌstəm/", spell: false },
        { en: "standard", cn: "标准", phonetic: "/ˈstændəd/", spell: false },
        { en: "scarf", cn: "围巾", phonetic: "/skɑːf/", spell: false },
        { en: "natural", cn: "天然的，自然的", phonetic: "/ˈnætʃrəl/", spell: false },
        { en: "kung fu", cn: "功夫", phonetic: "/ˌkʌŋ ˈfuː/", spell: false },
        { en: "goods", cn: "商品", phonetic: "/ɡʊdz/", spell: false },
        { en: "cycle", cn: "骑自行车；循环", phonetic: "/ˈsaɪkl/", spell: false },
        { en: "junior", cn: "初级的", phonetic: "/ˈdʒuːniə(r)/", spell: false },
        { en: "behave", cn: "表现；守规矩", phonetic: "/bɪˈheɪv/", spell: false },
        { en: "except", cn: "除……之外", phonetic: "/ɪkˈsept/", spell: false },
        { en: "perhaps", cn: "也许，可能", phonetic: "/pəˈhæps/", spell: false },
        { en: "depend", cn: "取决于", phonetic: "/dɪˈpend/", spell: false },
        { en: "editor", cn: "编辑", phonetic: "/ˈedɪtə(r)/", spell: false },
        { en: "preparation", cn: "准备", phonetic: "/ˌprepəˈreɪʃn/", spell: false },
        { en: "coast", cn: "海岸", phonetic: "/kəʊst/", spell: false },
        { en: "take away", cn: "拿走", phonetic: "/teɪk əˈweɪ/", spell: false },
        { en: "thick", cn: "厚的", phonetic: "/θɪk/", spell: false },
        { en: "communicate", cn: "交流", phonetic: "/kəˈmjuːnɪkeɪt/", spell: false },
        { en: "pay", cn: "付费；工资；报答", phonetic: "/peɪ/", spell: false }
    ],

    "B2级 Unit 7": [
        { en: "eventually", cn: "最终，最后", phonetic: "/ɪˈventʃuəli/", spell: false },
        { en: "lecture", cn: "演讲", phonetic: "/ˈlektʃə(r)/", spell: false },
        { en: "Germany", cn: "德国", phonetic: "/ˈdʒɜːməni/", spell: false },
        { en: "treatment", cn: "治疗", phonetic: "/ˈtriːtmənt/", spell: false },
        { en: "blank", cn: "空格；空白的", phonetic: "/blæŋk/", spell: false },
        { en: "interview", cn: "面试；采访", phonetic: "/ˈɪntəvjuː/", spell: false },
        { en: "headache", cn: "头痛", phonetic: "/ˈhedeɪk/", spell: false },
        { en: "technique", cn: "技巧，技术", phonetic: "/tekˈniːk/", spell: false },
        { en: "distance", cn: "距离", phonetic: "/ˈdɪstəns/", spell: false },
        { en: "madam", cn: "夫人", phonetic: "/ˈmædəm/", spell: false },
        { en: "eastern", cn: "东方的", phonetic: "/ˈiːstən/", spell: false },
        { en: "ache", cn: "疼痛", phonetic: "/eɪk/", spell: false },
        { en: "Africa", cn: "非洲", phonetic: "/ˈæfrɪkə/", spell: false },
        { en: "a lot of", cn: "许多", phonetic: "/ə ˈlɒt ɒv/", spell: false },
        { en: "responsible", cn: "有责任的", phonetic: "/rɪˈspɒnsəbl/", spell: false },
        { en: "take up", cn: "开始从事；占据（时间/空间）；拿起", phonetic: "/teɪk ˈʌp/", spell: false },
        { en: "freeze", cn: "结冰", phonetic: "/friːz/", spell: false },
        { en: "dig", cn: "挖；掘", phonetic: "/dɪɡ/", spell: false },
        { en: "drum", cn: "鼓", phonetic: "/drʌm/", spell: false },
        { en: "trouble", cn: "麻烦", phonetic: "/ˈtrʌbl/", spell: false },
        { en: "listen to", cn: "听", phonetic: "/ˈlɪsn tuː/", spell: false },
        { en: "lawyer", cn: "律师", phonetic: "/ˈlɔːjə(r)/", spell: false },
        { en: "secretary", cn: "秘书", phonetic: "/ˈsekrətri/", spell: false },
        { en: "steal", cn: "偷", phonetic: "/stiːl/", spell: false },
        { en: "shoot", cn: "射击", phonetic: "/ʃuːt/", spell: false },
        { en: "treasure", cn: "财富，宝藏", phonetic: "/ˈtreʒə(r)/", spell: false },
        { en: "cover", cn: "遮盖", phonetic: "/ˈkʌvə(r)/", spell: false },
        { en: "felt", cn: "感觉（feel的过去式）；毡", phonetic: "/felt/", spell: false }
    ],

    "B2级 Unit 8": [
        { en: "recent", cn: "最近", phonetic: "/ˈriːsnt/", spell: false },
        { en: "regular", cn: "规则的；正规的", phonetic: "/ˈreɡjələ(r)/", spell: false },
        { en: "X-ray", cn: "X射线", phonetic: "/ˈeks reɪ/", spell: false },
        { en: "smooth", cn: "光滑的", phonetic: "/smuːð/", spell: false },
        { en: "downstairs", cn: "在楼下；往楼下", phonetic: "/ˌdaʊnˈsteəz/", spell: false },
        { en: "pleasure", cn: "快乐", phonetic: "/ˈpleʒə(r)/", spell: false },
        { en: "take off", cn: "脱掉；起飞", phonetic: "/teɪk ˈɒf/", spell: false },
        { en: "agriculture", cn: "农业", phonetic: "/ˈæɡrɪkʌltʃə(r)/", spell: false },
        { en: "tip", cn: "提示；小费；给……小费", phonetic: "/tɪp/", spell: false },
        { en: "pardon", cn: "原谅", phonetic: "/ˈpɑːdn/", spell: false },
        { en: "policy", cn: "政策", phonetic: "/ˈpɒləsi/", spell: false },
        { en: "sour", cn: "酸的", phonetic: "/ˈsaʊə(r)/", spell: false },
        { en: "state", cn: "国家；状态", phonetic: "/steɪt/", spell: false },
        { en: "look at", cn: "看着", phonetic: "/lʊk æt/", spell: false },
        { en: "inspire", cn: "鼓舞", phonetic: "/ɪnˈspaɪə(r)/", spell: false },
        { en: "athlete", cn: "运动员", phonetic: "/ˈæθliːt/", spell: false },
        { en: "belong to", cn: "属于", phonetic: "/bɪˈlɒŋ tuː/", spell: false },
        { en: "sight", cn: "视力；景象；看见", phonetic: "/saɪt/", spell: false },
        { en: "seaside", cn: "海边", phonetic: "/ˈsiːsaɪd/", spell: false },
        { en: "death", cn: "死", phonetic: "/deθ/", spell: false },
        { en: "look for", cn: "寻找", phonetic: "/lʊk fɔː(r)/", spell: false },
        { en: "hunter", cn: "猎人", phonetic: "/ˈhʌntə(r)/", spell: false },
        { en: "bully", cn: "威胁；欺负", phonetic: "/ˈbʊli/", spell: false },
        { en: "condition", cn: "条件", phonetic: "/kənˈdɪʃn/", spell: false },
        { en: "Pacific", cn: "太平洋", phonetic: "/pəˈsɪfɪk/", spell: false },
        { en: "healthily", cn: "健康地", phonetic: "/ˈhelθɪli/", spell: false },
        { en: "fountain", cn: "喷泉", phonetic: "/ˈfaʊntən/", spell: false },
        { en: "hurry up", cn: "快点", phonetic: "/ˈhʌri ʌp/", spell: false }
    ],

    "B2级 Unit 9": [
        { en: "harm", cn: "伤害", phonetic: "/hɑːm/", spell: false },
        { en: "gentle", cn: "温和的", phonetic: "/ˈdʒentl/", spell: false },
        { en: "request", cn: "请求", phonetic: "/rɪˈkwest/", spell: false },
        { en: "proper", cn: "适当的", phonetic: "/ˈprɒpə(r)/", spell: false },
        { en: "think of", cn: "认为", phonetic: "/θɪŋk ɒv/", spell: false },
        { en: "gate", cn: "大门", phonetic: "/ɡeɪt/", spell: false },
        { en: "slow down", cn: "减速", phonetic: "/ˌsləʊ ˈdaʊn/", spell: false },
        { en: "eager", cn: "热切的", phonetic: "/ˈiːɡə(r)/", spell: false },
        { en: "Russia", cn: "俄罗斯", phonetic: "/ˈrʌʃə/", spell: false },
        { en: "engineering", cn: "工程学", phonetic: "/ˌendʒɪˈnɪərɪŋ/", spell: false },
        { en: "block", cn: "块；街区", phonetic: "/blɒk/", spell: false },
        { en: "government", cn: "政府", phonetic: "/ˈɡʌvənmənt/", spell: false },
        { en: "UN", cn: "联合国", phonetic: "/ˌjuː ˈen/", spell: false },
        { en: "point", cn: "观点；指向", phonetic: "/pɔɪnt/", spell: false },
        { en: "manner", cn: "举止；礼貌", phonetic: "/ˈmænə(r)/", spell: false },
        { en: "fiction", cn: "小说", phonetic: "/ˈfɪkʃn/", spell: false },
        { en: "on time", cn: "按时，准时", phonetic: "/ɒn taɪm/", spell: false },
        { en: "sunglasses", cn: "太阳镜", phonetic: "/ˈsʌnɡlɑːsɪz/", spell: false },
        { en: "western", cn: "西方的", phonetic: "/ˈwestən/", spell: false },
        { en: "personal", cn: "个人的", phonetic: "/ˈpɜːsənl/", spell: false },
        { en: "America", cn: "美国", phonetic: "/əˈmerɪkə/", spell: false },
        { en: "classic", cn: "经典的；最优秀的", phonetic: "/ˈklæsɪk/", spell: false },
        { en: "narrow", cn: "狭窄的", phonetic: "/ˈnærəʊ/", spell: false },
        { en: "backpack", cn: "背包", phonetic: "/ˈbækpæk/", spell: false },
        { en: "press", cn: "按；压", phonetic: "/pres/", spell: false },
        { en: "according", cn: "根据；依照（与to连用）", phonetic: "/əˈkɔːdɪŋ/", spell: false },
        { en: "peace", cn: "和平", phonetic: "/piːs/", spell: false },
        { en: "writer", cn: "作者，作家", phonetic: "/ˈraɪtə(r)/", spell: false }
    ],

    "B2级 Unit 10": [
        { en: "murder", cn: "谋杀", phonetic: "/ˈmɜːdə(r)/", spell: false },
        { en: "material", cn: "材料", phonetic: "/məˈtɪəriəl/", spell: false },
        { en: "unlucky", cn: "不幸运", phonetic: "/ʌnˈlʌki/", spell: false },
        { en: "convenient", cn: "便利", phonetic: "/kənˈviːniənt/", spell: false },
        { en: "education", cn: "教育", phonetic: "/ˌedʒuˈkeɪʃn/", spell: false },
        { en: "unless", cn: "除非", phonetic: "/ənˈles/", spell: false },
        { en: "report", cn: "报告", phonetic: "/rɪˈpɔːt/", spell: false },
        { en: "original", cn: "原始的，最初的", phonetic: "/əˈrɪdʒənl/", spell: false },
        { en: "excite", cn: "使兴奋", phonetic: "/ɪkˈsaɪt/", spell: false },
        { en: "fair", cn: "公平的；集市；晴朗的", phonetic: "/feə(r)/", spell: false },
        { en: "wealth", cn: "财产，财富", phonetic: "/welθ/", spell: false },
        { en: "fishing", cn: "钓鱼", phonetic: "/ˈfɪʃɪŋ/", spell: false },
        { en: "provide", cn: "提供", phonetic: "/prəˈvaɪd/", spell: false },
        { en: "meeting", cn: "会议", phonetic: "/ˈmiːtɪŋ/", spell: false },
        { en: "envelope", cn: "信封", phonetic: "/ˈenvələʊp/", spell: false },
        { en: "edge", cn: "边缘", phonetic: "/edʒ/", spell: false },
        { en: "dialogue", cn: "对话", phonetic: "/ˈdaɪəlɒɡ/", spell: false },
        { en: "case", cn: "情况；事例；箱", phonetic: "/keɪs/", spell: false },
        { en: "system", cn: "系统", phonetic: "/ˈsɪstəm/", spell: false },
        { en: "anywhere", cn: "任何地方", phonetic: "/ˈeniweə(r)/", spell: false },
        { en: "company", cn: "公司", phonetic: "/ˈkʌmpəni/", spell: false },
        { en: "vote", cn: "投票", phonetic: "/vəʊt/", spell: false },
        { en: "software", cn: "软件", phonetic: "/ˈsɒftweə(r)/", spell: false },
        { en: "boil", cn: "煮沸", phonetic: "/bɔɪl/", spell: false },
        { en: "pop", cn: "流行；流行音乐；取出", phonetic: "/pɒp/", spell: false },
        { en: "lose weight", cn: "减轻体重", phonetic: "/luːz weɪt/", spell: false },
        { en: "understanding", cn: "善解人意的", phonetic: "/ˌʌndəˈstændɪŋ/", spell: false },
        { en: "England", cn: "英国", phonetic: "/ˈɪŋɡlənd/", spell: false }
    ],

    "B2级 Unit 11": [
        { en: "negative", cn: "负面的", phonetic: "/ˈneɡətɪv/", spell: false },
        { en: "poster", cn: "海报", phonetic: "/ˈpəʊstə(r)/", spell: false },
        { en: "trainer", cn: "教练员；运动鞋", phonetic: "/ˈtreɪnə(r)/", spell: false },
        { en: "fool", cn: "傻瓜；愚弄", phonetic: "/fuːl/", spell: false },
        { en: "stress", cn: "压力；加压力于", phonetic: "/stres/", spell: false },
        { en: "nobody", cn: "没人", phonetic: "/ˈnəʊbədi/", spell: false },
        { en: "Australia", cn: "澳大利亚", phonetic: "/ɒˈstreɪliə/", spell: false },
        { en: "button", cn: "按键", phonetic: "/ˈbʌtn/", spell: false },
        { en: "clerk", cn: "职员；店员", phonetic: "/klɑːk/", spell: false },
        { en: "sausage", cn: "香肠", phonetic: "/ˈsɒsɪdʒ/", spell: false },
        { en: "female", cn: "女性", phonetic: "/ˈfiːmeɪl/", spell: false },
        { en: "population", cn: "人口", phonetic: "/ˌpɒpjuˈleɪʃn/", spell: false },
        { en: "host", cn: "主持人；主办", phonetic: "/həʊst/", spell: false },
        { en: "university", cn: "大学", phonetic: "/ˌjuːnɪˈvɜːsəti/", spell: false },
        { en: "pole", cn: "极；电线杆", phonetic: "/pəʊl/", spell: false },
        { en: "rainbow", cn: "彩虹", phonetic: "/ˈreɪnbəʊ/", spell: false },
        { en: "kilogram", cn: "千克", phonetic: "/ˈkɪləɡræm/", spell: false },
        { en: "spaceship", cn: "宇宙飞船", phonetic: "/ˈspeɪsʃɪp/", spell: false },
        { en: "brain", cn: "大脑", phonetic: "/breɪn/", spell: false },
        { en: "since", cn: "自从", phonetic: "/sɪns/", spell: false },
        { en: "quite", cn: "相当；完全", phonetic: "/kwaɪt/", spell: false },
        { en: "endangered", cn: "濒危；灭绝的", phonetic: "/ɪnˈdeɪndʒəd/", spell: false },
        { en: "businessman", cn: "商人", phonetic: "/ˈbɪznəsmæn/", spell: false },
        { en: "banker", cn: "银行家", phonetic: "/ˈbæŋkə(r)/", spell: false },
        { en: "lively", cn: "充满活力的；生动有趣的", phonetic: "/ˈlaɪvli/", spell: false },
        { en: "talk about", cn: "谈论", phonetic: "/tɔːk əˈbaʊt/", spell: false },
        { en: "honest", cn: "诚实的", phonetic: "/ˈɒnɪst/", spell: false },
        { en: "sign", cn: "符号；签名", phonetic: "/saɪn/", spell: false }
    ],

    "B2级 Unit 12": [
        { en: "hopefully", cn: "有希望地", phonetic: "/ˈhəʊpfəli/", spell: false },
        { en: "reflect", cn: "反射", phonetic: "/rɪˈflekt/", spell: false },
        { en: "fry", cn: "用油煎", phonetic: "/fraɪ/", spell: false },
        { en: "fix", cn: "修理", phonetic: "/fɪks/", spell: false },
        { en: "blood", cn: "血液", phonetic: "/blʌd/", spell: false },
        { en: "planet", cn: "行星", phonetic: "/ˈplænɪt/", spell: false },
        { en: "test", cn: "测试", phonetic: "/test/", spell: false },
        { en: "wool", cn: "羊毛", phonetic: "/wʊl/", spell: false },
        { en: "uncomfortable", cn: "不舒服的", phonetic: "/ʌnˈkʌmftəbl/", spell: false },
        { en: "handbag", cn: "手提包", phonetic: "/ˈhændbæɡ/", spell: false },
        { en: "pack", cn: "包；打包，包装", phonetic: "/pæk/", spell: false },
        { en: "speech", cn: "演讲", phonetic: "/spiːtʃ/", spell: false },
        { en: "design", cn: "设计", phonetic: "/dɪˈzaɪn/", spell: false },
        { en: "century", cn: "世纪", phonetic: "/ˈsentʃəri/", spell: false },
        { en: "clay", cn: "黏土", phonetic: "/kleɪ/", spell: false },
        { en: "Atlantic", cn: "大西洋", phonetic: "/ətˈlæntɪk/", spell: false },
        { en: "stair", cn: "楼梯", phonetic: "/steə(r)/", spell: false },
        { en: "Japan", cn: "日本", phonetic: "/dʒəˈpæn/", spell: false },
        { en: "topic", cn: "话题", phonetic: "/ˈtɒpɪk/", spell: false },
        { en: "mainly", cn: "主要地", phonetic: "/ˈmeɪnli/", spell: false },
        { en: "expensive", cn: "昂贵的", phonetic: "/ɪkˈspensɪv/", spell: false },
        { en: "string", cn: "细绳；线；一串", phonetic: "/strɪŋ/", spell: false },
        { en: "twin", cn: "双胞胎", phonetic: "/twɪn/", spell: false },
        { en: "grow up", cn: "长大", phonetic: "/ɡrəʊ ʌp/", spell: false },
        { en: "flood", cn: "洪水", phonetic: "/flʌd/", spell: false },
        { en: "would rather", cn: "宁愿", phonetic: "/wʊd ˈrɑːðə(r)/", spell: false },
        { en: "onto", cn: "到……上", phonetic: "/ˈɒntə/", spell: false },
        { en: "smoke", cn: "烟", phonetic: "/sməʊk/", spell: false }
    ],

    "B2级 Unit 13": [
        { en: "recommend", cn: "推荐", phonetic: "/ˌrekəˈmend/", spell: false },
        { en: "wildlife", cn: "野生动物", phonetic: "/ˈwaɪldlaɪf/", spell: false },
        { en: "pioneer", cn: "先驱者；开拓者", phonetic: "/ˌpaɪəˈnɪə(r)/", spell: false },
        { en: "Asian", cn: "亚洲的；亚洲人", phonetic: "/ˈeɪʃn/", spell: false },
        { en: "deal", cn: "处理；交易", phonetic: "/diːl/", spell: false },
        { en: "concert", cn: "音乐会", phonetic: "/ˈkɒnsət/", spell: false },
        { en: "Europe", cn: "欧洲", phonetic: "/ˈjʊərəp/", spell: false },
        { en: "cost", cn: "费用；花费", phonetic: "/kɒst/", spell: false },
        { en: "channel", cn: "频道；渠道", phonetic: "/ˈtʃænl/", spell: false },
        { en: "on business", cn: "出差", phonetic: "/ɒn ˈbɪznəs/", spell: false },
        { en: "dentist", cn: "牙医", phonetic: "/ˈdentɪst/", spell: false },
        { en: "television", cn: "电视", phonetic: "/ˈtelɪvɪʒn/", spell: false },
        { en: "character", cn: "角色；性格；字", phonetic: "/ˈkærəktə(r)/", spell: false },
        { en: "get into", cn: "进入；陷入", phonetic: "/ɡet ˈɪntuː/", spell: false },
        { en: "refrigerator", cn: "冰箱", phonetic: "/rɪˈfrɪdʒəreɪtə(r)/", spell: false },
        { en: "cafe", cn: "咖啡馆", phonetic: "/ˈkæfeɪ/", spell: false },
        { en: "strength", cn: "力量；力气", phonetic: "/streŋθ/", spell: false },
        { en: "soil", cn: "土壤；土地", phonetic: "/sɔɪl/", spell: false },
        { en: "Britain", cn: "英国", phonetic: "/ˈbrɪtn/", spell: false },
        { en: "palace", cn: "宫殿", phonetic: "/ˈpæləs/", spell: false },
        { en: "model", cn: "模型；模范", phonetic: "/ˈmɒdl/", spell: false },
        { en: "voluntary", cn: "自愿的", phonetic: "/ˈvɒləntri/", spell: false },
        { en: "regard", cn: "认为；看待", phonetic: "/rɪˈɡɑːd/", spell: false },
        { en: "historical", cn: "历史的", phonetic: "/hɪˈstɒrɪkl/", spell: false },
        { en: "cotton", cn: "棉花；棉的", phonetic: "/ˈkɒtn/", spell: false },
        { en: "friendship", cn: "友谊", phonetic: "/ˈfrendʃɪp/", spell: false },
        { en: "weak", cn: "虚弱的；弱的", phonetic: "/wiːk/", spell: false },
        { en: "herself", cn: "她自己", phonetic: "/hɜːˈself/", spell: false }
    ],

    "B2级 Unit 14": [
        { en: "ceiling", cn: "天花板", phonetic: "/ˈsiːlɪŋ/", spell: false },
        { en: "virus", cn: "病毒", phonetic: "/ˈvaɪrəs/", spell: false },
        { en: "transport", cn: "运输；交通工具", phonetic: "/ˈtrænspɔːt/", spell: false },
        { en: "European", cn: "欧洲的；欧洲人", phonetic: "/ˌjʊərəˈpiːən/", spell: false },
        { en: "surprised", cn: "感到吃惊的", phonetic: "/səˈpraɪzd/", spell: false },
        { en: "address", cn: "地址", phonetic: "/əˈdres/", spell: false },
        { en: "poem", cn: "诗", phonetic: "/ˈpəʊɪm/", spell: false },
        { en: "bleed", cn: "流血", phonetic: "/bliːd/", spell: false },
        { en: "intelligent", cn: "智能的；聪明的", phonetic: "/ɪnˈtelɪdʒənt/", spell: false },
        { en: "data", cn: "数据", phonetic: "/ˈdeɪtə/", spell: false },
        { en: "celebration", cn: "庆祝；庆祝会", phonetic: "/ˌselɪˈbreɪʃn/", spell: false },
        { en: "electricity", cn: "电", phonetic: "/ɪˌlekˈtrɪsəti/", spell: false },
        { en: "whenever", cn: "无论何时", phonetic: "/wenˈevə(r)/", spell: false },
        { en: "India", cn: "印度", phonetic: "/ˈɪndiə/", spell: false },
        { en: "hostess", cn: "女主人", phonetic: "/ˈhəʊstəs/", spell: false },
        { en: "nowhere", cn: "无处；任何地方都不", phonetic: "/ˈnəʊweə(r)/", spell: false },
        { en: "official", cn: "官员；正式的", phonetic: "/əˈfɪʃl/", spell: false },
        { en: "mention", cn: "提到；提及", phonetic: "/ˈmenʃn/", spell: false },
        { en: "foreign", cn: "外国的；外国人", phonetic: "/ˈfɒrən/", spell: false },
        { en: "fear", cn: "害怕；恐惧", phonetic: "/fɪə(r)/", spell: false },
        { en: "clear", cn: "清晰的；清楚的", phonetic: "/klɪə(r)/", spell: false },
        { en: "annual", cn: "每年的；年度的", phonetic: "/ˈænjuəl/", spell: false },
        { en: "warmth", cn: "温暖", phonetic: "/wɔːmθ/", spell: false },
        { en: "judge", cn: "法官；判断", phonetic: "/dʒʌdʒ/", spell: false },
        { en: "text", cn: "文本；课文", phonetic: "/tekst/", spell: false },
        { en: "asleep", cn: "睡着的", phonetic: "/əˈsliːp/", spell: false },
        { en: "role", cn: "角色", phonetic: "/rəʊl/", spell: false },
        { en: "reach", cn: "到达；抵达", phonetic: "/riːtʃ/", spell: false }
    ],

    "B2级 Unit 15": [
        { en: "petrol", cn: "汽油", phonetic: "/ˈpetrəl/", spell: false },
        { en: "decorate", cn: "装饰", phonetic: "/ˈdekəreɪt/", spell: false },
        { en: "familiar", cn: "熟悉的；常见的", phonetic: "/fəˈmɪliə(r)/", spell: false },
        { en: "passport", cn: "护照", phonetic: "/ˈpɑːspɔːt/", spell: false },
        { en: "development", cn: "发展", phonetic: "/dɪˈveləpmənt/", spell: false },
        { en: "army", cn: "军队", phonetic: "/ˈɑːmi/", spell: false },
        { en: "least", cn: "最少的", phonetic: "/liːst/", spell: false },
        { en: "budget", cn: "预算", phonetic: "/ˈbʌdʒɪt/", spell: false },
        { en: "medium", cn: "媒体；媒介", phonetic: "/ˈmiːdiəm/", spell: false },
        { en: "solution", cn: "解决方案；答案", phonetic: "/səˈluːʃn/", spell: false },
        { en: "be satisfied with", cn: "对…感到满意的", phonetic: "/biː ˈsætɪsfaɪd wɪð/", spell: false },
        { en: "whom", cn: "谁（宾格）", phonetic: "/huːm/", spell: false },
        { en: "leader", cn: "领导者", phonetic: "/ˈliːdə(r)/", spell: false },
        { en: "active", cn: "积极的；活跃的", phonetic: "/ˈæktɪv/", spell: false },
        { en: "extinct", cn: "灭绝的", phonetic: "/ɪkˈstɪŋkt/", spell: false },
        { en: "strange", cn: "奇怪的；陌生的", phonetic: "/streɪndʒ/", spell: false },
        { en: "aware", cn: "意识到的", phonetic: "/əˈweə(r)/", spell: false },
        { en: "tenth", cn: "第十", phonetic: "/tenθ/", spell: false },
        { en: "perform", cn: "表演；表现", phonetic: "/pəˈfɔːm/", spell: false },
        { en: "increase", cn: "增加；增长", phonetic: "/ɪnˈkriːs/", spell: false },
        { en: "ad", cn: "广告", phonetic: "/æd/", spell: false },
        { en: "false", cn: "假的；错误的", phonetic: "/fɔːls/", spell: false },
        { en: "stream", cn: "河流；溪流", phonetic: "/striːm/", spell: false },
        { en: "besides", cn: "此外；而且", phonetic: "/bɪˈsaɪdz/", spell: false },
        { en: "sand", cn: "沙子", phonetic: "/sænd/", spell: false },
        { en: "beauty", cn: "美人；美丽", phonetic: "/ˈbjuːti/", spell: false },
        { en: "Asia", cn: "亚洲", phonetic: "/ˈeɪʒə/", spell: false },
        { en: "subway", cn: "地铁；地下通道", phonetic: "/ˈsʌbweɪ/", spell: false }
    ],

    "B2级 Unit 16": [
        { en: "confidence", cn: "信心；自信", phonetic: "/ˈkɒnfɪdəns/", spell: false },
        { en: "swing", cn: "秋千；摇摆", phonetic: "/swɪŋ/", spell: false },
        { en: "cream", cn: "奶油", phonetic: "/kriːm/", spell: false },
        { en: "sudden", cn: "突然的", phonetic: "/ˈsʌdn/", spell: false },
        { en: "talent", cn: "天赋；才华", phonetic: "/ˈtælənt/", spell: false },
        { en: "careless", cn: "粗心的", phonetic: "/ˈkeələs/", spell: false },
        { en: "worth", cn: "值得的；价值", phonetic: "/wɜːθ/", spell: false },
        { en: "gather", cn: "聚集；收集", phonetic: "/ˈɡæðə(r)/", spell: false },
        { en: "servant", cn: "佣人；仆人", phonetic: "/ˈsɜːvənt/", spell: false },
        { en: "publish", cn: "出版；发表", phonetic: "/ˈpʌblɪʃ/", spell: false },
        { en: "spoon", cn: "汤匙", phonetic: "/spuːn/", spell: false },
        { en: "programme", cn: "节目；计划", phonetic: "/ˈprəʊɡræm/", spell: false },
        { en: "necessary", cn: "必要的", phonetic: "/ˈnesəsəri/", spell: false },
        { en: "working", cn: "正在工作", phonetic: "/ˈwɜːkɪŋ/", spell: false },
        { en: "deer", cn: "鹿", phonetic: "/dɪə(r)/", spell: false },
        { en: "cash", cn: "现金", phonetic: "/kæʃ/", spell: false },
        { en: "humour", cn: "幽默", phonetic: "/ˈhjuːmə(r)/", spell: false },
        { en: "Italian", cn: "意大利的；意大利语", phonetic: "/ɪˈtæliən/", spell: false },
        { en: "community", cn: "社区", phonetic: "/kəˈmjuːnəti/", spell: false },
        { en: "crazy", cn: "疯狂的", phonetic: "/ˈkreɪzi/", spell: false },
        { en: "type", cn: "类型；打字", phonetic: "/taɪp/", spell: false },
        { en: "honour", cn: "荣誉", phonetic: "/ˈɒnə(r)/", spell: false },
        { en: "examination", cn: "考试", phonetic: "/ɪɡˌzæmɪˈneɪʃn/", spell: false },
        { en: "bar", cn: "酒吧；条", phonetic: "/bɑː(r)/", spell: false },
        { en: "direct", cn: "直接的", phonetic: "/daɪˈrekt/", spell: false },
        { en: "officer", cn: "长官；官员", phonetic: "/ˈɒfɪsə(r)/", spell: false },
        { en: "silk", cn: "丝绸", phonetic: "/sɪlk/", spell: false },
        { en: "countryside", cn: "农村；乡村", phonetic: "/ˈkʌntrisaɪd/", spell: false }
    ],

    "B2级 Unit 17": [
        { en: "feature", cn: "特征；特色", phonetic: "/ˈfiːtʃə(r)/", spell: false },
        { en: "crowded", cn: "拥挤的", phonetic: "/ˈkraʊdɪd/", spell: false },
        { en: "otherwise", cn: "否则；不然", phonetic: "/ˈʌðəwaɪz/", spell: false },
        { en: "northeast", cn: "东北方的", phonetic: "/ˌnɔːθˈiːst/", spell: false },
        { en: "offer", cn: "提供；提议", phonetic: "/ˈɒfə(r)/", spell: false },
        { en: "abroad", cn: "在国外；到国外", phonetic: "/əˈbrɔːd/", spell: false },
        { en: "dictionary", cn: "词典；字典", phonetic: "/ˈdɪkʃənri/", spell: false },
        { en: "monitor", cn: "班长；监视器", phonetic: "/ˈmɒnɪtə(r)/", spell: false },
        { en: "part-time", cn: "兼职的", phonetic: "/ˌpɑːt ˈtaɪm/", spell: false },
        { en: "suit", cn: "西装；套装", phonetic: "/suːt/", spell: false },
        { en: "gentleman", cn: "绅士", phonetic: "/ˈdʒentlmən/", spell: false },
        { en: "whatever", cn: "无论什么", phonetic: "/wɒtˈevə(r)/", spell: false },
        { en: "rather", cn: "宁愿；相当", phonetic: "/ˈrɑːðə(r)/", spell: false },
        { en: "radio", cn: "收音机", phonetic: "/ˈreɪdiəʊ/", spell: false },
        { en: "teenage", cn: "青少年的", phonetic: "/ˈtiːneɪdʒ/", spell: false },
        { en: "disappoint", cn: "使失望", phonetic: "/ˌdɪsəˈpɔɪnt/", spell: false },
        { en: "senior", cn: "高级的；年长的", phonetic: "/ˈsiːniə(r)/", spell: false },
        { en: "capital", cn: "首都", phonetic: "/ˈkæpɪtl/", spell: false },
        { en: "happily", cn: "开心地", phonetic: "/ˈhæpɪli/", spell: false },
        { en: "freshly", cn: "刚刚；新鲜地", phonetic: "/ˈfreʃli/", spell: false },
        { en: "noisy", cn: "吵闹的", phonetic: "/ˈnɔɪzi/", spell: false },
        { en: "basis", cn: "基础", phonetic: "/ˈbeɪsɪs/", spell: false },
        { en: "surely", cn: "当然；无疑", phonetic: "/ˈʃʊəli/", spell: false },
        { en: "income", cn: "收入", phonetic: "/ˈɪnkʌm/", spell: false },
        { en: "goose", cn: "鹅", phonetic: "/ɡuːs/", spell: false },
        { en: "heat", cn: "热；热量", phonetic: "/hiːt/", spell: false },
        { en: "impossible", cn: "不可能的", phonetic: "/ɪmˈpɒsəbl/", spell: false },
        { en: "visitor", cn: "访客；参观者", phonetic: "/ˈvɪzɪtə(r)/", spell: false }
    ],

    "B2级 Unit 18": [
        { en: "kilometre", cn: "千米", phonetic: "/ˈkɪləmiːtə(r)/", spell: false },
        { en: "enjoyable", cn: "令人享受的", phonetic: "/ɪnˈdʒɔɪəbl/", spell: false },
        { en: "furniture", cn: "家具", phonetic: "/ˈfɜːnɪtʃə(r)/", spell: false },
        { en: "pollute", cn: "污染", phonetic: "/pəˈluːt/", spell: false },
        { en: "avoid", cn: "避免", phonetic: "/əˈvɔɪd/", spell: false },
        { en: "reduce", cn: "减少", phonetic: "/rɪˈdjuːs/", spell: false },
        { en: "postman", cn: "邮递员", phonetic: "/ˈpəʊstmən/", spell: false },
        { en: "realise", cn: "意识到", phonetic: "/ˈriəlaɪz/", spell: false },
        { en: "neighbourhood", cn: "居住区；社区", phonetic: "/ˈneɪbəhʊd/", spell: false },
        { en: "master", cn: "主人；大师", phonetic: "/ˈmɑːstə(r)/", spell: false },
        { en: "spare", cn: "空闲的；多余的", phonetic: "/speə(r)/", spell: false },
        { en: "forever", cn: "永远", phonetic: "/fərˈevə(r)/", spell: false },
        { en: "copy", cn: "复制；抄写", phonetic: "/ˈkɒpi/", spell: false },
        { en: "yourselves", cn: "你们自己", phonetic: "/jɔːˈselvz/", spell: false },
        { en: "teen", cn: "青少年", phonetic: "/tiːn/", spell: false },
        { en: "expert", cn: "专家", phonetic: "/ˈekspɜːt/", spell: false },
        { en: "satisfy", cn: "使满足", phonetic: "/ˈsætɪsfaɪ/", spell: false },
        { en: "surf", cn: "冲浪", phonetic: "/sɜːf/", spell: false },
        { en: "god", cn: "上帝", phonetic: "/ɡɒd/", spell: false },
        { en: "anyway", cn: "不管怎样", phonetic: "/ˈeniweɪ/", spell: false },
        { en: "wallet", cn: "钱包", phonetic: "/ˈwɒlɪt/", spell: false },
        { en: "sunshine", cn: "阳光", phonetic: "/ˈsʌnʃaɪn/", spell: false },
        { en: "pattern", cn: "模式；图案", phonetic: "/ˈpætn/", spell: false },
        { en: "creative", cn: "有创造性的", phonetic: "/kriˈeɪtɪv/", spell: false },
        { en: "in charge of", cn: "主管；负责", phonetic: "/ɪn tʃɑːdʒ ɒv/", spell: false },
        { en: "challenging", cn: "挑战性的", phonetic: "/ˈtʃælɪndʒɪŋ/", spell: false },
        { en: "stick", cn: "粘贴；坚持", phonetic: "/stɪk/", spell: false },
        { en: "lamp", cn: "灯", phonetic: "/læmp/", spell: false }
    ],

    "B2级 Unit 19": [
        { en: "donate", cn: "捐献；捐赠", phonetic: "/dəʊˈneɪt/", spell: false },
        { en: "dessert", cn: "甜点", phonetic: "/dɪˈzɜːt/", spell: false },
        { en: "battery", cn: "电池", phonetic: "/ˈbætəri/", spell: false },
        { en: "separate", cn: "分开；分离", phonetic: "/ˈsepəreɪt/", spell: false },
        { en: "telephone", cn: "电话", phonetic: "/ˈtelɪfəʊn/", spell: false },
        { en: "central", cn: "中心的；中央的", phonetic: "/ˈsentrl/", spell: false },
        { en: "bicycle", cn: "自行车", phonetic: "/ˈbaɪsɪkl/", spell: false },
        { en: "magical", cn: "有魔力的", phonetic: "/ˈmædʒɪkl/", spell: false },
        { en: "inventor", cn: "发明者", phonetic: "/ɪnˈventə(r)/", spell: false },
        { en: "complain", cn: "抱怨；投诉", phonetic: "/kəmˈpleɪn/", spell: false },
        { en: "silver", cn: "银", phonetic: "/ˈsɪlvə(r)/", spell: false },
        { en: "alarm", cn: "警报；闹钟", phonetic: "/əˈlɑːm/", spell: false },
        { en: "stupid", cn: "愚蠢的", phonetic: "/ˈstjuːpɪd/", spell: false },
        { en: "bowl", cn: "碗；盒", phonetic: "/bəʊl/", spell: false },
        { en: "context", cn: "上下文；语境", phonetic: "/ˈkɒntekst/", spell: false },
        { en: "fuel", cn: "燃料", phonetic: "/fjuːəl/", spell: false },
        { en: "lifestyle", cn: "生活方式", phonetic: "/ˈlaɪfstaɪl/", spell: false },
        { en: "conclusion", cn: "结论", phonetic: "/kənˈkluːʒn/", spell: false },
        { en: "suppose", cn: "假设；猜想", phonetic: "/səˈpəʊz/", spell: false },
        { en: "soccer", cn: "足球", phonetic: "/ˈsɒkə(r)/", spell: false },
        { en: "tape", cn: "胶带", phonetic: "/teɪp/", spell: false },
        { en: "merry", cn: "高兴的；愉快的", phonetic: "/ˈmeri/", spell: false },
        { en: "widely", cn: "广泛地", phonetic: "/ˈwaɪdli/", spell: false },
        { en: "deliver", cn: "递送；交付", phonetic: "/dɪˈlɪvə(r)/", spell: false },
        { en: "dare", cn: "敢", phonetic: "/deə(r)/", spell: false },
        { en: "soap", cn: "肥皂", phonetic: "/səʊp/", spell: false },
        { en: "gold", cn: "黄金的", phonetic: "/ɡəʊld/", spell: false },
        { en: "twentieth", cn: "第二十", phonetic: "/ˈtwentiəθ/", spell: false }
    ],

    "B2级 Unit 20": [
        { en: "goodness", cn: "善良；美德", phonetic: "/ˈɡʊdnəs/", spell: false },
        { en: "throat", cn: "喉咙", phonetic: "/θrəʊt/", spell: false },
        { en: "appearance", cn: "外貌；出现", phonetic: "/əˈpɪərəns/", spell: false },
        { en: "shut", cn: "关闭", phonetic: "/ʃʌt/", spell: false },
        { en: "mail", cn: "邮件", phonetic: "/meɪl/", spell: false },
        { en: "usual", cn: "通常的", phonetic: "/ˈjuːʒuəl/", spell: false },
        { en: "fridge", cn: "冰箱", phonetic: "/frɪdʒ/", spell: false },
        { en: "champion", cn: "冠军", phonetic: "/ˈtʃæmpiən/", spell: false },
        { en: "raincoat", cn: "雨衣", phonetic: "/ˈreɪnkəʊt/", spell: false },
        { en: "wherever", cn: "无论哪里", phonetic: "/werˈevə(r)/", spell: false },
        { en: "Australian", cn: "澳大利亚(人)的", phonetic: "/ɒˈstreɪliən/", spell: false },
        { en: "luckily", cn: "幸运地", phonetic: "/ˈlʌkɪli/", spell: false },
        { en: "shell", cn: "贝壳", phonetic: "/ʃel/", spell: false },
        { en: "opposite", cn: "相反的", phonetic: "/ˈɒpəzɪt/", spell: false },
        { en: "artwork", cn: "艺术品", phonetic: "/ˈɑːtwɜːk/", spell: false },
        { en: "kindness", cn: "仁慈；善良", phonetic: "/ˈkaɪndnəs/", spell: false },
        { en: "captain", cn: "船长", phonetic: "/ˈkæptɪn/", spell: false },
        { en: "bottom", cn: "底部", phonetic: "/ˈbɒtəm/", spell: false },
        { en: "coal", cn: "煤炭", phonetic: "/kəʊl/", spell: false },
        { en: "biscuit", cn: "饼干", phonetic: "/ˈbɪskɪt/", spell: false },
        { en: "unfair", cn: "不公平的", phonetic: "/ʌnˈfeə(r)/", spell: false },
        { en: "facility", cn: "设备；设施", phonetic: "/fəˈsɪləti/", spell: false },
        { en: "destination", cn: "目的地", phonetic: "/ˌdestɪˈneɪʃn/", spell: false },
        { en: "opera", cn: "歌剧", phonetic: "/ˈɒprə/", spell: false },
        { en: "recycle", cn: "回收利用", phonetic: "/ˌriːˈsaɪkl/", spell: false },
        { en: "repair", cn: "修理", phonetic: "/rɪˈpeə(r)/", spell: false },
        { en: "title", cn: "标题", phonetic: "/ˈtaɪtl/", spell: false },
        { en: "schoolwork", cn: "学校作业；功课", phonetic: "/ˈskuːlwɜːk/", spell: false }
    ],

    "B2级 Unit 21": [
        { en: "outgoing", cn: "外向的", phonetic: "/ˈaʊtɡəʊɪŋ/", spell: false },
        { en: "cruel", cn: "残忍的", phonetic: "/ˈkruːəl/", spell: false },
        { en: "pressure", cn: "压力", phonetic: "/ˈpreʃə(r)/", spell: false },
        { en: "location", cn: "位置；地点", phonetic: "/ləʊˈkeɪʃn/", spell: false },
        { en: "destroy", cn: "破坏；毁坏", phonetic: "/dɪˈstrɔɪ/", spell: false },
        { en: "lazy", cn: "懒惰的", phonetic: "/ˈleɪzi/", spell: false },
        { en: "grandparent", cn: "(外)祖父母", phonetic: "/ˈɡrænpeərənt/", spell: false },
        { en: "slim", cn: "苗条的", phonetic: "/slɪm/", spell: false },
        { en: "shelf", cn: "架子", phonetic: "/ʃelf/", spell: false },
        { en: "source", cn: "来源", phonetic: "/sɔːs/", spell: false },
        { en: "dislike", cn: "不喜欢", phonetic: "/dɪsˈlaɪk/", spell: false },
        { en: "advantage", cn: "优势；优点", phonetic: "/ədˈvɑːntɪdʒ/", spell: false },
        { en: "somewhere", cn: "某处；某地", phonetic: "/ˈsʌmweə(r)/", spell: false },
        { en: "hundredth", cn: "第一百", phonetic: "/ˈhʌndrədθ/", spell: false },
        { en: "organise", cn: "组织", phonetic: "/ˈɔːɡənaɪz/", spell: false },
        { en: "exit", cn: "出口；退出", phonetic: "/ˈeɡzɪt/", spell: false },
        { en: "dining", cn: "用餐", phonetic: "/ˈdaɪnɪŋ/", spell: false },
        { en: "cent", cn: "分", phonetic: "/sent/", spell: false },
        { en: "first of all", cn: "首先", phonetic: "/fɜːst ɒv ɔːl/", spell: false },
        { en: "course", cn: "课程；科目", phonetic: "/kɔːs/", spell: false },
        { en: "environment", cn: "环境", phonetic: "/ɪnˈvaɪrənmənt/", spell: false },
        { en: "towel", cn: "毛巾", phonetic: "/ˈtaʊəl/", spell: false },
        { en: "rapid", cn: "快速的", phonetic: "/ˈræpɪd/", spell: false },
        { en: "range", cn: "范围", phonetic: "/reɪndʒ/", spell: false },
        { en: "public", cn: "公共的", phonetic: "/ˈpʌblɪk/", spell: false },
        { en: "Canadian", cn: "加拿大(人)的", phonetic: "/kəˈneɪdiən/", spell: false },
        { en: "sense", cn: "感觉；意识", phonetic: "/sens/", spell: false },
        { en: "business", cn: "生意；商业", phonetic: "/ˈbɪznəs/", spell: false }
    ],

    "B2级 Unit 22": [
        { en: "recognise", cn: "认出；识别", phonetic: "/ˈrekəɡnaɪz/", spell: false },
        { en: "click", cn: "点击", phonetic: "/klɪk/", spell: false },
        { en: "schedule", cn: "时间表；日程", phonetic: "/ˈʃedjuːl/", spell: false },
        { en: "sort", cn: "分类；种类", phonetic: "/sɔːt/", spell: false },
        { en: "bill", cn: "账单", phonetic: "/bɪl/", spell: false },
        { en: "PLA", cn: "中国人民解放军", phonetic: "/ˌpiː el ˈeɪ/", spell: false },
        { en: "independent", cn: "独立的", phonetic: "/ˌɪndɪˈpendənt/", spell: false },
        { en: "download", cn: "下载", phonetic: "/ˌdaʊnˈləʊd/", spell: false },
        { en: "attach", cn: "附加；附着", phonetic: "/əˈtætʃ/", spell: false },
        { en: "represent", cn: "代表", phonetic: "/ˌreprɪˈzent/", spell: false },
        { en: "guard", cn: "守卫；保卫", phonetic: "/ɡɑːd/", spell: false },
        { en: "graduate", cn: "毕业；毕业生", phonetic: "/ˈɡrædʒueɪt/", spell: false },
        { en: "fail", cn: "失败", phonetic: "/feɪl/", spell: false },
        { en: "yet", cn: "还；尚未", phonetic: "/jet/", spell: false },
        { en: "socialism", cn: "社会主义", phonetic: "/ˈsəʊʃəlɪzəm/", spell: false },
        { en: "image", cn: "图像；形象", phonetic: "/ˈɪmɪdʒ/", spell: false },
        { en: "advertisement", cn: "广告", phonetic: "/ədˈvɜːtɪsmənt/", spell: false },
        { en: "truck", cn: "卡车", phonetic: "/trʌk/", spell: false },
        { en: "value", cn: "价值", phonetic: "/ˈvæljuː/", spell: false },
        { en: "attention", cn: "注意", phonetic: "/əˈtenʃn/", spell: false },
        { en: "recently", cn: "最近", phonetic: "/ˈriːsntli/", spell: false },
        { en: "pipe", cn: "管道", phonetic: "/paɪp/", spell: false },
        { en: "unbelievable", cn: "难以置信的", phonetic: "/ˌʌnbɪˈliːvəbl/", spell: false },
        { en: "disaster", cn: "灾难", phonetic: "/dɪˈzɑːstə(r)/", spell: false },
        { en: "pronunciation", cn: "发音", phonetic: "/prəˌnʌnsiˈeɪʃn/", spell: false },
        { en: "bite", cn: "咬", phonetic: "/baɪt/", spell: false },
        { en: "cheese", cn: "奶酪", phonetic: "/tʃiːz/", spell: false },
        { en: "interested", cn: "感兴趣的", phonetic: "/ˈɪntrəstɪd/", spell: false }
    ],

    "B2级 Unit 23": [
        { en: "packet", cn: "包；小包", phonetic: "/ˈpækɪt/", spell: false },
        { en: "bored", cn: "无聊的；厌倦的", phonetic: "/bɔːd/", spell: false },
        { en: "typical", cn: "典型的", phonetic: "/ˈtɪpɪkl/", spell: false },
        { en: "silence", cn: "沉默", phonetic: "/ˈsaɪləns/", spell: false },
        { en: "southeast", cn: "东南方", phonetic: "/ˌsaʊθˈiːst/", spell: false },
        { en: "guest", cn: "客人", phonetic: "/ɡest/", spell: false },
        { en: "human", cn: "人类", phonetic: "/ˈhjuːmən/", spell: false },
        { en: "housewife", cn: "家庭主妇", phonetic: "/ˈhaʊswaɪf/", spell: false },
        { en: "branch", cn: "树枝；分支", phonetic: "/brɑːntʃ/", spell: false },
        { en: "aid", cn: "援助", phonetic: "/eɪd/", spell: false },
        { en: "literature", cn: "文学", phonetic: "/ˈlɪtrətʃə(r)/", spell: false },
        { en: "prevent", cn: "阻止；预防", phonetic: "/prɪˈvent/", spell: false },
        { en: "toothache", cn: "牙痛", phonetic: "/ˈtuːθeɪk/", spell: false },
        { en: "British", cn: "英国人的；英国的", phonetic: "/ˈbrɪtɪʃ/", spell: false },
        { en: "era", cn: "时代；纪元", phonetic: "/ˈɪərə/", spell: false },
        { en: "camel", cn: "骆驼", phonetic: "/ˈkæml/", spell: false },
        { en: "retire", cn: "退休", phonetic: "/rɪˈtaɪə(r)/", spell: false },
        { en: "harmful", cn: "有害的", phonetic: "/ˈhɑːmfl/", spell: false },
        { en: "mostly", cn: "主要地", phonetic: "/ˈməʊstli/", spell: false },
        { en: "invent", cn: "发明", phonetic: "/ɪnˈvent/", spell: false },
        { en: "probably", cn: "大概；可能", phonetic: "/ˈprɒbəbli/", spell: false },
        { en: "unhealthy", cn: "不健康的", phonetic: "/ʌnˈhelθi/", spell: false },
        { en: "energetic", cn: "精力充沛的", phonetic: "/ˌenəˈdʒetɪk/", spell: false },
        { en: "seriously", cn: "严肃地；认真地", phonetic: "/ˈsɪəriəsli/", spell: false },
        { en: "pity", cn: "遗憾", phonetic: "/ˈpɪti/", spell: false },
        { en: "single", cn: "单一的", phonetic: "/ˈsɪŋɡl/", spell: false },
        { en: "jeans", cn: "牛仔裤", phonetic: "/dʒiːnz/", spell: false },
        { en: "thousand", cn: "千", phonetic: "/ˈθaʊznd/", spell: false }
    ],

    "B2级 Unit 24": [
        { en: "absolutely", cn: "绝对地", phonetic: "/ˈæbsəluːtli/", spell: false },
        { en: "steam", cn: "水蒸气", phonetic: "/stiːm/", spell: false },
        { en: "compete", cn: "竞争", phonetic: "/kəmˈpiːt/", spell: false },
        { en: "ton", cn: "吨", phonetic: "/tʌn/", spell: false },
        { en: "tiny", cn: "微小的", phonetic: "/ˈtaɪni/", spell: false },
        { en: "worst", cn: "最差的", phonetic: "/wɜːst/", spell: false },
        { en: "France", cn: "法国", phonetic: "/frɑːns/", spell: false },
        { en: "maintain", cn: "维持；保持", phonetic: "/meɪnˈteɪn/", spell: false },
        { en: "exact", cn: "精确的", phonetic: "/ɪɡˈzækt/", spell: false },
        { en: "contain", cn: "包含；容纳", phonetic: "/kənˈteɪn/", spell: false },
        { en: "manager", cn: "经理", phonetic: "/ˈmænɪdʒə(r)/", spell: false },
        { en: "relation", cn: "关系", phonetic: "/rɪˈleɪʃn/", spell: false },
        { en: "hearing", cn: "听觉；听力", phonetic: "/ˈhɪərɪŋ/", spell: false },
        { en: "million", cn: "百万", phonetic: "/ˈmɪljən/", spell: false },
        { en: "particular", cn: "特殊的", phonetic: "/pəˈtɪkjələ(r)/", spell: false },
        { en: "fold", cn: "折叠", phonetic: "/fəʊld/", spell: false },
        { en: "arrival", cn: "到达", phonetic: "/əˈraɪvl/", spell: false },
        { en: "congratulation", cn: "祝贺；庆祝", phonetic: "/kənˌɡrætʃuˈleɪʃn/", spell: false },
        { en: "waiter", cn: "服务员", phonetic: "/ˈweɪtə(r)/", spell: false },
        { en: "birth", cn: "出生", phonetic: "/bɜːθ/", spell: false },
        { en: "twice", cn: "两次", phonetic: "/twaɪs/", spell: false },
        { en: "mall", cn: "购物中心", phonetic: "/mɔːl/", spell: false },
        { en: "similarity", cn: "相似性；类似", phonetic: "/ˌsɪmɪˈlærəti/", spell: false },
        { en: "universe", cn: "宇宙", phonetic: "/ˈjuːnɪvɜːs/", spell: false },
        { en: "in addition", cn: "此外", phonetic: "/ɪn əˈdɪʃn/", spell: false },
        { en: "base", cn: "基础", phonetic: "/beɪs/", spell: false },
        { en: "require", cn: "要求", phonetic: "/rɪˈwaɪə(r)/", spell: false },
        { en: "slowly", cn: "缓慢地", phonetic: "/ˈsləʊli/", spell: false }
    ],

    "B2级 Unit 28": [
        { en: "naturally", cn: "自然地；天生地；当然", phonetic: "/ˈnætʃrəli/", spell: false },
        { en: "scare", cn: "惊吓；使害怕；恐慌", phonetic: "/skeə(r)/", spell: false },
        { en: "digital", cn: "数字的；数码的", phonetic: "/ˈdɪdʒɪtl/", spell: false },
        { en: "wheat", cn: "小麦", phonetic: "/wiːt/", spell: false },
        { en: "supper", cn: "晚餐；晚饭", phonetic: "/ˈsʌpə(r)/", spell: false },
        { en: "chalk", cn: "粉笔", phonetic: "/tʃɔːk/", spell: false },
        { en: "training", cn: "训练；培训", phonetic: "/ˈtreɪnɪŋ/", spell: false },
        { en: "couch", cn: "长沙发；睡椅", phonetic: "/kaʊtʃ/", spell: false },
        { en: "mushroom", cn: "蘑菇", phonetic: "/ˈmʌʃruːm/", spell: false },
        { en: "rude", cn: "粗鲁的；无礼的", phonetic: "/ruːd/", spell: false },
        { en: "rocket", cn: "火箭", phonetic: "/ˈrɒkɪt/", spell: false },
        { en: "seventh", cn: "第七", phonetic: "/ˈsevnθ/", spell: false },
        { en: "print", cn: "印刷；打印", phonetic: "/prɪnt/", spell: false },
        { en: "below", cn: "在……下面；低于", phonetic: "/bɪˈləʊ/", spell: false },
        { en: "smartphone", cn: "智能手机", phonetic: "/ˈsmɑːtfəʊn/", spell: false },
        { en: "content", cn: "内容；满足的", phonetic: "/ˈkɒntent/", spell: false },
        { en: "dinosaur", cn: "恐龙", phonetic: "/ˈdaɪnəsɔː(r)/", spell: false },
        { en: "detail", cn: "细节；详情", phonetic: "/ˈdiːteɪl/", spell: false },
        { en: "pound", cn: "英镑；磅", phonetic: "/paʊnd/", spell: false },
        { en: "direction", cn: "方向；方位", phonetic: "/dəˈrekʃn/", spell: false },
        { en: "control", cn: "控制；操控", phonetic: "/kənˈtrəʊl/", spell: false },
        { en: "bin", cn: "垃圾箱；箱子", phonetic: "/bɪn/", spell: false },
        { en: "rubber", cn: "橡胶；橡皮", phonetic: "/ˈrʌbə(r)/", spell: false },
        { en: "partner", cn: "搭档；伙伴；合伙人", phonetic: "/ˈpɑːtnə(r)/", spell: false },
        { en: "foolish", cn: "愚蠢的；傻的", phonetic: "/ˈfuːlɪʃ/", spell: false },
        { en: "exciting", cn: "令人兴奋的；使人激动的", phonetic: "/ɪkˈsaɪtɪŋ/", spell: false },
        { en: "hole", cn: "洞；孔", phonetic: "/həʊl/", spell: false },
        { en: "wheel", cn: "轮子；车轮", phonetic: "/wiːl/", spell: false }
    ],

    "B2级 Unit 29": [
        { en: "Scotland", cn: "苏格兰", phonetic: "/ˈskɒtlənd/", spell: false },
        { en: "zebra", cn: "斑马", phonetic: "/ˈzebrə/", spell: false },
        { en: "highway", cn: "公路；高速公路", phonetic: "/ˈhaɪweɪ/", spell: false },
        { en: "punish", cn: "惩罚；处罚", phonetic: "/ˈpʌnɪʃ/", spell: false },
        { en: "argue", cn: "争论；争吵；辩论", phonetic: "/ˈɑːɡjuː/", spell: false },
        { en: "talented", cn: "有天赋的；有才能的", phonetic: "/ˈtæləntɪd/", spell: false },
        { en: "French", cn: "法国的；法国人；法语", phonetic: "/frentʃ/", spell: false },
        { en: "youth", cn: "青年；青春；青年时期", phonetic: "/juːθ/", spell: false },
        { en: "audience", cn: "听众；观众", phonetic: "/ˈɔːdiəns/", spell: false },
        { en: "above all", cn: "最重要的是；首先", phonetic: "/əˈbʌv ɔːl/", spell: false },
        { en: "try on", cn: "试穿", phonetic: "/traɪ ɒn/", spell: false },
        { en: "stand for", cn: "代表；象征；支持", phonetic: "/stænd fɔː(r)/", spell: false },
        { en: "happiness", cn: "幸福；快乐", phonetic: "/ˈhæpinəs/", spell: false },
        { en: "less than", cn: "少于；不到", phonetic: "/les ðæn/", spell: false },
        { en: "equipment", cn: "设备；装备", phonetic: "/ɪˈkwɪpmənt/", spell: false },
        { en: "quality", cn: "质量；品质", phonetic: "/ˈkwɒləti/", spell: false },
        { en: "by the way", cn: "顺便提一下；顺便说", phonetic: "/baɪ ðə weɪ/", spell: false },
        { en: "make progress", cn: "取得进步", phonetic: "/meɪk ˈprəʊɡres/", spell: false },
        { en: "take care of", cn: "照顾；照料", phonetic: "/teɪk keə(r) ɒv/", spell: false },
        { en: "be famous for", cn: "因……而出名", phonetic: "/biː ˈfeɪməs fɔː(r)/", spell: false },
        { en: "restroom", cn: "洗手间；公共厕所", phonetic: "/ˈrestruːm/", spell: false },
        { en: "damage", cn: "损害；损坏", phonetic: "/ˈdæmɪdʒ/", spell: false },
        { en: "flight", cn: "航班；飞行", phonetic: "/flaɪt/", spell: false },
        { en: "look out", cn: "小心；留神", phonetic: "/lʊk aʊt/", spell: false },
        { en: "all the time", cn: "一直；始终", phonetic: "/ɔːl ðə taɪm/", spell: false },
        { en: "be fond of", cn: "喜爱；喜欢", phonetic: "/biː fɒnd ɒv/", spell: false },
        { en: "be similar to", cn: "与……相似", phonetic: "/biː ˈsɪmələ(r) tuː/", spell: false },
        { en: "think about", cn: "考虑；思考", phonetic: "/ˈθɪŋk əˈbaʊt/", spell: false }
    ],

    "B2级 Unit 30": [
        { en: "upstairs", cn: "在楼上；向楼上；楼上的", phonetic: "/ˌʌpˈsteəz/", spell: false },
        { en: "survive", cn: "幸存；存活；生还", phonetic: "/səˈvaɪv/", spell: false },
        { en: "characteristic", cn: "特征；特点；典型的", phonetic: "/ˌkærəktəˈrɪstɪk/", spell: false },
        { en: "go ahead", cn: "请便；前进；继续进行", phonetic: "/ɡəʊ əˈhed/", spell: false },
        { en: "so that", cn: "以便；为了", phonetic: "/səʊ ðæt/", spell: false },
        { en: "vs", cn: "对抗；对阵", phonetic: "/ˌviː ˈes/", spell: false },
        { en: "cave", cn: "洞穴；山洞", phonetic: "/keɪv/", spell: false },
        { en: "loss", cn: "损失；丧失", phonetic: "/lɒs/", spell: false },
        { en: "career", cn: "职业；生涯", phonetic: "/kəˈrɪə(r)/", spell: false },
        { en: "be strict with", cn: "对……严格要求", phonetic: "/biː strɪkt wɪð/", spell: false },
        { en: "on the other hand", cn: "另一方面", phonetic: "/ɒn ðə ˈʌðə(r) hænd/", spell: false },
        { en: "look up", cn: "查阅；向上看", phonetic: "/lʊk ʌp/", spell: false },
        { en: "break down", cn: "出故障；坏掉；分解；崩溃", phonetic: "/breɪk daʊn/", spell: false },
        { en: "instead of", cn: "代替；而不是", phonetic: "/ɪnˈsted ɒv/", spell: false },
        { en: "balance", cn: "平衡；天平；使平衡", phonetic: "/ˈbæləns/", spell: false },
        { en: "global", cn: "全球的；全球性的", phonetic: "/ˈɡləʊbl/", spell: false },
        { en: "as for", cn: "至于；关于", phonetic: "/æz fɔː(r)/", spell: false },
        { en: "run out", cn: "用完；耗尽", phonetic: "/rʌn aʊt/", spell: false },
        { en: "pay attention to", cn: "注意；重视", phonetic: "/peɪ əˈtenʃn tuː/", spell: false },
        { en: "work out", cn: "算出；解决；锻炼", phonetic: "/wɜːk aʊt/", spell: false },
        { en: "pale", cn: "苍白的；灰白的", phonetic: "/peɪl/", spell: false },
        { en: "expression", cn: "表情；表达；措辞", phonetic: "/ɪkˈspreʃn/", spell: false },
        { en: "attract", cn: "吸引；引起……的注意", phonetic: "/əˈtrækt/", spell: false },
        { en: "in time", cn: "及时", phonetic: "/ɪn taɪm/", spell: false },
        { en: "futurist", cn: "未来学家", phonetic: "/ˈfjuːtʃərɪst/", spell: false },
        { en: "at present", cn: "目前；现在", phonetic: "/ət ˈpreznt/", spell: false },
        { en: "hear from", cn: "收到……的来信", phonetic: "/hɪə(r) frɒm/", spell: false },
        { en: "in one's opinion", cn: "在某人看来", phonetic: "/ɪn wʌnz əˈpɪnjən/", spell: false }
    ],

    "B2级 Unit 31": [
        { en: "benefit", cn: "利益；好处；益处", phonetic: "/ˈbenɪfɪt/", spell: false },
        { en: "path", cn: "小路；道路；路径", phonetic: "/pɑːθ/", spell: false },
        { en: "therefore", cn: "因此；所以", phonetic: "/ˈðeəfɔː(r)/", spell: false },
        { en: "join in", cn: "参加；加入", phonetic: "/dʒɔɪn ɪn/", spell: false },
        { en: "in trouble", cn: "处于困境中；遇到麻烦", phonetic: "/ɪn ˈtrʌbl/", spell: false },
        { en: "get on", cn: "上车；进展；和睦相处", phonetic: "/ɡet ɒn/", spell: false },
        { en: "wound", cn: "伤口；创伤；使受伤", phonetic: "/wuːnd/", spell: false },
        { en: "aim", cn: "目标；目的；瞄准", phonetic: "/eɪm/", spell: false },
        { en: "average", cn: "平均；平均的；普通的", phonetic: "/ˈævərɪdʒ/", spell: false },
        { en: "traditional", cn: "传统的", phonetic: "/trəˈdɪʃənl/", spell: false },
        { en: "Olympics", cn: "奥林匹克运动会；奥运会", phonetic: "/əˈlɪmpɪks/", spell: false },
        { en: "after all", cn: "毕竟；终究", phonetic: "/ˈɑːftər ɔːl/", spell: false },
        { en: "change one's mind", cn: "改变主意", phonetic: "/tʃeɪndʒ wʌnz maɪnd/", spell: false },
        { en: "chopsticks", cn: "筷子", phonetic: "/ˈtʃɒpstɪks/", spell: false },
        { en: "truly", cn: "真正地；真诚地；确实", phonetic: "/ˈtruːli/", spell: false },
        { en: "responsibility", cn: "责任；义务", phonetic: "/rɪˌspɒnsəˈbɪləti/", spell: false },
        { en: "province", cn: "省份；省", phonetic: "/ˈprɒvɪns/", spell: false },
        { en: "stressed", cn: "有压力的；紧张的", phonetic: "/strest/", spell: false },
        { en: "in the end", cn: "最后；终于", phonetic: "/ɪn ðə end/", spell: false },
        { en: "creativity", cn: "创造力；创造性", phonetic: "/ˌkriːeɪˈtɪvəti/", spell: false },
        { en: "in a hurry", cn: "匆忙地；急忙地", phonetic: "/ɪn ə ˈhʌri/", spell: false },
        { en: "upset", cn: "心烦的；沮丧的；打翻；扰乱", phonetic: "/ʌpˈset/", spell: false },
        { en: "reward", cn: "奖励；报酬；奖赏", phonetic: "/rɪˈwɔːd/", spell: false },
        { en: "missing", cn: "失踪的；缺少的", phonetic: "/ˈmɪsɪŋ/", spell: false },
        { en: "dress up", cn: "打扮；装扮；盛装打扮", phonetic: "/dres ʌp/", spell: false },
        { en: "rather than", cn: "而不是", phonetic: "/ˈrɑːðə(r) ðæn/", spell: false },
        { en: "and so on", cn: "等等；诸如此类", phonetic: "/ənd səʊ ɒn/", spell: false },
        { en: "as soon as", cn: "一……就……", phonetic: "/əz suːn əz/", spell: false }
    ],

    "B2级 Unit 32": [
        { en: "chemical", cn: "化学的；化学制品；化学品", phonetic: "/ˈkemɪkl/", spell: false },
        { en: "exchange", cn: "交换；交流；兑换", phonetic: "/ɪksˈtʃeɪndʒ/", spell: false },
        { en: "illness", cn: "疾病；病", phonetic: "/ˈɪlnəs/", spell: false },
        { en: "come to an end", cn: "结束；告终", phonetic: "/kʌm tuː ən end/", spell: false },
        { en: "in order to", cn: "为了；以便", phonetic: "/ɪn ˈɔːdə(r) tuː/", spell: false },
        { en: "close to", cn: "靠近；接近", phonetic: "/kləʊs tuː/", spell: false },
        { en: "author", cn: "作者；作家", phonetic: "/ˈɔːθə(r)/", spell: false },
        { en: "make up one's mind", cn: "下决心；下定决心", phonetic: "/meɪk ʌp wʌnz maɪnd/", spell: false },
        { en: "laboratory", cn: "实验室", phonetic: "/ləˈbɒrətri/", spell: false }
    ],

    // ==================== 1 级 ====================
    // 来源：《外研版高中词库1(R版v2)》Units 1-9
    // 中文释义经 AI 校正为高中考纲标准释义

    "1级 Unit 1": [
        { en: "lately", cn: "最近；近来", phonetic: "/ˈleɪtli/", spell: false },
        { en: "evolution", cn: "进化；演变；发展", phonetic: "/ˌiːvəˈlu˃n/", spell: false },
        { en: "export", cn: "出口；输出品", phonetic: "/ɪkˈspɔːt/", spell: false },
        { en: "ancestor", cn: "祖先；祖宗", phonetic: "/ˈænsestə(r)/", spell: false },
        { en: "discourage", cn: "使气馁；阻止；劝阻", phonetic: "/dɪsˈkʌrɪdʒ/", spell: false },
        { en: "expedition", cn: "远征；探险队", phonetic: "/ˌekspɪˈdɪʃn/", spell: false },
        { en: "mixture", cn: "混合物", phonetic: "/ˈmɪkstʃə(r)/", spell: false },
        { en: "bargain", cn: "便宜货；讨价还价", phonetic: "/ˈbɑːɡɪn/", spell: false },
        { en: "skilled", cn: "熟练的；有技能的", phonetic: "/skɪld/", spell: false },
        { en: "leather", cn: "皮革", phonetic: "/ˈleðə(r)/", spell: false },
        { en: "approximately", cn: "大约；近似地", phonetic: "/əˈprɒksɪmətli/", spell: false },
        { en: "personally", cn: "亲自地；就个人而言", phonetic: "/ˈpɜːsənəli/", spell: false },
        { en: "stadium", cn: "体育场；运动场", phonetic: "/ˈsteɪdiəm/", spell: false },
        { en: "suitcase", cn: "手提箱；行李箱", phonetic: "/ˈsuːtkeɪs/", spell: false },
        { en: "newcomer", cn: "新来的人；新手", phonetic: "/ˈnjuːkʌmə(r)/", spell: false },
        { en: "helpless", cn: "无助的；无能为力的", phonetic: "/ˈhelpləs/", spell: false },
        { en: "energetic", cn: "精力充沛的", phonetic: "/ˌenəˈdʒetɪk/", spell: false },
        { en: "chart", cn: "图表；海图", phonetic: "/tʃɑːt/", spell: false },
        { en: "republic", cn: "共和国", phonetic: "/rɪˈpʌblɪk/", spell: false },
        { en: "version", cn: "版本；说法", phonetic: "/ˈvɜːʃn/", spell: false },
        { en: "generous", cn: "慷慨的；大方的", phonetic: "/ˈdʒenərəs/", spell: false },
        { en: "burn up", cn: "烧毁；烧尽", phonetic: "/bɜːn ʌp/", spell: false },
        { en: "spoonful", cn: "一匙（的量）", phonetic: "/ˈspuːnfʊl/", spell: false },
        { en: "entrance", cn: "入口", phonetic: "/ˈentrəns/", spell: false },
        { en: "unlikely", cn: "不大可能的", phonetic: "/ʌnˈlaɪkli/", spell: false },
        { en: "click", cn: "点击；咔嗒声", phonetic: "/klɪk/", spell: false },
        { en: "philosophy", cn: "哲学", phonetic: "/fɪˈlɒsəfi/", spell: false },
        { en: "regardless", cn: "不管；不顾", phonetic: "/rɪˈɡɑːdləs/", spell: false }
    ],

    "1级 Unit 2": [
        { en: "bowling", cn: "保龄球运动", phonetic: "/ˈbəʊlɪŋ/", spell: false },
        { en: "motor", cn: "发动机；马达", phonetic: "/ˈməʊtə(r)/", spell: false },
        { en: "lung", cn: "肺", phonetic: "/lʌŋ/", spell: false },
        { en: "lightning", cn: "闪电", phonetic: "/ˈlaɪtnɪŋ/", spell: false },
        { en: "garbage", cn: "垃圾", phonetic: "/ˈɡɑːbɪdʒ/", spell: false },
        { en: "destination", cn: "目的地；终点", phonetic: "/ˌdestɪˈneɪʃn/", spell: false },
        { en: "aspect", cn: "方面；外观", phonetic: "/ˈæspekt/", spell: false },
        { en: "daylight", cn: "日光；白昼", phonetic: "/ˈdeɪlaɪt/", spell: false },
        { en: "factor", cn: "因素；要素", phonetic: "/ˈfæktə(r)/", spell: false },
        { en: "scenery", cn: "风景；景色", phonetic: "/ˈsiːnəri/", spell: false },
        { en: "equal", cn: "相等的；平等的；等于", phonetic: "/ˈiːkwəl/", spell: false },
        { en: "attach", cn: "依附；附上；连接", phonetic: "/əˈtætʃ/", spell: false },
        { en: "court", cn: "球场；法庭；宫廷", phonetic: "/kɔːt/", spell: false },
        { en: "altogether", cn: "总共；总而言之", phonetic: "/ˌɔːltəˈɡeðə(r)/", spell: false },
        { en: "footprint", cn: "脚印；足迹", phonetic: "/ˈfʊtprɪnt/", spell: false },
        { en: "gain", cn: "获得；赢得；收益", phonetic: "/ɡeɪn/", spell: false },
        { en: "puzzled", cn: "困惑的；迷惑的", phonetic: "/ˈpʌzld/", spell: false },
        { en: "minor", cn: "较少的；次要的", phonetic: "/ˈmaɪnə(r)/", spell: false },
        { en: "monthly", cn: "每月的；月刊的；月刊", phonetic: "/ˈmʌnθli/", spell: false },
        { en: "injure", cn: "伤害；损害", phonetic: "/ɪnˈdʒə(r)/", spell: false },
        { en: "campaign", cn: "战役；活动；发起运动", phonetic: "/kæmˈpeɪn/", spell: false },
        { en: "performer", cn: "表演者；演出者", phonetic: "/pəˈfɔːmə(r)/", spell: false },
        { en: "sharp", cn: "锋利的；敏锐的", phonetic: "/ʃɑːp/", spell: false },
        { en: "shortly", cn: "不久；立刻", phonetic: "/ˈʃɔːtli/", spell: false },
        { en: "quantity", cn: "数量", phonetic: "/ˈkwɒntəti/", spell: false },
        { en: "image", cn: "形象；图像；影像", phonetic: "/ˈɪmɪdʒ/", spell: false },
        { en: "sailor", cn: "水手；海员", phonetic: "/ˈseɪlə(r)/", spell: false },
        { en: "steady", cn: "稳定的；平稳的", phonetic: "/ˈstedi/", spell: false }
    ],

    "1级 Unit 3": [
        { en: "flame", cn: "火焰；火苗", phonetic: "/fleɪm/", spell: false },
        { en: "headmaster", cn: "（中小学）校长", phonetic: "/ˈhedmɑːstə(r)/", spell: false },
        { en: "embarrassed", cn: "尴尬的；窘迫的", phonetic: "/ɪmˈbærəst/", spell: false },
        { en: "officially", cn: "官方地；正式地", phonetic: "/əˈfɪʃli/", spell: false },
        { en: "pumpkin", cn: "南瓜", phonetic: "/ˈpʌmpkɪn/", spell: false },
        { en: "permission", cn: "允许；许可", phonetic: "/pəˈmɪʃn/", spell: false },
        { en: "performance", cn: "表演；表现；业绩", phonetic: "/pəˈfɔːməns/", spell: false },
        { en: "bent", cn: "弯曲的；（bend过去式）弯曲", phonetic: "/bent/", spell: false },
        { en: "detective", cn: "侦探", phonetic: "/dɪˈtektɪv/", spell: false },
        { en: "anyhow", cn: "无论如何；不管怎样", phonetic: "/ˈenihaʊ/", spell: false },
        { en: "curtain", cn: "窗帘；幕布", phonetic: "/ˈkɜːtn/", spell: false },
        { en: "disadvantage", cn: "不利因素；缺点", phonetic: "/ˌdɪsədˈvɑːntɪdʒ/", spell: false },
        { en: "exit", cn: "出口；通道；离开", phonetic: "/ˈeɡzɪt/", spell: false },
        { en: "timetable", cn: "时间表；课程表", phonetic: "/ˈtaɪmteɪbl/", spell: false },
        { en: "brief", cn: "简短的；简洁的", phonetic: "/briːf/", spell: false },
        { en: "salty", cn: "含盐的；咸的", phonetic: "/ˈsɔːlti/", spell: false },
        { en: "fare", cn: "车费；票价；费用", phonetic: "/feə(r)/", spell: false },
        { en: "incident", cn: "事件；事变", phonetic: "/ˈɪnsɪdənt/", spell: false },
        { en: "branch", cn: "分支；树枝；分部", phonetic: "/brɑːntʃ/", spell: false },
        { en: "neighbour", cn: "邻居（美式neighbor）", phonetic: "/ˈneɪbə(r)/", spell: false },
        { en: "frightened", cn: "受惊的；害怕的", phonetic: "/ˈfraɪtnd/", spell: false },
        { en: "fortunate", cn: "幸运的", phonetic: "/ˈfɔːtʃənət/", spell: false },
        { en: "outer", cn: "外部的；外表的", phonetic: "/ˈaʊtə(r)/", spell: false },
        { en: "forecast", cn: "预报；预测", phonetic: "/ˈfɔːkɑːst/", spell: false },
        { en: "phrase", cn: "短语；词组", phonetic: "/freɪz/", spell: false },
        { en: "committee", cn: "委员会", phonetic: "/kəˈmɪti/", spell: false },
        { en: "rapid", cn: "快速的；迅速的", phonetic: "/ˈræpɪd/", spell: false },
        { en: "revolution", cn: "革命；变革", phonetic: "/ˌrevəˈluːʃn/", spell: false }
    ],

    "1级 Unit 4": [
        { en: "observatory", cn: "天文台；观测台", phonetic: "/əbˈzɜːvətri/", spell: false },
        { en: "recommendation", cn: "推荐；建议", phonetic: "/ˌrekəmenˈdeɪʃn/", spell: false },
        { en: "hunger", cn: "饥饿；渴望", phonetic: "/ˈhʌŋɡə(r)/", spell: false },
        { en: "critical", cn: "批评的；关键的；危急的", phonetic: "/ˈkrɪtɪkl/", spell: false },
        { en: "agent", cn: "代理人；代理商", phonetic: "/ˈeɪdʒənt/", spell: false },
        { en: "movement", cn: "动作；移动；运动", phonetic: "/ˈmuːvmənt/", spell: false },
        { en: "have an effect on", cn: "对……有影响", phonetic: "/hæv ən ɪˈfekt ɒn/", spell: false },
        { en: "curve", cn: "曲线；弯曲；弯曲", phonetic: "/kɜːv/", spell: false },
        { en: "troublesome", cn: "令人烦恼的；麻烦的", phonetic: "/ˈtrʌblsm/", spell: false },
        { en: "origin", cn: "来源；起源；出身", phonetic: "/ˈɒrɪdʒɪn/", spell: false },
        { en: "requirement", cn: "需要；必需品；要求", phonetic: "/rɪˈkwaɪəmənt/", spell: false },
        { en: "advertise", cn: "做广告；宣传", phonetic: "/ˈædvətaɪz/", spell: false },
        { en: "laboratory", cn: "实验室（简写lab）", phonetic: "/ləˈbɒrətri/", spell: false },
        { en: "comrade", cn: "同志；伙伴", phonetic: "/ˈkɒmreɪd/", spell: false },
        { en: "convert", cn: "转换；转变", phonetic: "/kənˈvɜːt/", spell: false },
        { en: "tutor", cn: "导师；家庭教师", phonetic: "/ˈtjuːtə(r)/", spell: false },
        { en: "chapter", cn: "章；篇；回", phonetic: "/ˈtʃæptə(r)/", spell: false },
        { en: "climate", cn: "气候", phonetic: "/ˈklaɪmət/", spell: false },
        { en: "narrow", cn: "狭窄的；（使）变窄", phonetic: "/ˈnærəʊ/", spell: false },
        { en: "issue", cn: "议题；问题；发布；发行", phonetic: "/ˈɪʃuː/", spell: false },
        { en: "pole", cn: "杆；极地；极点", phonetic: "/pəʊl/", spell: false },
        { en: "overtake", cn: "赶上；超过", phonetic: "/ˌəʊvəˈteɪk/", spell: false },
        { en: "dormitory", cn: "宿舍（简写dorm）", phonetic: "/ˈdɔːmətri/", spell: false },
        { en: "cautious", cn: "谨慎的；小心的", phonetic: "/ˈkɔːʃəs/", spell: false },
        { en: "attempt", cn: "尝试；试图", phonetic: "/əˈtempt/", spell: false },
        { en: "react", cn: "反应；作出回应", phonetic: "/riˈækt/", spell: false },
        { en: "apply", cn: "申请；应用", phonetic: "/əˈplaɪ/", spell: false },
        { en: "adorable", cn: "可爱的；讨人喜爱的", phonetic: "/əˈdɔːrəbl/", spell: false }
    ],

    "1级 Unit 5": [
        { en: "collective", cn: "集体的；共同的；集体", phonetic: "/kəˈlektɪv/", spell: false },
        { en: "canteen", cn: "食堂；餐厅", phonetic: "/kænˈtiːn/", spell: false },
        { en: "ashamed", cn: "感到羞愧的；惭愧的", phonetic: "/əˈʃeɪmd/", spell: false },
        { en: "application", cn: "申请；应用", phonetic: "/ˌæplɪˈkeɪʃn/", spell: false },
        { en: "identity", cn: "身份；特征", phonetic: "/aɪˈdentəti/", spell: false },
        { en: "failure", cn: "失败；故障", phonetic: "/ˈfeɪljə(r)/", spell: false },
        { en: "harmless", cn: "无害的", phonetic: "/ˈhɑːmləs/", spell: false },
        { en: "informative", cn: "提供信息的；增长见闻的", phonetic: "/ɪnˈfɔːmətɪv/", spell: false },
        { en: "broom", cn: "扫帚", phonetic: "/bruːm/", spell: false },
        { en: "oppose", cn: "反对；反抗", phonetic: "/əˈpəʊz/", spell: false },
        { en: "unable", cn: "不能的；无法的", phonetic: "/ʌnˈeɪbl/", spell: false },
        { en: "contribute", cn: "贡献；捐献；投稿", phonetic: "/kənˈtrɪbjuːt/", spell: false },
        { en: "escalator", cn: "自动扶梯", phonetic: "/ˈeskəleɪtə(r)/", spell: false },
        { en: "get across", cn: "传达；使理解", phonetic: "/ɡet əˈkrɒs/", spell: false },
        { en: "essential", cn: "必要的；极其重要的", phonetic: "/ɪˈsenʃl/", spell: false },
        { en: "microscope", cn: "显微镜", phonetic: "/ˈmaɪkrəskəʊp/", spell: false },
        { en: "ban", cn: "禁止；禁令", phonetic: "/bæn/", spell: false },
        { en: "decade", cn: "十年；十年期", phonetic: "/ˈdekeɪd/", spell: false },
        { en: "comedy", cn: "喜剧；喜剧片", phonetic: "/ˈkɒmədi/", spell: false },
        { en: "resource", cn: "资源；财力", phonetic: "/rɪˈsɔːs/", spell: false },
        { en: "disqualify", cn: "取消……资格；使不合格", phonetic: "/dɪsˈkwɒlɪfaɪ/", spell: false },
        { en: "sincerity", cn: "真诚；诚挚", phonetic: "/sɪnˈserəti/", spell: false },
        { en: "archaeology", cn: "考古学", phonetic: "/ˌɑːkiˈɒlədʒi/", spell: false },
        { en: "complex", cn: "复杂的；综合体", phonetic: "/ˈkɒmpleks/", spell: false },
        { en: "survival", cn: "生存；幸存", phonetic: "/səˈvaɪvl/", spell: false },
        { en: "properly", cn: "适当地；正确地", phonetic: "/ˈprɒpəli/", spell: false },
        { en: "earn", cn: "赚得；挣得；赢得", phonetic: "/ɜːn/", spell: false },
        { en: "best-seller", cn: "畅销书；畅销品", phonetic: "/ˌbest ˈselə(r)/", spell: false }
    ],

    "1级 Unit 6": [
        { en: "parade", cn: "游行；阅兵；列队行进", phonetic: "/pəˈreɪd/", spell: false },
        { en: "shuttle", cn: "穿梭班车；航天飞机", phonetic: "/ˈʃʌtl/", spell: false },
        { en: "legal", cn: "法律的；合法的", phonetic: "/ˈliːɡl/", spell: false },
        { en: "switch", cn: "切换；转换；开关", phonetic: "/swɪtʃ/", spell: false },
        { en: "parent", cn: "父母；亲本", phonetic: "/ˈpeərənt/", spell: false },
        { en: "reality", cn: "现实；真实", phonetic: "/riˈæləti/", spell: false },
        { en: "wedding", cn: "婚礼", phonetic: "/ˈwedɪŋ/", spell: false },
        { en: "marine", cn: "海洋的；海生的", phonetic: "/məˈriːn/", spell: false },
        { en: "preview", cn: "预习；预告；预览", phonetic: "/ˈpriːvjuː/", spell: false },
        { en: "emergency", cn: "紧急情况；突发事件", phonetic: "/ɪˈmɜːdʒənsi/", spell: false },
        { en: "violence", cn: "暴力；猛烈", phonetic: "/ˈvaɪələns/", spell: false },
        { en: "persuade", cn: "说服；劝说", phonetic: "/pəˈsweɪd/", spell: false },
        { en: "literature", cn: "文学；文献", phonetic: "/ˈlɪtrətʃə(r)/", spell: false },
        { en: "let down", cn: "使失望；放下", phonetic: "/let daʊn/", spell: false },
        { en: "recover", cn: "恢复；康复；找回", phonetic: "/rɪˈkʌvə(r)/", spell: false },
        { en: "troop", cn: "部队；一群人", phonetic: "/truːp/", spell: false },
        { en: "arrangement", cn: "安排；筹备", phonetic: "/əˈreɪndʒmənt/", spell: false },
        { en: "promote", cn: "促进；提升；推广", phonetic: "/prəˈməʊt/", spell: false },
        { en: "pause", cn: "暂停；中止", phonetic: "/pɔːz/", spell: false },
        { en: "adventure", cn: "冒险；奇遇", phonetic: "/ədˈventʃə(r)/", spell: false },
        { en: "defect", cn: "缺陷；缺点", phonetic: "/ˈdiːfekt/", spell: false },
        { en: "disguise", cn: "伪装；掩饰", phonetic: "/dɪsˈɡaɪz/", spell: false },
        { en: "arithmetic", cn: "算术", phonetic: "/əˈrɪθmətɪk/", spell: false },
        { en: "appointment", cn: "约会；预约；任命", phonetic: "/əˈpɔɪntmənt/", spell: false },
        { en: "expectation", cn: "期待；预期", phonetic: "/ˌekspekˈteɪʃn/", spell: false },
        { en: "businessman", cn: "商人", phonetic: "/ˈbɪznəsmæn/", spell: false },
        { en: "explore", cn: "探索；探究；考察", phonetic: "/ɪkˈsplɔː(r)/", spell: false },
        { en: "significantly", cn: "显著地；值得注意地", phonetic: "/sɪɡˈnɪfikəntli/", spell: false }
    ],

    "1级 Unit 7": [
        { en: "absorb", cn: "吸收；吸引；理解", phonetic: "/əbˈsɔːb/", spell: false },
        { en: "statesman", cn: "政治家", phonetic: "/ˈsteɪtsmən/", spell: false },
        { en: "majority", cn: "大多数；大部分", phonetic: "/məˈdʒɒrəti/", spell: false },
        { en: "principle", cn: "原理；原则；准则", phonetic: "/ˈprɪnsəpl/", spell: false },
        { en: "essay", cn: "散文；短文", phonetic: "/ˈeseɪ/", spell: false },
        { en: "lack", cn: "缺乏；缺少", phonetic: "/læk/", spell: false },
        { en: "urban", cn: "城市的；都市的", phonetic: "/ˈɜːbən/", spell: false },
        { en: "flourish", cn: "繁荣；蓬勃发展；茂盛生长", phonetic: "/ˈflʌrɪʃ/", spell: false },
        { en: "frontier", cn: "边界；边境；前沿", phonetic: "/ˈfrʌntɪə(r)/", spell: false },
        { en: "editor", cn: "编辑；编者", phonetic: "/ˈedɪtə(r)/", spell: false },
        { en: "battle", cn: "战役；战斗；搏斗", phonetic: "/ˈbætl/", spell: false },
        { en: "worldwide", cn: "全世界的（地）", phonetic: "/ˈwɜːldwaɪd/", spell: false },
        { en: "attractive", cn: "迷人的；有吸引力的", phonetic: "/əˈtræktɪv/", spell: false },
        { en: "thanks to", cn: "多亏；由于", phonetic: "/θæŋks tuː/", spell: false },
        { en: "dock", cn: "码头；船坞", phonetic: "/dɒk/", spell: false },
        { en: "shave", cn: "剃；刮（胡须）", phonetic: "/ʃeɪv/", spell: false },
        { en: "percentage", cn: "百分比；百分率", phonetic: "/pəˈsentɪdʒ/", spell: false },
        { en: "economy", cn: "经济；经济体；节约", phonetic: "/ɪˈkɒnəmi/", spell: false },
        { en: "cure", cn: "治愈；治疗；疗法", phonetic: "/kjʊə(r)/", spell: false },
        { en: "generally", cn: "普遍地；一般地", phonetic: "/ˈdʒenrəli/", spell: false },
        { en: "memorise", cn: "记住；熟记（美式memorize）", phonetic: "/ˈmeməraɪz/", spell: false },
        { en: "weave", cn: "编织；编造", phonetic: "/wiːv/", spell: false },
        { en: "geometry", cn: "几何学", phonetic: "/dʒiˈɒmətri/", spell: false },
        { en: "anxiety", cn: "焦虑；担忧", phonetic: "/æŋˈzaɪəti/", spell: false },
        { en: "bacteria", cn: "细菌（复数）", phonetic: "/bækˈtɪəriə/", spell: false },
        { en: "charity", cn: "慈善；慈善机构；施舍", phonetic: "/ˈtʃærəti/", spell: false },
        { en: "opportunity", cn: "机会；时机", phonetic: "/ˌɒpəˈtjuːnəti/", spell: false },
        { en: "help out", cn: "帮助（某人）摆脱困境", phonetic: "help aʊt/", spell: false }
    ],

    "1级 Unit 8": [
        { en: "gymnastic", cn: "体操的；体育的", phonetic: "/dʒɪmˈnæstɪk/", spell: false },
        { en: "choke", cn: "窒息；堵塞；哽住", phonetic: "/tʃəʊk/", spell: false },
        { en: "original", cn: "最初的；原始的；原创的", phonetic: "/əˈrɪdʒənl/", spell: false },
        { en: "ongoing", cn: "进行中的；正在发展的", phonetic: "/ˈɒnɡəʊɪŋ/", spell: false },
        { en: "indicate", cn: "指出；表明；象征", phonetic: "/ˈɪndɪkeɪt/", spell: false },
        { en: "surround", cn: "包围；围绕", phonetic: "/səˈraʊnd/", spell: false },
        { en: "Confucius", cn: "孔子", phonetic: "/kənˈfjuːʃəs/", spell: false },
        { en: "devote", cn: "奉献；致力于", phonetic: "/dɪˈvəʊt/", spell: false },
        { en: "apron", cn: "围裙", phonetic: "/ˈeɪprən/", spell: false },
        { en: "relate", cn: "联系；讲述", phonetic: "/rɪˈleɪt/", spell: false },
        { en: "obstacle", cn: "障碍；阻碍", phonetic: "/ˈɒbstəkl/", spell: false },
        { en: "pace", cn: "步伐；速度；节奏", phonetic: "/peɪs/", spell: false },
        { en: "replace", cn: "代替；取代；更换", phonetic: "/rɪˈpleɪs/", spell: false },
        { en: "slope", cn: "斜坡；坡度", phonetic: "/sləʊp/", spell: false },
        { en: "arch", cn: "拱门；拱形结构", phonetic: "/ɑːtʃ/", spell: false },
        { en: "formal", cn: "正式的；形式的", phonetic: "/ˈfɔːml/", spell: false },
        { en: "justice", cn: "正义；公正；司法", phonetic: "/ˈdʒʌstɪs/", spell: false },
        { en: "announce", cn: "宣布；宣告", phonetic: "/əˈnaʊns/", spell: false },
        { en: "limit", cn: "限制；限度", phonetic: "/ˈlɪmɪt/", spell: false },
        { en: "unfold", cn: "展开；显露；展现", phonetic: "/ʌnˈfəʊld/", spell: false },
        { en: "despair", cn: "绝望", phonetic: "/dɪˈspeə(r)/", spell: false },
        { en: "equipment", cn: "设备；装备（不可数名词）", phonetic: "/ɪˈkwɪpmənt/", spell: false },
        { en: "debate", cn: "争论；辩论", phonetic: "/dɪˈbeɪt/", spell: false },
        { en: "access", cn: "通道；机会；使用权；访问", phonetic: "/ˈækses/", spell: false },
        { en: "dive", cn: "跳水；潜水；俯冲", phonetic: "/daɪv/", spell: false },
        { en: "various", cn: "各种各样的", phonetic: "/ˈveəriəs/", spell: false },
        { en: "attentively", cn: "专注地；认真地", phonetic: "/əˈtentɪvli/", spell: false },
        { en: "in panic", cn: "惊慌地", phonetic: "ɪn ˈpænɪk/", spell: false }
    ],

    "1级 Unit 9": [
        { en: "tender", cn: "嫩的；温柔的；脆弱的", phonetic: "/ˈtendə(r)/", spell: false },
        { en: "premier", cn: "首要的；第一的；总理；首相", phonetic: "/ˈpremiə(r)/", spell: false },
        { en: "tight", cn: "紧的；紧绷的", phonetic: "/taɪt/", spell: false },
        { en: "former", cn: "以前的；从前的", phonetic: "/ˈfɔːmə(r)/", spell: false },
        { en: "disappointed", cn: "失望的；沮丧的", phonetic: "/ˌdɪsˈpɔɪntɪd/", spell: false },
        { en: "figure", cn: "数字；人物；身材；图形；认为", phonetic: "/ˈfɪɡə(r)/", spell: false },
        { en: "headphones", cn: "（复数）耳机", phonetic: "/ˈhedfəʊnz/", spell: false },
        { en: "strait", cn: "海峡", phonetic: "/streɪt/", spell: false },
        { en: "butcher", cn: "屠夫；肉贩；屠宰", phonetic: "/ˈbʊtʃə(r)/", spell: false },
        { en: "adjust", cn: "调整；调节；适应", phonetic: "/əˈdʒʌst/", spell: false },
        { en: "poetry", cn: "诗歌（总称，不可数）", phonetic: "/ˈpəʊətri/", spell: false },
        { en: "associate", cn: "联系；联想；交往", phonetic: "/əˈsəʊʃieɪt/", spell: false },
        { en: "unique", cn: "独一无二的；独特的", phonetic: "/juːˈniːk/", spell: false },
        { en: "gateway", cn: "大门；通道；途径", phonetic: "/ˈɡeɪtweɪ/", spell: false },
        { en: "cable", cn: "电缆；电报；线缆", phonetic: "/ˈkeɪbl/", spell: false },
        { en: "wrinkled", cn: "有皱纹的", phonetic: "/ˈrɪŋkld/", spell: false },
        { en: "administration", cn: "管理；行政部门", phonetic: "/ədˌmɪnɪˈstreɪʃn/", spell: false },
        { en: "channel", cn: "渠道；频道；海峡", phonetic: "/ˈtʃænl/", spell: false },
        { en: "positive", cn: "正面的；积极的；阳性的", phonetic: "/ˈpɒzətɪv/", spell: false },
        { en: "calm", cn: "镇静的；平静的；使冷静", phonetic: "/kɑːm/", spell: false },
        { en: "unfamiliar", cn: "不熟悉的；陌生的", phonetic: "/ʌnfəˈmɪliə(r)/", spell: false },
        { en: "humble", cn: "卑微的；谦逊的", phonetic: "/ˈhʌmbl/", spell: false },
        { en: "improvement", cn: "改进；改善", phonetic: "/ɪmˈpruːvmənt/", spell: false },
        { en: "gallery", cn: "画廊；美术馆", phonetic: "/ˈɡæləri/", spell: false },
        { en: "crime", cn: "罪行；犯罪", phonetic: "/kraɪm/", spell: false },
        { en: "potential", cn: "潜在的；潜力", phonetic: "/pəˈtenʃl/", spell: false },
        { en: "benefit", cn: "利益，好处；有益于", phonetic: "/ˈbenɪfɪt/", spell: false },
        { en: "live up to", cn: "符合；不辜负（期望）", phonetic: "/lɪv ʌp tuː/", spell: false }
    ]

};
