var wordBank = wordBank || {};

wordBank["词库 B2 级"] = {

    "Unit 1": [
        // 只认读（英译中）
        { en: "discussion", cn: "讨论", phonetic: "/dɪˈskʌʃn/", spell: false },
        { en: "nation", cn: "国家，民族", phonetic: "/ˈneɪʃn/", spell: false },
        { en: "born", cn: "出生", phonetic: "/bɔːn/", spell: false },
        { en: "flash", cn: "闪光；闪现", phonetic: "/flæʃ/", spell: false },
        { en: "outdoor", cn: "户外的", phonetic: "/ˈaʊtdɔː(r)/", spell: false },
        { en: "northern", cn: "北方的", phonetic: "/ˈnɔːðən/", spell: false },
        { en: "website", cn: "网站", phonetic: "/ˈwebsaɪt/", spell: false },
        { en: "mad", cn: "生气的；疯狂的", phonetic: "/mæd/", spell: false },
        { en: "trade", cn: "贸易", phonetic: "/treɪd/", spell: false },
        { en: "towards", cn: "朝向", phonetic: "/təˈwɔːdz/", spell: false },
        { en: "low", cn: "低的", phonetic: "/ləʊ/", spell: false },
        { en: "German", cn: "德国人，德语", phonetic: "/ˈdʒɜːmən/", spell: false },
        { en: "childhood", cn: "童年", phonetic: "/ˈtʃaɪldhʊd/", spell: false },
        { en: "simply", cn: "仅仅；简单地", phonetic: "/ˈsɪmpli/", spell: false },
        { en: "degree", cn: "度；程度；学位", phonetic: "/dɪˈɡriː/", spell: false },
        { en: "musician", cn: "音乐家", phonetic: "/mjuˈzɪʃn/", spell: false },
        { en: "frog", cn: "青蛙", phonetic: "/frɒɡ/", spell: false },
        { en: "spread", cn: "传播", phonetic: "/spred/", spell: false },
        { en: "final", cn: "最终的；决赛", phonetic: "/ˈfaɪnl/", spell: false },
        { en: "scene", cn: "场景", phonetic: "/siːn/", spell: false },
        { en: "earthquake", cn: "地震", phonetic: "/ˈɜːθkweɪk/", spell: false },
        { en: "airplane", cn: "飞机", phonetic: "/ˈeəpleɪn/", spell: false },
        { en: "remind", cn: "提醒", phonetic: "/rɪˈmaɪnd/", spell: false },
        { en: "effort", cn: "努力", phonetic: "/ˈefət/", spell: false },
        { en: "coach", cn: "教练", phonetic: "/kəʊtʃ/", spell: false },
        { en: "primary", cn: "首要的；初级的；小学的", phonetic: "/ˈpraɪməri/", spell: false },
        { en: "repeat", cn: "重复", phonetic: "/rɪˈpiːt/", spell: false },
        { en: "society", cn: "社会", phonetic: "/səˈsaɪəti/", spell: false }
    ],

    "Unit 2": [
        { en: "enemy", cn: "敌人", phonetic: "/ˈenəmi/", spell: false },
        { en: "lock", cn: "锁", phonetic: "/lɒk/", spell: false },
        { en: "corn", cn: "玉米", phonetic: "/kɔːn/", spell: false },
        { en: "basic", cn: "基础的", phonetic: "/ˈbeɪsɪk/", spell: false },
        { en: "ugly", cn: "丑陋的", phonetic: "/ˈʌɡli/", spell: false },
        { en: "tower", cn: "塔", phonetic: "/ˈtaʊə(r)/", spell: false },
        { en: "alive", cn: "活着的", phonetic: "/əˈlaɪv/", spell: false },
        { en: "available", cn: "可获得的；有空的", phonetic: "/əˈveɪləbl/", spell: false },
        { en: "protection", cn: "保护，防护", phonetic: "/prəˈtekʃn/", spell: false },
        { en: "president", cn: "总统", phonetic: "/ˈprezɪdənt/", spell: false },
        { en: "refer to", cn: "参考；涉及；指的是", phonetic: "/rɪˈfɜː(r) tuː/", spell: false },
        { en: "immediately", cn: "立刻", phonetic: "/ɪˈmiːdiətli/", spell: false },
        { en: "itself", cn: "它自己", phonetic: "/ɪtˈself/", spell: false },
        { en: "nor", cn: "也不", phonetic: "/nɔː(r)/", spell: false },
        { en: "electronic", cn: "电子的", phonetic: "/ɪˌlekˈtrɒnɪk/", spell: false },
        { en: "industry", cn: "行业；工业", phonetic: "/ˈɪndəstri/", spell: false },
        { en: "till", cn: "直到……为止", phonetic: "/tɪl/", spell: false },
        { en: "confident", cn: "自信的", phonetic: "/ˈkɒnfɪdənt/", spell: false },
        { en: "agreement", cn: "同意，协议", phonetic: "/əˈɡriːmənt/", spell: false },
        { en: "nearby", cn: "在附近", phonetic: "/ˌnɪəˈbaɪ/", spell: false },
        { en: "gas", cn: "煤气，气体", phonetic: "/ɡæs/", spell: false },
        { en: "doubt", cn: "怀疑；疑惑", phonetic: "/daʊt/", spell: false },
        { en: "afford", cn: "负担得起", phonetic: "/əˈfɔːd/", spell: false },
        { en: "physical", cn: "物理的；身体的", phonetic: "/ˈfɪzɪkl/", spell: false },
        { en: "survey", cn: "调查；测量", phonetic: "/ˈsɜːveɪ/", spell: false },
        { en: "organization", cn: "组织", phonetic: "/ˌɔːɡənaɪˈzeɪʃn/", spell: false },
        { en: "boss", cn: "老板", phonetic: "/bɒs/", spell: false },
        { en: "law", cn: "法律", phonetic: "/lɔː/", spell: false }
    ],

    "Unit 3": [
        { en: "underground", cn: "地下的；地铁", phonetic: "/ˈʌndəɡraʊnd/", spell: false },
        { en: "method", cn: "方法", phonetic: "/ˈmeθəd/", spell: false },
        { en: "attend", cn: "参加，出席", phonetic: "/əˈtend/", spell: false },
        { en: "fashion", cn: "时尚", phonetic: "/ˈfæʃn/", spell: false },
        { en: "crowd", cn: "人群；拥挤", phonetic: "/kraʊd/", spell: false },
        { en: "file", cn: "文件；档案", phonetic: "/faɪl/", spell: false },
        { en: "anybody", cn: "任何人", phonetic: "/ˈenibɒdi/", spell: false },
        { en: "wine", cn: "酒", phonetic: "/waɪn/", spell: false },
        { en: "nowadays", cn: "当今", phonetic: "/ˈnaʊədeɪz/", spell: false },
        { en: "apartment", cn: "公寓", phonetic: "/əˈpɑːtmənt/", spell: false },
        { en: "metal", cn: "金属", phonetic: "/ˈmetl/", spell: false },
        { en: "manage", cn: "管理", phonetic: "/ˈmænɪdʒ/", spell: false },
        { en: "cancel", cn: "取消", phonetic: "/ˈkænsl/", spell: false },
        { en: "importance", cn: "重要性", phonetic: "/ɪmˈpɔːtns/", spell: false },
        { en: "period", cn: "一段时间；时期", phonetic: "/ˈpɪəriəd/", spell: false },
        { en: "stomach", cn: "胃", phonetic: "/ˈstʌmək/", spell: false },
        { en: "director", cn: "导演；主管", phonetic: "/dɪˈrektə(r)/", spell: false },
        { en: "valuable", cn: "有价值的", phonetic: "/ˈvæljuəbl/", spell: false },
        { en: "church", cn: "教堂", phonetic: "/tʃɜːtʃ/", spell: false },
        { en: "southern", cn: "南方的", phonetic: "/ˈsʌðən/", spell: false },
        { en: "percent", cn: "百分之", phonetic: "/pəˈsent/", spell: false },
        { en: "desert", cn: "沙漠", phonetic: "/ˈdezət/", spell: false },
        { en: "amount", cn: "数量", phonetic: "/əˈmaʊnt/", spell: false },
        { en: "board", cn: "上（船/飞机/火车等）；木板", phonetic: "/bɔːd/", spell: false },
        { en: "service", cn: "服务", phonetic: "/ˈsɜːvɪs/", spell: false },
        { en: "couple", cn: "一对；夫妇；几个", phonetic: "/ˈkʌpl/", spell: false },
        { en: "badly", cn: "严重地；非常", phonetic: "/ˈbædli/", spell: false },
        { en: "trust", cn: "信任", phonetic: "/trʌst/", spell: false }
    ],

    "Unit 4": [
        { en: "forgetful", cn: "健忘的", phonetic: "/fəˈɡetfl/", spell: false },
        { en: "citizen", cn: "公民", phonetic: "/ˈsɪtɪzn/", spell: false },
        { en: "glue", cn: "胶水；粘贴", phonetic: "/ɡluː/", spell: false },
        { en: "risk", cn: "风险", phonetic: "/rɪsk/", spell: false },
        { en: "rubbish", cn: "垃圾", phonetic: "/ˈrʌbɪʃ/", spell: false },
        { en: "allow", cn: "允许", phonetic: "/əˈlaʊ/", spell: false },
        { en: "VR", cn: "虚拟现实", phonetic: "/ˌviː ˈɑː(r)/", spell: false },
        { en: "caring", cn: "体贴的", phonetic: "/ˈkeərɪŋ/", spell: false },
        { en: "pride", cn: "骄傲，自豪", phonetic: "/praɪd/", spell: false },
        { en: "private", cn: "私人的", phonetic: "/ˈpraɪvət/", spell: false },
        { en: "actress", cn: "女演员", phonetic: "/ˈæktrəs/", spell: false },
        { en: "warn", cn: "警告", phonetic: "/wɔːn/", spell: false },
        { en: "speaker", cn: "发言者", phonetic: "/ˈspiːkə(r)/", spell: false },
        { en: "best-selling", cn: "畅销", phonetic: "/ˌbest ˈselɪŋ/", spell: false },
        { en: "kangaroo", cn: "袋鼠", phonetic: "/ˌkæŋɡəˈruː/", spell: false },
        { en: "exhibition", cn: "展览", phonetic: "/ˌeksɪˈbɪʃn/", spell: false },
        { en: "elder", cn: "年长的", phonetic: "/ˈeldə(r)/", spell: false },
        { en: "discovery", cn: "发现", phonetic: "/dɪˈskʌvəri/", spell: false },
        { en: "sometime", cn: "某一时刻", phonetic: "/ˈsʌmtaɪm/", spell: false },
        { en: "college", cn: "大学，学院", phonetic: "/ˈkɒlɪdʒ/", spell: false },
        { en: "PRC", cn: "中华人民共和国", phonetic: "/ˌpiː ɑːr ˈsiː/", spell: false },
        { en: "site", cn: "地点；场所；网站", phonetic: "/saɪt/", spell: false },
        { en: "contribution", cn: "贡献", phonetic: "/ˌkɒntrɪˈbjuːʃn/", spell: false },
        { en: "fee", cn: "费", phonetic: "/fiː/", spell: false },
        { en: "experiment", cn: "实验", phonetic: "/ɪkˈsperɪmənt/", spell: false },
        { en: "saw", cn: "锯；锯子（see的过去式）", phonetic: "/sɔː/", spell: false },
        { en: "include", cn: "包括", phonetic: "/ɪnˈkluːd/", spell: false },
        { en: "re", cn: "关于，事由", phonetic: "/reɪ/", spell: false }
    ],

    "Unit 5": [
        { en: "sweetness", cn: "甜蜜；可爱", phonetic: "/ˈswiːtnəs/", spell: false },
        { en: "congratulate", cn: "祝贺", phonetic: "/kənˈɡrætʃuleɪt/", spell: false },
        { en: "measure", cn: "措施；测量", phonetic: "/ˈmeʒə(r)/", spell: false },
        { en: "mess", cn: "杂乱；混乱", phonetic: "/mes/", spell: false },
        { en: "pocket", cn: "口袋；把…放进口袋", phonetic: "/ˈpɒkɪt/", spell: false },
        { en: "develop", cn: "发展，开发", phonetic: "/dɪˈveləp/", spell: false },
        { en: "AI", cn: "人工智能", phonetic: "/ˌeɪ ˈaɪ/", spell: false },
        { en: "riddle", cn: "谜语", phonetic: "/ˈrɪdl/", spell: false },
        { en: "anxious", cn: "忧虑的", phonetic: "/ˈæŋkʃəs/", spell: false },
        { en: "steel", cn: "钢", phonetic: "/stiːl/", spell: false },
        { en: "net", cn: "网", phonetic: "/net/", spell: false },
        { en: "listener", cn: "倾听者", phonetic: "/ˈlɪsənə(r)/", spell: false },
        { en: "accident", cn: "事故", phonetic: "/ˈæksɪdənt/", spell: false },
        { en: "ice cream", cn: "冰激凌", phonetic: "/ˌaɪs ˈkriːm/", spell: false },
        { en: "tiring", cn: "使人疲惫的", phonetic: "/ˈtaɪərɪŋ/", spell: false },
        { en: "apologize", cn: "道歉", phonetic: "/əˈpɒlədʒaɪz/", spell: false },
        { en: "chain", cn: "链子", phonetic: "/tʃeɪn/", spell: false },
        { en: "background", cn: "背景", phonetic: "/ˈbækɡraʊnd/", spell: false },
        { en: "photograph", cn: "照片；拍照", phonetic: "/ˈfəʊtəɡrɑːf/", spell: false },
        { en: "African", cn: "非洲的；非洲人", phonetic: "/ˈæfrɪkən/", spell: false },
        { en: "wisely", cn: "明智地；充满智慧地", phonetic: "/ˈwaɪzli/", spell: false },
        { en: "stormy", cn: "暴风雨的", phonetic: "/ˈstɔːmi/", spell: false },
        { en: "major", cn: "主要的", phonetic: "/ˈmeɪdʒə(r)/", spell: false },
        { en: "daytime", cn: "白天", phonetic: "/ˈdeɪtaɪm/", spell: false },
        { en: "effect", cn: "影响；效果", phonetic: "/ɪˈfekt/", spell: false },
        { en: "railway", cn: "铁路", phonetic: "/ˈreɪlweɪ/", spell: false },
        { en: "Olympic", cn: "奥林匹克的", phonetic: "/əˈlɪmpɪk/", spell: false },
        { en: "worry about", cn: "担心", phonetic: "/ˈwʌri əˈbaʊt/", spell: false }
    ],

    "Unit 6": [
        { en: "volunteer", cn: "志愿者", phonetic: "/ˌvɒlənˈtɪə(r)/", spell: false },
        { en: "overcome", cn: "克服", phonetic: "/ˌəʊvəˈkʌm/", spell: false },
        { en: "pianist", cn: "钢琴师", phonetic: "/ˈpiːənɪst/", spell: false },
        { en: "force", cn: "强迫", phonetic: "/fɔːs/", spell: false },
        { en: "cough", cn: "咳嗽", phonetic: "/kɒf/", spell: false },
        { en: "safety", cn: "安全；安全性", phonetic: "/ˈseɪfti/", spell: false },
        { en: "fortieth", cn: "第四十", phonetic: "/ˈfɔːtiəθ/", spell: false },
        { en: "honey", cn: "蜂蜜", phonetic: "/ˈhʌni/", spell: false },
        { en: "disagree", cn: "不同意", phonetic: "/ˌdɪsəˈɡriː/", spell: false },
        { en: "custom", cn: "习惯；风俗", phonetic: "/ˈkʌstəm/", spell: false },
        { en: "standard", cn: "标准", phonetic: "/ˈstændəd/", spell: false },
        { en: "scarf", cn: "围巾", phonetic: "/skɑːf/", spell: false },
        { en: "natural", cn: "天然的，自然的", phonetic: "/ˈnætʃrəl/", spell: false },
        { en: "kung fu", cn: "功夫", phonetic: "/ˌkʌŋ ˈfuː/", spell: false },
        { en: "goods", cn: "商品", phonetic: "/ɡʊdz/", spell: false },
        { en: "cycle", cn: "骑自行车；循环", phonetic: "/ˈsaɪkl/", spell: false },
        { en: "junior", cn: "初级的", phonetic: "/ˈdʒuːniə(r)/", spell: false },
        { en: "behave", cn: "表现；守规矩", phonetic: "/bɪˈheɪv/", spell: false },
        { en: "except", cn: "除……之外", phonetic: "/ɪkˈsept/", spell: false },
        { en: "perhaps", cn: "也许，可能", phonetic: "/pəˈhæps/", spell: false },
        { en: "depend", cn: "取决于", phonetic: "/dɪˈpend/", spell: false },
        { en: "editor", cn: "编辑", phonetic: "/ˈedɪtə(r)/", spell: false },
        { en: "preparation", cn: "准备", phonetic: "/ˌprepəˈreɪʃn/", spell: false },
        { en: "coast", cn: "海岸", phonetic: "/kəʊst/", spell: false },
        { en: "take away", cn: "拿走", phonetic: "/teɪk əˈweɪ/", spell: false },
        { en: "thick", cn: "厚的", phonetic: "/θɪk/", spell: false },
        { en: "communicate", cn: "交流", phonetic: "/kəˈmjuːnɪkeɪt/", spell: false },
        { en: "pay", cn: "付费；工资；报答", phonetic: "/peɪ/", spell: false }
    ],

    "Unit 7": [
        { en: "eventually", cn: "最终，最后", phonetic: "/ɪˈventʃuəli/", spell: false },
        { en: "lecture", cn: "演讲", phonetic: "/ˈlektʃə(r)/", spell: false },
        { en: "Germany", cn: "德国", phonetic: "/ˈdʒɜːməni/", spell: false },
        { en: "treatment", cn: "治疗", phonetic: "/ˈtriːtmənt/", spell: false },
        { en: "blank", cn: "空格；空白的", phonetic: "/blæŋk/", spell: false },
        { en: "interview", cn: "面试；采访", phonetic: "/ˈɪntəvjuː/", spell: false },
        { en: "headache", cn: "头痛", phonetic: "/ˈhedeɪk/", spell: false },
        { en: "technique", cn: "技巧，技术", phonetic: "/tekˈniːk/", spell: false },
        { en: "distance", cn: "距离", phonetic: "/ˈdɪstəns/", spell: false },
        { en: "madam", cn: "夫人", phonetic: "/ˈmædəm/", spell: false },
        { en: "eastern", cn: "东方的", phonetic: "/ˈiːstən/", spell: false },
        { en: "ache", cn: "疼痛", phonetic: "/eɪk/", spell: false },
        { en: "Africa", cn: "非洲", phonetic: "/ˈæfrɪkə/", spell: false },
        { en: "a lot of", cn: "许多", phonetic: "/ə ˈlɒt ɒv/", spell: false },
        { en: "responsible", cn: "有责任的", phonetic: "/rɪˈspɒnsəbl/", spell: false },
        { en: "take up", cn: "开始从事；占据（时间/空间）；拿起", phonetic: "/teɪk ˈʌp/", spell: false },
        { en: "freeze", cn: "结冰", phonetic: "/friːz/", spell: false },
        { en: "dig", cn: "挖；掘", phonetic: "/dɪɡ/", spell: false },
        { en: "drum", cn: "鼓", phonetic: "/drʌm/", spell: false },
        { en: "trouble", cn: "麻烦", phonetic: "/ˈtrʌbl/", spell: false },
        { en: "listen to", cn: "听", phonetic: "/ˈlɪsn tuː/", spell: false },
        { en: "lawyer", cn: "律师", phonetic: "/ˈlɔːjə(r)/", spell: false },
        { en: "secretary", cn: "秘书", phonetic: "/ˈsekrətri/", spell: false },
        { en: "steal", cn: "偷", phonetic: "/stiːl/", spell: false },
        { en: "shoot", cn: "射击", phonetic: "/ʃuːt/", spell: false },
        { en: "treasure", cn: "财富，宝藏", phonetic: "/ˈtreʒə(r)/", spell: false },
        { en: "cover", cn: "遮盖", phonetic: "/ˈkʌvə(r)/", spell: false },
        { en: "felt", cn: "感觉（feel的过去式）；毡", phonetic: "/felt/", spell: false }
    ],

    "Unit 8": [
        { en: "recent", cn: "最近", phonetic: "/ˈriːsnt/", spell: false },
        { en: "regular", cn: "规则的；正规的", phonetic: "/ˈreɡjələ(r)/", spell: false },
        { en: "X-ray", cn: "X射线", phonetic: "/ˈeks reɪ/", spell: false },
        { en: "smooth", cn: "光滑的", phonetic: "/smuːð/", spell: false },
        { en: "downstairs", cn: "在楼下；往楼下", phonetic: "/ˌdaʊnˈsteəz/", spell: false },
        { en: "pleasure", cn: "快乐", phonetic: "/ˈpleʒə(r)/", spell: false },
        { en: "take off", cn: "脱掉；起飞", phonetic: "/teɪk ˈɒf/", spell: false },
        { en: "agriculture", cn: "农业", phonetic: "/ˈæɡrɪkʌltʃə(r)/", spell: false },
        { en: "tip", cn: "提示；小费；给……小费", phonetic: "/tɪp/", spell: false },
        { en: "pardon", cn: "原谅", phonetic: "/ˈpɑːdn/", spell: false },
        { en: "policy", cn: "政策", phonetic: "/ˈpɒləsi/", spell: false },
        { en: "sour", cn: "酸的", phonetic: "/ˈsaʊə(r)/", spell: false },
        { en: "state", cn: "国家；状态", phonetic: "/steɪt/", spell: false },
        { en: "look at", cn: "看着", phonetic: "/lʊk æt/", spell: false },
        { en: "inspire", cn: "鼓舞", phonetic: "/ɪnˈspaɪə(r)/", spell: false },
        { en: "athlete", cn: "运动员", phonetic: "/ˈæθliːt/", spell: false },
        { en: "belong to", cn: "属于", phonetic: "/bɪˈlɒŋ tuː/", spell: false },
        { en: "sight", cn: "视力；景象；看见", phonetic: "/saɪt/", spell: false },
        { en: "seaside", cn: "海边", phonetic: "/ˈsiːsaɪd/", spell: false },
        { en: "death", cn: "死", phonetic: "/deθ/", spell: false },
        { en: "look for", cn: "寻找", phonetic: "/lʊk fɔː(r)/", spell: false },
        { en: "hunter", cn: "猎人", phonetic: "/ˈhʌntə(r)/", spell: false },
        { en: "bully", cn: "威胁；欺负", phonetic: "/ˈbʊli/", spell: false },
        { en: "condition", cn: "条件", phonetic: "/kənˈdɪʃn/", spell: false },
        { en: "Pacific", cn: "太平洋", phonetic: "/pəˈsɪfɪk/", spell: false },
        { en: "healthily", cn: "健康地", phonetic: "/ˈhelθɪli/", spell: false },
        { en: "fountain", cn: "喷泉", phonetic: "/ˈfaʊntən/", spell: false },
        { en: "hurry up", cn: "快点", phonetic: "/ˈhʌri ʌp/", spell: false }
    ],

    "Unit 9": [
        { en: "harm", cn: "伤害", phonetic: "/hɑːm/", spell: false },
        { en: "gentle", cn: "温和的", phonetic: "/ˈdʒentl/", spell: false },
        { en: "request", cn: "请求", phonetic: "/rɪˈkwest/", spell: false },
        { en: "proper", cn: "适当的", phonetic: "/ˈprɒpə(r)/", spell: false },
        { en: "think of", cn: "认为", phonetic: "/θɪŋk ɒv/", spell: false },
        { en: "gate", cn: "大门", phonetic: "/ɡeɪt/", spell: false },
        { en: "slow down", cn: "减速", phonetic: "/ˌsləʊ ˈdaʊn/", spell: false },
        { en: "eager", cn: "热切的", phonetic: "/ˈiːɡə(r)/", spell: false },
        { en: "Russia", cn: "俄罗斯", phonetic: "/ˈrʌʃə/", spell: false },
        { en: "engineering", cn: "工程学", phonetic: "/ˌendʒɪˈnɪərɪŋ/", spell: false },
        { en: "block", cn: "块；街区", phonetic: "/blɒk/", spell: false },
        { en: "government", cn: "政府", phonetic: "/ˈɡʌvənmənt/", spell: false },
        { en: "UN", cn: "联合国", phonetic: "/ˌjuː ˈen/", spell: false },
        { en: "point", cn: "观点；指向", phonetic: "/pɔɪnt/", spell: false },
        { en: "manner", cn: "举止；礼貌", phonetic: "/ˈmænə(r)/", spell: false },
        { en: "fiction", cn: "小说", phonetic: "/ˈfɪkʃn/", spell: false },
        { en: "on time", cn: "按时，准时", phonetic: "/ɒn taɪm/", spell: false },
        { en: "sunglasses", cn: "太阳镜", phonetic: "/ˈsʌnɡlɑːsɪz/", spell: false },
        { en: "western", cn: "西方的", phonetic: "/ˈwestən/", spell: false },
        { en: "personal", cn: "个人的", phonetic: "/ˈpɜːsənl/", spell: false },
        { en: "America", cn: "美国", phonetic: "/əˈmerɪkə/", spell: false },
        { en: "classic", cn: "经典的；最优秀的", phonetic: "/ˈklæsɪk/", spell: false },
        { en: "narrow", cn: "狭窄的", phonetic: "/ˈnærəʊ/", spell: false },
        { en: "backpack", cn: "背包", phonetic: "/ˈbækpæk/", spell: false },
        { en: "press", cn: "按；压", phonetic: "/pres/", spell: false },
        { en: "according", cn: "根据；依照（与to连用）", phonetic: "/əˈkɔːdɪŋ/", spell: false },
        { en: "peace", cn: "和平", phonetic: "/piːs/", spell: false },
        { en: "writer", cn: "作者，作家", phonetic: "/ˈraɪtə(r)/", spell: false }
    ],

    "Unit 10": [
        { en: "murder", cn: "谋杀", phonetic: "/ˈmɜːdə(r)/", spell: false },
        { en: "material", cn: "材料", phonetic: "/məˈtɪəriəl/", spell: false },
        { en: "unlucky", cn: "不幸运", phonetic: "/ʌnˈlʌki/", spell: false },
        { en: "convenient", cn: "便利", phonetic: "/kənˈviːniənt/", spell: false },
        { en: "education", cn: "教育", phonetic: "/ˌedʒuˈkeɪʃn/", spell: false },
        { en: "unless", cn: "除非", phonetic: "/ənˈles/", spell: false },
        { en: "report", cn: "报告", phonetic: "/rɪˈpɔːt/", spell: false },
        { en: "original", cn: "原始的，最初的", phonetic: "/əˈrɪdʒənl/", spell: false },
        { en: "excite", cn: "使兴奋", phonetic: "/ɪkˈsaɪt/", spell: false },
        { en: "fair", cn: "公平的；集市；晴朗的", phonetic: "/feə(r)/", spell: false },
        { en: "wealth", cn: "财产，财富", phonetic: "/welθ/", spell: false },
        { en: "fishing", cn: "钓鱼", phonetic: "/ˈfɪʃɪŋ/", spell: false },
        { en: "provide", cn: "提供", phonetic: "/prəˈvaɪd/", spell: false },
        { en: "meeting", cn: "会议", phonetic: "/ˈmiːtɪŋ/", spell: false },
        { en: "envelope", cn: "信封", phonetic: "/ˈenvələʊp/", spell: false },
        { en: "edge", cn: "边缘", phonetic: "/edʒ/", spell: false },
        { en: "dialogue", cn: "对话", phonetic: "/ˈdaɪəlɒɡ/", spell: false },
        { en: "case", cn: "情况；事例；箱", phonetic: "/keɪs/", spell: false },
        { en: "system", cn: "系统", phonetic: "/ˈsɪstəm/", spell: false },
        { en: "anywhere", cn: "任何地方", phonetic: "/ˈeniweə(r)/", spell: false },
        { en: "company", cn: "公司", phonetic: "/ˈkʌmpəni/", spell: false },
        { en: "vote", cn: "投票", phonetic: "/vəʊt/", spell: false },
        { en: "software", cn: "软件", phonetic: "/ˈsɒftweə(r)/", spell: false },
        { en: "boil", cn: "煮沸", phonetic: "/bɔɪl/", spell: false },
        { en: "pop", cn: "流行；流行音乐；取出", phonetic: "/pɒp/", spell: false },
        { en: "lose weight", cn: "减轻体重", phonetic: "/luːz weɪt/", spell: false },
        { en: "understanding", cn: "善解人意的", phonetic: "/ˌʌndəˈstændɪŋ/", spell: false },
        { en: "England", cn: "英国", phonetic: "/ˈɪŋɡlənd/", spell: false }
    ],

    "Unit 11": [
        { en: "negative", cn: "负面的", phonetic: "/ˈneɡətɪv/", spell: false },
        { en: "poster", cn: "海报", phonetic: "/ˈpəʊstə(r)/", spell: false },
        { en: "trainer", cn: "教练员；运动鞋", phonetic: "/ˈtreɪnə(r)/", spell: false },
        { en: "fool", cn: "傻瓜；愚弄", phonetic: "/fuːl/", spell: false },
        { en: "stress", cn: "压力；加压力于", phonetic: "/stres/", spell: false },
        { en: "nobody", cn: "没人", phonetic: "/ˈnəʊbədi/", spell: false },
        { en: "Australia", cn: "澳大利亚", phonetic: "/ɒˈstreɪliə/", spell: false },
        { en: "button", cn: "按键", phonetic: "/ˈbʌtn/", spell: false },
        { en: "clerk", cn: "职员；店员", phonetic: "/klɑːk/", spell: false },
        { en: "sausage", cn: "香肠", phonetic: "/ˈsɒsɪdʒ/", spell: false },
        { en: "female", cn: "女性", phonetic: "/ˈfiːmeɪl/", spell: false },
        { en: "population", cn: "人口", phonetic: "/ˌpɒpjuˈleɪʃn/", spell: false },
        { en: "host", cn: "主持人；主办", phonetic: "/həʊst/", spell: false },
        { en: "university", cn: "大学", phonetic: "/ˌjuːnɪˈvɜːsəti/", spell: false },
        { en: "pole", cn: "极；电线杆", phonetic: "/pəʊl/", spell: false },
        { en: "rainbow", cn: "彩虹", phonetic: "/ˈreɪnbəʊ/", spell: false },
        { en: "kilogram", cn: "千克", phonetic: "/ˈkɪləɡræm/", spell: false },
        { en: "spaceship", cn: "宇宙飞船", phonetic: "/ˈspeɪsʃɪp/", spell: false },
        { en: "brain", cn: "大脑", phonetic: "/breɪn/", spell: false },
        { en: "since", cn: "自从", phonetic: "/sɪns/", spell: false },
        { en: "quite", cn: "相当；完全", phonetic: "/kwaɪt/", spell: false },
        { en: "endangered", cn: "濒危；灭绝的", phonetic: "/ɪnˈdeɪndʒəd/", spell: false },
        { en: "businessman", cn: "商人", phonetic: "/ˈbɪznəsmæn/", spell: false },
        { en: "banker", cn: "银行家", phonetic: "/ˈbæŋkə(r)/", spell: false },
        { en: "lively", cn: "充满活力的；生动有趣的", phonetic: "/ˈlaɪvli/", spell: false },
        { en: "talk about", cn: "谈论", phonetic: "/tɔːk əˈbaʊt/", spell: false },
        { en: "honest", cn: "诚实的", phonetic: "/ˈɒnɪst/", spell: false },
        { en: "sign", cn: "符号；签名", phonetic: "/saɪn/", spell: false }
    ],

    "Unit 12": [
        { en: "hopefully", cn: "有希望地", phonetic: "/ˈhəʊpfəli/", spell: false },
        { en: "reflect", cn: "反射", phonetic: "/rɪˈflekt/", spell: false },
        { en: "fry", cn: "用油煎", phonetic: "/fraɪ/", spell: false },
        { en: "fix", cn: "修理", phonetic: "/fɪks/", spell: false },
        { en: "blood", cn: "血液", phonetic: "/blʌd/", spell: false },
        { en: "planet", cn: "行星", phonetic: "/ˈplænɪt/", spell: false },
        { en: "test", cn: "测试", phonetic: "/test/", spell: false },
        { en: "wool", cn: "羊毛", phonetic: "/wʊl/", spell: false },
        { en: "uncomfortable", cn: "不舒服的", phonetic: "/ʌnˈkʌmftəbl/", spell: false },
        { en: "handbag", cn: "手提包", phonetic: "/ˈhændbæɡ/", spell: false },
        { en: "pack", cn: "包；打包，包装", phonetic: "/pæk/", spell: false },
        { en: "speech", cn: "演讲", phonetic: "/spiːtʃ/", spell: false },
        { en: "design", cn: "设计", phonetic: "/dɪˈzaɪn/", spell: false },
        { en: "century", cn: "世纪", phonetic: "/ˈsentʃəri/", spell: false },
        { en: "clay", cn: "黏土", phonetic: "/kleɪ/", spell: false },
        { en: "Atlantic", cn: "大西洋", phonetic: "/ətˈlæntɪk/", spell: false },
        { en: "stair", cn: "楼梯", phonetic: "/steə(r)/", spell: false },
        { en: "Japan", cn: "日本", phonetic: "/dʒəˈpæn/", spell: false },
        { en: "topic", cn: "话题", phonetic: "/ˈtɒpɪk/", spell: false },
        { en: "mainly", cn: "主要地", phonetic: "/ˈmeɪnli/", spell: false },
        { en: "expensive", cn: "昂贵的", phonetic: "/ɪkˈspensɪv/", spell: false },
        { en: "string", cn: "细绳；线；一串", phonetic: "/strɪŋ/", spell: false },
        { en: "twin", cn: "双胞胎", phonetic: "/twɪn/", spell: false },
        { en: "grow up", cn: "长大", phonetic: "/ɡrəʊ ʌp/", spell: false },
        { en: "flood", cn: "洪水", phonetic: "/flʌd/", spell: false },
        { en: "would rather", cn: "宁愿", phonetic: "/wʊd ˈrɑːðə(r)/", spell: false },
        { en: "onto", cn: "到……上", phonetic: "/ˈɒntə/", spell: false },
        { en: "smoke", cn: "烟", phonetic: "/sməʊk/", spell: false }
    ]

};
