// vocab_detail.js — 拓展知识点数据
function D(f, p, e, c) { return { family: f, phrases: p, examples: e, comparison: c }; }

var wordDetail = {

// ===== Unit 1 =====
"senior": D(["seniority n.资历","junior adj.低年级的"],["senior high","senior student"],["He is a senior student in our school."],"近义词：advanced；反义词：junior；senior侧重年级/级别高，advanced侧重水平先进"),
"curious": D(["curiosity n.好奇心","curiously adv.好奇地"],["be curious about","be curious to do"],["All kids are curious about new things."],"近义词：interested；反义词：uninterested；curious带探寻未知的好奇，interested泛指感兴趣"),
"impression": D(["impress v.使印象深刻","impressive adj.令人印象深刻的"],["make an impression","first impression"],["Her smile left a good impression on me."],"近义词：feeling；无反义词；impression侧重外界带来的观感"),
"campus": D([],["on campus","campus life"],["We take a walk around the campus after class."],"近义词：schoolyard；无反义词；campus专指大/高中校园，schoolyard多指小学操场"),
"tradition": D(["traditional adj.传统的","traditionally adv.传统上"],["school tradition","cultural tradition"],["It's our school tradition to hold a sports meeting."],"近义词：custom；无反义词；tradition长期传承，custom侧重日常习俗"),
"facility": D(["facilitate v.使便利","facilitator n.协调人"],["sports facilities","school facilities"],["Our school has many modern sports facilities."],"近义词：equipment；无反义词；facility多指场地配套设施，equipment指器械设备"),
"impressive": D(["impress v.使印象深刻","impression n.印象"],["impressive performance","impressive view"],["The opening show of Orientation Day is impressive."],"近义词：striking；反义词：ordinary；impressive侧重让人赞叹难忘"),
"moment": D(["momentary adj.短暂的","momentarily adv.短暂地"],["at the moment","wait a moment"],["Could you wait for me for a moment?"],"近义词：minute；无反义词；moment侧重某个特定时刻，minute侧重一分钟的时段"),
"author": D(["authorship n.作者身份","authoress n.女作家"],["the author of the book","famous author"],["Who is the author of this English novel?"],"近义词：writer；无反义词；author多指书籍创作者，writer泛指各类写作者"),
"eagerness": D(["eager adj.渴望的","eagerly adv.急切地"],["with eagerness","show eagerness"],["He looks at the new club with great eagerness."],"近义词：desire；无反义词；eagerness是名词，表迫切向往"),
"explore": D(["exploration n.探索","explorer n.探险家"],["explore the campus","explore new ideas"],["We explore every corner of our new campus after school."],"近义词：discover；无反义词；explore主动探寻，discover侧重偶然发现"),
"engine": D(["engineer n.工程师","engineering n.工程学"],["car engine","start the engine"],["The engine of the school bus works well."],""),
"insect": D(["insecticide n.杀虫剂"],["small insect","flying insect"],["A butterfly is a beautiful flying insect."],"近义词：bug；无反义词；insect正式统称昆虫，bug口语小虫"),
"collection": D(["collect v.收集","collector n.收藏家"],["a collection of stamps","book collection"],["He shows us his collection of butterfly pictures."],"近义词：set；无反义词；collection成套收藏，set成套物品"),
"organise": D(["organisation n.组织","organiser n.组织者"],["organise a club","organise activities"],["We organise a badminton club in Grade One."],"近义词：arrange；无反义词；organise组织大型活动，arrange安排小事"),
"nudge": D([],["give sb a nudge","a gentle nudge"],["She gives me a nudge to remind me to speak."],"近义词：push；无反义词；nudge轻柔推，push用力推"),
"butterfly": D([],["butterfly garden","butterfly wings"],["I see many colourful butterflies on campus."],""),
"breathe": D(["breath n.呼吸","breathless adj.气喘吁吁的"],["breathe deeply","breathe slowly"],["Calm down and breathe deeply when you feel nervous."],"近义词：respire；无反义词；breathe日常用词，respire书面生物用词"),
"panic": D(["panicked adj.惊慌的","panicky adj.惶恐的"],["in panic","fall into panic"],["Don't be in panic when facing new challenges."],"近义词：fear；反义词：calm；panic突发慌乱，fear泛指恐惧"),
"challenge": D(["challenging adj.有挑战性的","challenger n.挑战者"],["face a challenge","meet the challenge"],["Learning new subjects is a big challenge for freshmen."],"近义词：difficulty；无反义词；challenge带有主动攻克的意味，difficulty单纯困难"),
"pressure": D(["press v.按压","pressured adj.有压力的"],["under pressure","reduce pressure"],["We should find ways to reduce study pressure."],"近义词：stress；无反义词；pressure外界施压，stress内心精神压力"),
"calm": D(["calmly adv.冷静地","calmness n.冷静"],["stay calm","keep calm"],["Stay calm when you feel butterflies in your stomach."],"近义词：quiet；反义词：nervous；calm情绪平稳，quiet环境安静"),
"description": D(["describe v.描述","descriptive adj.描写的"],["give a description","full description"],["Can you give a short description of your new teacher?"],"近义词：account；无反义词；description书面详细描述，account口头叙述"),
"confident": D(["confidence n.自信","confidently adv.自信地"],["be confident in","confident about"],["I am confident in my English speaking skills."],"近义词：sure；反义词：doubtful；confident长期内心自信，sure单纯确定某事"),
"poster": D([],["club poster","activity poster"],["We put a drama club poster on the classroom wall."],"近义词：notice；无反义词；poster大幅宣传海报，notice小型通知"),
"badminton": D([],["play badminton","badminton club"],["I join the badminton club after school every Wednesday."],""),
"drama": D(["dramatic adj.戏剧化的","dramatist n.剧作家"],["drama club","school drama"],["Our class will put on a small school drama."],"近义词：play；无反义词；drama戏剧艺术，play单指一出剧目"),
"band": D(["bandmate n.乐队队友"],["school band","rock band"],["The school band will perform on the stage tonight."],"近义词：orchestra；无反义词；band小型流行乐队，orchestra大型管弦乐团"),
"debate": D(["debater n.辩手","debatable adj.有争议的"],["class debate","hold a debate"],["We have a class debate about school topics this week."],"近义词：discussion；无反义词；debate正式辩论，discussion普通讨论"),
"gym": D(["gymnasium n.体育馆(完整拼写)"],["gym class","go to the gym"],["We have PE class in the big gym every Monday."],"近义词：sports hall；无反义词"),
"piano": D(["pianist n.钢琴家"],["play the piano","piano lesson"],["I take piano lessons after school every Friday."],""),
"stage": D(["stagecraft n.舞台技艺"],["on the stage","stage show"],["All band members stand on the stage to sing."],"近义词：platform；无反义词；stage演出舞台，platform高台/讲台"),
"photography": D(["photograph n.照片","photographer n.摄影师","photographic adj.摄影的"],["photography club","learn photography"],["I join the photography club to take pictures of the campus."],""),
"inner": D(["innermost adj.最深处的"],["inner thought","inner feeling"],["Writing journals helps us show our inner feelings."],"近义词：internal；反义词：outer；inner侧重心灵内在，internal侧重物体内部"),
"argue": D(["argument n.争论","argumentative adj.爱争辩的"],["argue about","argue with sb"],["Don't argue with your classmates over small topics."],"近义词：quarrel；无反义词；argue理性争辩，quarrel争吵带情绪"),
"topic": D(["topical adj.时下热门的"],["hot topic","discussion topic"],["Our debate topic is about after-school clubs."],"近义词：subject；无反义词；topic谈话话题，subject学科/主题"),
"sharp": D(["sharply adv.敏锐地","sharpness n.敏锐"],["sharp mind","sharp eyes"],["He has a sharp mind and learns new words fast."],"近义词：clever；反义词：slow；sharp思维反应快，clever泛指聪明"),
"dinosaur": D([],["dinosaur model","dinosaur picture"],["We see dinosaur pictures in the science classroom."],""),
"dolphin": D([],["dolphin show","dolphin tank"],["The article tells us about clever dolphins in the sea."],""),
"intelligent": D(["intelligence n.智慧","intelligently adv.聪慧地"],["intelligent animal","intelligent student"],["Dolphins are intelligent sea animals."],"近义词：smart；反义词：stupid；intelligent侧重高智商，smart机灵聪慧"),
"investigate": D(["investigation n.调查","investigator n.调查者","investigative adj.调查性的"],["investigate a problem","investigate facts"],["We investigate students' club choices for the committee."],"近义词：research；无反义词；investigate核查事实，research学术研究"),
"various": D(["vary v.变化","variety n.多样"],["various clubs","various activities"],["Our school has various after-school clubs for students."],"近义词：different；无反义词；various多种类，different侧重彼此不同"),
"volunteer": D(["volunteer v.自愿","voluntary adj.志愿的"],["school volunteer","volunteer work"],["I work as a volunteer for the school Orientation Day."],"近义词：helper；无反义词；volunteer无偿志愿，helper普通帮手"),
"gain": D(["gainful adj.有收益的"],["gain confidence","gain experience"],["You will gain lots of experience by joining clubs."],"近义词：get；反义词：lose；gain通过努力收获，get单纯得到"),
"apply": D(["application n.申请","applicant n.申请人"],["apply for a club","apply for opportunity"],["I apply for the photography club this term."],"近义词：request；无反义词；apply正式提交申请，request口头请求"),
"schedule": D(["schedule v.安排","scheduled adj.预定的"],["daily schedule","class schedule"],["Check your daily schedule before signing up for clubs."],"近义词：timetable；无反义词；schedule通用计划表，timetable专指课表/时刻表"),
"award": D(["award v.授予","awardee n.获奖者"],["win an award","get an award"],["He gets an award for his great performance in the band."],"近义词：prize；无反义词；award官方颁发奖项，prize竞赛奖品"),
"opportunity": D(["opportune adj.适宜的"],["golden opportunity","seize opportunity"],["This debate is a good opportunity to practise speaking."],"近义词：chance；无反义词；opportunity有利良机，chance偶然机会"),
"hint": D(["hint v.暗示"],["give a hint","take a hint"],["The teacher gives us a hint to memorise new words."],"近义词：suggestion；无反义词；hint间接提示，suggestion直接建议"),
"subscribe": D(["subscription n.订阅","subscriber n.订阅者"],["subscribe to a magazine","subscribe to journal"],["I subscribe to an English journal to improve reading."],"近义词：order；无反义词；subscribe长期订阅刊物，order单次订购"),
"view": D(["view v.看待","viewer n.观看者"],["a good view","one's view of school"],["We have a great view of the campus from the window."],"近义词：sight；无反义词；view远景视野，sight眼前所见事物"),
"former": D(["formerly adv.从前"],["former classmate","former teacher"],["My former teacher comes to visit our senior high today."],"近义词：past；反义词：current；former指前任/过去的人，past泛指过去时间"),
"graduate": D(["graduate n.毕业生","graduation n.毕业"],["graduate from senior high","graduate this year"],["We will graduate from this school in three years."],"近义词：finish；无反义词；graduate特指完成学业毕业"),
"orientation": D(["orient v.熟悉","oriented adj.导向的"],["Orientation Day","school orientation"],["All freshmen take part in school orientation on Monday."],""),
"frightened": D(["frighten v.使害怕","frightening adj.令人害怕的"],["feel frightened","frightened of insects"],["I feel frightened when I see big insects in the garden."],"近义词：scared；反义词：brave；frightened人感到害怕，frightening事物吓人"),
"sight": D(["sightsee v.观光","sightseeing n.游览"],["catch sight of","at first sight"],["I catch sight of a beautiful rainbow after class."],"近义词：view；无反义词；sight侧重偶然看见，view开阔视野"),
"figure": D(["figure n.人物","figuration n.外形"],["figure out","figure that"],["I figure that joining clubs can improve my confidence."],"近义词：think；无反义词；figure口语化认为，think通用思考"),
"select": D(["selection n.挑选","selective adj.挑剔的"],["select a club","select carefully"],["We select our favourite activities one by one."],"近义词：choose；无反义词；select精挑细选，choose普通选择"),
"particular": D(["particularly adv.尤其","particularity n.特性"],["in particular","particular topic"],["I like drama clubs in particular among all clubs."],"近义词：special；无反义词；particular特指某一个，special特殊与众不同"),
"rainbow": D([],["see a rainbow","rainbow colour"],["We see a bright rainbow after light rain at school."],""),
"neat": D(["neatly adv.整洁地","neatness n.整洁"],["neat classroom","neat idea"],["Our new classroom is neat and comfortable."],"近义词：tidy；反义词：messy；neat整洁清爽，tidy侧重收拾整齐"),
"specific": D(["specifically adv.具体地","specify v.明确说明"],["specific requirement","specific hint"],["The teacher gives us specific rules for the debate."],"近义词：detailed；反义词：general；specific精准具体，detailed细节丰富"),
"refer": D(["reference n.参考","referential adj.参照的"],["refer to","refer to the text"],["Don't refer to outside topics in your speech."],"近义词：mention；无反义词；refer间接提及，mention随口说起"),
"journal": D(["journalist n.记者","journalism n.新闻业"],["keep a journal","school journal"],["I keep a journal to write down my inner thoughts."],"近义词：diary；无反义词；journal可学习日志，diary私人日记"),
"junior": D(["juniority n.年少"],["junior high","junior student"],["Junior students will visit our senior campus next week."],"近义词：young；反义词：senior；junior年级低/年少，young单纯年龄小"),
"struggle": D(["struggle n.奋斗","struggling adj.努力的"],["struggle for goals","struggle with study"],["We struggle to go all out for our club performance."],"近义词：fight；无反义词；struggle克服困难拼搏，fight对抗争斗"),
"memorise": D(["memory n.记忆","memorable adj.难忘的"],["memorise words","memorise sentences"],["I memorise new words every morning before class."],"近义词：remember；无反义词；memorise刻意背诵，remember单纯记得"),
"skateboarding": D(["skateboard n.滑板","skateboarder n.滑板爱好者"],["skateboarding club","go skateboarding"],["He joins the skateboarding club after school."],""),
"forward": D(["forward adj.向前的","forwards adv.向前(同义)"],["look forward to","step forward"],["We look forward to the coming Orientation Day."],"近义词：ahead；反义词：backward；forward通用向前，ahead侧重前方位置"),
"committee": D(["commit v.负责","commission n.委员会(正式)"],["student committee","school committee"],["The student committee plans all club activities."],"近义词：board；无反义词；committee学生小型委员会，board董事会/理事会"),
"improve": D(["improvement n.提升","improved adj.改良的"],["improve skills","improve performance"],["Joining debates helps improve your speaking skills."],"近义词：develop；无反义词；improve向好提升，develop发展成长"),
"rate": D(["rate n.速度","rating n.评分"],["rate performance","rate carefully"],["Teachers rate our club performance every month."],"近义词：judge；无反义词；rate打分评估，judge主观判断"),
"performance": D(["perform v.表演","performer n.表演者"],["good performance","stage performance"],["The band's performance on stage is very impressive."],"近义词：show；无反义词；performance综合表现/正式演出，show小型展示"),
"exchange": D(["exchange n.交换","exchangeable adj.可交换的"],["exchange ideas","exchange thoughts"],["We exchange study ideas with new classmates after class."],"近义词：share；无反义词；exchange互相交换，share分享共用"),
"senior high": D([],["attend senior high","senior high life"],["I enjoy my new senior high life very much."],""),
"one by one": D([],["check one by one","select one by one"],["We go onto the stage one by one to give speeches."],""),
"butterflies in one's stomach": D([],["have butterflies in one's stomach"],["I have butterflies in my stomach before speaking on stage."],""),
"in panic": D([],["run in panic","act in panic"],["Don't act in panic when you meet new challenges."],""),
"pm": D([],["3 pm","after pm"],["Our club activities start at 4 pm every Wednesday."],"反义词：am（上午）"),
"Orientation Day": D([],["school Orientation Day","take part in Orientation Day"],["All freshmen take part in Orientation Day this week."],""),
"go all out": D([],["go all out for a match","go all out for performance"],["We go all out to prepare for the school drama show."],""),
"in particular": D([],["like in particular","notice in particular"],["I like photography clubs in particular among all clubs."],""),
"refer to": D([],["refer to notes","refer to the text"],["You can refer to your journal when writing the description."],""),
"look forward to": D([],["look forward to the show","look forward to holiday"],["We look forward to the coming school sports meeting."],""),

// ===== Unit 2 =====
"title": D([],["book title","essay title"],["Write a clear title for your English essay."],"近义词：heading；无反义词；title多指文章/书籍标题，heading段落小标题"),
"ham": D([],["ham sandwich","sliced ham"],["We have ham sandwiches for lunch at school."],""),
"eggplant": D([],["fried eggplant","eggplant salad"],["I learn the word eggplant in today's English class."],""),
"pine": D([],["pine tree","pine wood"],["There are tall pine trees beside our classroom."],""),
"pineapple": D([],["pineapple juice","fresh pineapple"],["The shop sells sweet pineapple after school."],""),
"sculpt": D(["sculpture n.雕像","sculptor n.雕刻家"],["sculpt stone","sculpt clay"],["Art students sculpt small figures in art class."],"近义词：carve；无反义词；sculpt艺术雕塑，carve切割木头石头"),
"sculpture": D(["sculpt v.雕刻","sculptor n.雕刻家"],["stone sculpture","art sculpture"],["We enjoy beautiful sculptures in the school art room."],"近义词：statue；无反义词；sculpture泛指雕刻艺术品，statue人像雕塑"),
"seasick": D(["seasickness n.晕船"],["feel seasick","get seasick"],["I will not get seasick on the school ship trip."],"近义词：nauseous；反义词：comfortable；seasick特指坐船头晕，nauseous泛指恶心"),
"airsick": D(["airsickness n.晕机"],["become airsick","feel airsick"],["Some students feel airsick on the plane trip."],"近义词：nauseous；反义词：comfortable；airsick仅指坐飞机不适"),
"carsick": D(["carsickness n.晕车"],["get carsick","feel carsick"],["My deskmate easily gets carsick on school buses."],"近义词：nauseous；反义词：comfortable；carsick专指乘车头晕"),
"homesick": D(["homesickness n.思乡"],["feel homesick","become homesick"],["Freshmen often feel homesick at boarding school."],"近义词：lonely；反义词：content；homesick思念家乡，lonely内心孤单"),
"opposing": D(["oppose v.反对","opposite adj.相反的"],["opposing views","opposing ideas"],["We hold opposing opinions in the English forum."],"近义词：contrary；反义词：same；opposing侧重观点对立，contrary完全相反"),
"behavior": D(["behave v.表现","well-behaved adj.举止得体的"],["good behavior","student behavior"],["Teachers pay attention to students' daily behavior."],"近义词：conduct；无反义词；behavior日常行为，conduct正式品行"),
"confusing": D(["confuse v.使困惑","confused adj.感到困惑的"],["confusing rules","confusing words"],["These similar English words are confusing to new students."],"近义词：puzzling；反义词：clear；confusing事物让人迷惑，confused人感到困惑"),
"capitalized": D(["capital n.大写字母","capitalise v.大写"],["capitalized letter","capitalized word"],["Proper nouns need capitalized first letters."],"近义词：uppercase；反义词：lowercase；capitalized形容词大写的，uppercase名词大写字母"),
"unique": D(["uniquely adv.独特地","uniqueness n.独特性"],["unique style","unique culture"],["Every student has a unique way to learn English."],"近义词：special；反义词：common；unique仅此一个，special与众不同"),
"alarm": D(["alarm v.使惊慌","alarmed adj.受惊的"],["alarm clock","fire alarm"],["My alarm clock wakes me up at 6 every morning."],"近义词：warning；无反义词；alarm实物闹钟/警报，warning口头警示"),
"reflect": D(["reflection n.反映","reflective adj.反思的"],["reflect ideas","reflect feelings"],["Your writing can reflect your real thoughts."],"近义词：show；无反义词；reflect深层反映，show单纯展示"),
"creativity": D(["creative adj.有创造力的","create v.创造"],["develop creativity","artistic creativity"],["Art class helps us develop our creativity."],"近义词：imagination；无反义词；creativity创造能力，imagination想象力"),
"visible": D(["visibly adv.明显地","vision n.视力"],["visible light","clearly visible"],["The words on the blackboard are visible to all students."],"近义词：seen；反义词：invisible；visible客观能看见，seen被动看见"),
"creative": D(["create v.创造","creativity n.创造力"],["creative thinking","creative work"],["We need creative thinking for group discussion."],"近义词：original；反义词：unimaginative；creative善于创造，original新颖原创"),
"type": D(["typical adj.典型的","type v.打字"],["different types","all types"],["There are many types of English learning resources."],"近义词：kind；无反义词；type分类标准类型，kind泛指类别"),
"unfamiliar": D(["familiar adj.熟悉的","familiarity n.熟悉"],["unfamiliar words","unfamiliar place"],["Many new words are unfamiliar to Grade One students."],"近义词：strange；反义词：familiar；unfamiliar不认识，strange陌生怪异"),
"contact": D(["contact n.联系","contactable adj.可联系的"],["contact classmates","contact teachers"],["You can contact your teacher after class for help."],"近义词：reach；无反义词；contact书面正式联系，reach口语联系上"),
"organization": D(["organise v.组织","organiser n.组织者"],["student organization","school organization"],["Our school has many student organizations."],"近义词：group；无反义词；organization正规机构，group小型小组"),
"likely": D(["like v.喜欢","likelihood n.可能性"],["be likely to do","likely result"],["It is likely that we will have an English forum tomorrow."],"近义词：possible；反义词：unlikely；likely侧重有迹象很可能，possible客观存在可能性"),
"subway": D([],["take the subway","subway station"],["I take the subway to downtown every weekend."],"近义词：underground；无反义词；subway美式，underground英式地铁"),
"highway": D([],["national highway","busy highway"],["The highway connects our town to the city centre."],"近义词：road；无反义词；highway城际公路，road普通道路"),
"motorway": D([],["motorway exit","wide motorway"],["We drive on the motorway to the city museum."],"近义词：highway；无反义词；motorway英式高速，highway普通公路"),
"gas": D(["gasoline n.汽油(美式)"],["fill gas","gas station"],["The school bus needs enough gas every morning."],"近义词：petrol；无反义词；gas美式汽油，petrol英式汽油"),
"petrol": D(["petroleum n.石油","gas n.汽油(美式)"],["petrol pump","petrol station"],["We stop at a petrol station on our school trip."],"近义词：gas；无反义词；petrol英式汽油，gas美式口语"),
"apartment": D([],["small apartment","downtown apartment"],["My cousin lives in an apartment downtown."],"近义词：flat；无反义词；apartment美式公寓，flat英式公寓"),
"flat": D(["flat adj.平坦的","flatten v.使变平"],["city flat","small flat"],["Many teachers live in flats near the school."],"近义词：apartment；无反义词；flat英式公寓，apartment美式公寓"),
"elevator": D([],["take the elevator","elevator door"],["We take the elevator to the upstairs classroom."],"近义词：lift；无反义词；elevator美式电梯，lift英式电梯"),
"context": D(["contextual adj.上下文的"],["word context","reading context"],["Guess new words from the reading context."],"近义词：situation；无反义词；context文字语境，situation现实场景"),
"addition": D(["add v.添加","additional adj.额外的"],["in addition","useful addition"],["This English book is a good addition to our resources."],"近义词：extra；无反义词；addition新增事物，extra额外的"),
"forum": D([],["English forum","class forum"],["We share ideas in the online English forum."],"近义词：discussion；无反义词；forum固定讨论平台，discussion普通交谈"),
"resource": D(["resourceful adj.足智多谋的"],["learning resources","school resources"],["The library provides many English learning resources."],"近义词：material；无反义词；resource学习资源，material原材料"),
"misadventure": D(["adventure n.奇遇","misadventurous adj.多灾的"],["a small misadventure","unexpected misadventure"],["We met a small misadventure during the school trip."],"近义词：accident；无反义词；misadventure小型倒霉意外，accident严重事故"),
"remind": D(["reminder n.提示物"],["remind sb of sth","remind sb to do"],["The teacher reminds us to take English books every day."],"近义词：warn；无反义词；remind提醒某事，warn警告危险"),
"rather": D(["rather adj.公正的"],["rather difficult","rather interesting"],["This grammar point is rather difficult for freshmen."],"近义词：quite；无反义词；rather语气偏弱，quite程度更强"),
"comment": D(["comment v.评论","commentator n.评论员"],["make a comment","short comment"],["Write a short comment after reading the English article."],"近义词：opinion；无反义词；comment针对事物点评，opinion个人观点"),
"frog": D([],["green frog","frog sound"],["We learn the word frog in nature English class."],""),
"throat": D([],["sore throat","clear one's throat"],["I have a sore throat and cannot speak loudly today."],""),
"downtown": D(["downtown adv.往市中心"],["downtown street","downtown apartment"],["We visit downtown bookstores on weekends."],"近义词：city-centre；反义词：suburb；downtown城镇中心，suburb郊区"),
"boot": D([],["leather boot","rain boot"],["I wear rain boots on rainy school days."],"近义词：shoe；无反义词；boot高筒靴，shoe普通鞋子"),
"entrance": D(["enter v.进入","entry n.进入"],["school entrance","main entrance"],["Wait for your classmates at the school entrance."],"近义词：gate；反义词：exit；entrance建筑入口，gate户外大门"),
"section": D(["section v.划分","sectional adj.分区的"],["reading section","sports section"],["The English section is on the second floor of the library."],"近义词：part；无反义词；section固定分区，part任意一部分"),
"exit": D(["exit v.离开","exits n.复数出口"],["safe exit","back exit"],["Please find the nearest exit in case of danger."],"近义词：way out；反义词：entrance；exit正式安全出口，way out口语出路"),
"actually": D(["actual adj.真实的","actuality n.现实"],["actually speaking","not actually"],["I actually finish my English homework after class."],"近义词：in fact；无反义词；actually书面口语通用，in fact短语同义"),
"downstairs": D(["downstairs adj.楼下的","upstairs adv.在楼上"],["go downstairs","walk downstairs"],["The art classroom is downstairs on the first floor."],"近义词：below；反义词：upstairs；downstairs楼房楼下，below泛指下方"),
"wicked": D(["wickedly adv.恶劣地","wickedness n.邪恶"],["wicked plan","wicked idea"],["The students think the game has a wicked fun rule."],"近义词：evil/great；反义词：kind；表邪恶evil；表极好great"),
"odd": D(["oddly adv.奇怪地","oddness n.怪异"],["odd word","odd behavior"],["This old English word sounds odd to us."],"近义词：strange；反义词：normal；odd反常怪异，strange陌生奇怪"),
"negative": D(["negatively adv.消极地","negativity n.消极"],["negative thought","negative comment"],["Don't hold negative attitudes towards English study."],"近义词：bad；反义词：positive；negative侧重心态消极，bad单纯不好"),
"error": D(["err v.犯错","error-prone adj.易出错的"],["spelling error","small error"],["Check your writing for spelling errors before handing in."],"近义词：mistake；无反义词；error书面正式错误，mistake日常小失误"),
"intend": D(["intention n.意图","intended adj.有意的"],["intend to study","intend to join"],["I intend to join the school English forum this term."],"近义词：plan；无反义词；intend内心打算，plan制定计划"),
"informal": D(["formal adj.正式的","informally adv.非正式地"],["informal words","informal talk"],["We use informal English when chatting with classmates."],"近义词：casual；反义词：formal；informal语言不正式，casual场合随意"),
"recognise": D(["recognition n.认出","recognisable adj.可识别的"],["recognise words","recognise classmates"],["I can recognise all new words we learned this week."],"近义词：identify；无反义词；recognise认出人/文字，identify辨别区分"),
"base": D(["base n.基础","basic adj.基础的"],["base on facts","base on reading"],["We base our opinions on what we read in texts."],"近义词：found；无反义词；base以某物为依据，found建立机构"),
"aware": D(["awareness n.意识","unaware adj.没意识到的"],["be aware of","fully aware"],["We must be aware of confusing similar words."],"近义词：conscious；反义词：unaware；aware客观察觉到，conscious内心清醒"),
"burn up": D([],["burn up paper","burn up waste"],["Don't burn up waste paper in the classroom."],""),
"burn down": D([],["burn down buildings","burn down houses"],["The story tells a house burned down by accident."],""),
"wind up": D([],["wind up a watch","wind up a meeting"],["We wind up the English forum at 5 pm."],""),
"come across": D([],["come across new words","come across articles"],["I come across this useful English article online."],""),
"have a frog in one's throat": D([],["have a frog in one's throat"],["I have a frog in my throat before the speech."],""),
"be aware of": D([],["be aware of mistakes","be aware of rules"],["Be aware of your spelling errors when writing."],""),

// ===== Unit 4（运动与职业）=====
"character": D(["characteristic adj.典型","characterize v.描述特征"],["main character","cartoon character"],["We discuss the main character in the drama text."],"近义词：figure；无反义词；character文学影视人物，figure泛指形象"),
"approach": D(["approach n.方法","approachable adj.易亲近"],["approach the gate","approach the teacher"],["I approach my teacher to ask for advice."],"近义词：near；反义词：leave；approach主动靠近，near表距离近"),
"chat": D(["chat v.聊天","chatty adj.爱闲聊"],["have a chat","casual chat"],["We have a short chat after PE class."],"近义词：talk；反义词：silence；chat轻松闲聊，talk普通交谈"),
"focus": D(["focus n.焦点","focused adj.专注"],["focus on study","focus on class"],["Focus your mind on listening in class."],"近义词：concentrate；反义词：distract；focus集中注意力，concentrate书面专注"),
"career": D(["careerist n.事业心强的人"],["future career","career plan"],["We talk about our ideal career in English class."],"近义词：job；无反义词；career长期事业，job短期工作"),
"lawyer": D(["law n.法律","lawful adj.合法"],["famous lawyer","family lawyer"],["My uncle works as a professional lawyer."],"近义词：attorney；无反义词；lawyer通用律师，attorney美式法律代理人"),
"assume": D(["assumption n.假设","assumed adj.假定"],["assume the result","assume correctly"],["Don't assume you can pass without practice."],"近义词：suppose；反义词：prove；assume无依据假定，suppose口语猜想"),
"respect": D(["respect n.尊重","respectful adj.恭敬"],["respect teachers","respect others"],["We should respect every student in our class."],"近义词：admire；反义词：disrespect；respect尊重人格，admire钦佩才华"),
"studio": D([],["music studio","art studio"],["The band practises songs in the school studio."],"近义词：workroom；无反义词；studio专业影音画室，workroom普通工作室"),
"court": D(["courthouse n.法院大楼"],["law court","basketball court"],["The story happens in a local law court."],"近义词：tribunal；无反义词；court通用法庭，tribunal专项裁决庭"),
"ignore": D(["ignorant adj.无知","ignorance n.无知"],["ignore mistakes","ignore others' words"],["Don't ignore the small spelling errors in writing."],"近义词：neglect；反义词：notice；ignore刻意无视，neglect疏忽遗漏"),
"professional": D(["profession n.职业","professionally adv.专业地"],["professional skill","professional athlete"],["This athlete has professional training every day."],"近义词：skilled；反义词：amateur；professional受过专业训练，skilled单纯有技巧"),
"suit": D(["suitable adj.合适","suited adj.适宜"],["suit one's taste","suit students"],["This learning method suits most freshmen."],"近义词：fit；反义词：unsuit；suit侧重喜好匹配，fit尺寸适配"),
"talent": D(["talented adj.有天赋","talentless adj.无天分"],["show talent","natural talent"],["She shows great talent in piano playing."],"近义词：gift；反义词：weakness；talent后天可培养天赋，gift天生禀赋"),
"option": D(["opt v.选择","optional adj.可选"],["many options","best option"],["We have three options for after-school clubs."],"近义词：choice；反义词：obligation；option正式可选方案，choice日常选择"),
"sigh": D(["sigh v.叹气","sighingly adv.叹息地"],["a deep sigh","give a sigh"],["He gives a sigh when facing hard tasks."],"近义词：breath；反义词：cheer；sigh带情绪叹气，breath普通呼吸"),
"curtain": D(["curtained adj.带幕布"],["stage curtain","draw curtains"],["The stage curtain rises before the show."],"近义词：screen；无反义词；curtain舞台帷幕，screen屏幕遮挡物"),
"generation": D(["generate v.产生","generational adj.代际"],["young generation","old generation"],["There is a small gap between two generations."],"近义词：age group；无反义词；generation按年龄世代，age group同龄群体"),
"gap": D(["gap v.拉开差距"],["generation gap","gap in marks"],["We narrow the gap between weak students."],"近义词：difference；反义词：similarity；gap悬殊差距，difference普通差别"),
"currently": D(["current adj.当前","currency n.货币"],["currently studying","currently busy"],["We are currently preparing for the sports meet."],"近义词：now；反义词：formerly；currently书面当下，now口语现在"),
"regularly": D(["regular adj.定期","regularity n.规律"],["exercise regularly","read regularly"],["I practise English speaking regularly every morning."],"近义词：often；反义词：seldom；regularly有规律频繁，often单纯时常"),
"responsible": D(["responsibility n.责任","responsibly adv.负责地"],["be responsible for","responsible student"],["You are responsible for your own homework."],"近义词：dutiful；反义词：irresponsible；responsible承担责任，dutiful本分尽责"),
"memory": D(["memorise v.记忆","memorable adj.难忘"],["good memory","sweet memory"],["I keep sweet memories of my senior life."],"近义词：recollection；反义词：forgetfulness；memory长期记忆，recollection片段回忆"),
"nowadays": D([],["nowadays students","nowadays life"],["Nowadays students have more after-school activities."],"近义词：today；反义词：once；nowadays现今时代，today今日当天"),
"jaw": D([],["lower jaw","drop one's jaw"],["His jaw drops when hearing the medal news."],"近义词：chin；无反义词；jaw整个颌部，chin下巴尖端"),
"beard": D(["bearded adj.有胡须"],["long beard","shave beard"],["The old writer has a thick grey beard."],"近义词：whisker；无反义词；beard下巴胡须，whisker腮边细须"),
"skin": D(["skin v.剥皮","skinny adj.瘦皮"],["soft skin","protect skin"],["We should protect our skin outdoors."],"近义词：complexion；无反义词；skin皮肤表层，complexion肤色肤质"),
"jogging": D(["jog v.慢跑","jogger n.慢跑者"],["go jogging","daily jogging"],["Many students go jogging on the track after school."],"近义词：running；无反义词；jogging慢速慢跑，running快跑"),
"slim": D(["slim v.瘦身","slimness n.苗条"],["slim figure","slim body"],["She keeps slim by daily jogging."],"近义词：thin；反义词：fat；slim匀称苗条，thin单薄偏瘦"),
"cheek": D(["cheeky adj.厚脸皮"],["red cheek","touch one's cheek"],["Her cheeks turn red when getting praise."],"近义词：face；无反义词；cheek单侧面颊，face整张脸"),
"nation": D(["national adj.国家","nationality n.国籍"],["whole nation","nation hero"],["Athletes win medals for their nation."],"近义词：country；无反义词；nation国民层面国家，country国土"),
"aim": D(["aim n.目标","aimless adj.无目标"],["aim high","aim to improve"],["I aim to get positive progress in English."],"近义词：try；反义词：give up；aim树立目标努力，try单纯尝试"),
"issue": D(["issue v.发布"],["hot issue","social issue"],["We debate a hot issue in class today."],"近义词：topic；无反义词；issue社会争议议题，topic普通话题"),
"theme": D(["thematic adj.主题相关"],["main theme","story theme"],["The theme of this text is sports spirit."],"近义词：subject；无反义词；theme文章核心主旨，subject学科题材"),
"observe": D(["observation n.观察","observant adj.善于观察"],["observe festivals","observe birthdays"],["We observe Spring Festival every year."],"近义词：celebrate；反义词：ignore；observe正式过节，celebrate通用庆祝"),
"range": D(["range v.涵盖"],["a range of sports","wide range"],["The school offers a range of sport events."],"近义词：series；无反义词；range范围系列，series成套赛事"),
"event": D(["eventful adj.多事"],["sport event","school event"],["The triathlon is a big sport event this term."],"近义词：activity；无反义词；event大型赛事活动，activity小型课余活动"),
"apologise": D(["apology n.道歉","apologetic adj.愧疚"],["apologise to sb","apologise for mistakes"],["You must apologise for ignoring your partner."],"近义词：say sorry；反义词：offend；apologise正式致歉，say sorry口语道歉"),
"stress": D(["stress n.压力","stressful adj.有压力"],["word stress","mark stress"],["Mark the stress of each new vocabulary word."],"近义词：accent；无反义词；stress单词重音，accent口音"),
"impact": D(["impact v.影响"],["big impact","positive impact"],["Daily reading has an impact on your writing."],"近义词：influence；反义词：unimportance；impact强烈冲击影响，influence潜移默化"),
"strength": D(["strong adj.强壮","strengthen v.加强"],["great strength","mental strength"],["Athletes have great physical strength."],"近义词：power；反义词：weakness；strength内在力量强度，power外在权力"),
"admire": D(["admiration n.钦佩","admirable adj.令人敬佩"],["admire athletes","admire talent"],["I admire those hard-working young athletes."],"近义词：respect；无反义词；admire欣赏才华，respect尊重人格"),
"judge": D(["judge n.裁判","judgment n.判断"],["judge fairly","judge by facts"],["Don't judge a person only by appearance."],"近义词：decide；反义词：doubt；judge客观评判，decide做出决定"),
"settle": D(["settlement n.和解","settled adj.安定"],["settle arguments","settle disagreements"],["We settle our small chat arguments quickly."],"近义词：solve；反义词：argue；settle化解矛盾，solve解决难题"),
"feature": D(["feature v.以…为特色"],["news feature","sport feature"],["The magazine has a feature about triathletes."],"近义词：article；无反义词；feature专题特写，article普通文章"),
"typically": D(["typical adj.典型","typify v.代表"],["typically start","typically train"],["Athletes typically train every single day."],"近义词：usually；反义词：rarely；typically典型常态，usually日常经常"),
"individual": D(["individual n.个人","individually adv.单独"],["individual style","individual idea"],["Every athlete has their individual training way."],"近义词：personal；反义词：group；individual个体独特，personal私人的"),
"style": D(["stylish adj.时髦","stylist n.设计师"],["writing style","sport style"],["We learn different writing styles in English class."],"近义词：way；无反义词；style独特风格，way通用方式"),
"extra": D(["extra n.额外之物","extremely adv.极其"],["extra time","extra practice"],["Do extra English exercises to improve marks."],"近义词：additional；反义词：necessary；extra多余附加，additional补充必需"),
"detail": D(["detailed adj.详细","detail v.详述"],["small detail","every detail"],["Pay attention to small details in your summary."],"近义词：point；反义词：outline；detail细微细节，point要点"),
"contain": D(["container n.容器","content n.内容"],["contain details","contain facts"],["This text contains many sport related words."],"近义词：include；反义词：exclude；contain整体内含，include部分包含"),
"summary": D(["summarise v.总结","summarized adj.概括的"],["short summary","write a summary"],["Write a short summary after reading the passage."],"近义词：outline；反义词：detail；summary完整概要，outline提纲"),
"powerful": D(["power n.力量","powerfully adv.有力地"],["powerful athlete","powerful speech"],["The athlete has powerful leg strength."],"近义词：strong；反义词：weak；powerful气场力量强，strong身体强壮"),
"triathlon": D([],["join triathlon","triathlon match"],["I take part in the school triathlon this year."],""),
"series": D(["series adj.连续"],["race series","match series"],["We watch a series of track races today."],"近义词：range；无反义词；series连贯系列赛事，range宽泛范围"),
"track": D(["track v.追踪"],["running track","track event"],["All jogging activities happen on the track."],"近义词：path；无反义词；track标准田径跑道，path小路"),
"media": D(["medium n.媒介(单数)"],["news media","school media"],["The school media reports medal winners."],"近义词：press；无反义词；media各类传媒，press报刊媒体"),
"obviously": D(["obvious adj.明显","obviousness n.浅显"],["obviously better","obviously right"],["He is obviously in the lead in the race."],"近义词：clearly；反义词：unclearly；obviously书面显而易见，clearly清晰直观"),
"despite": D([],["despite pressure","despite tiredness"],["He keeps training despite great study pressure."],"近义词：although；反义词：because；despite介词接名词，although连词接句子"),
"throughout": D([],["throughout the match","throughout the term"],["He stays calm throughout the whole triathlon."],"近义词：during；反义词：after；throughout全程贯穿，during在期间"),
"entire": D(["entirely adv.完全","entirety n.整体"],["entire class","entire race"],["The entire class cheers for our athletes."],"近义词：whole；反义词：partial；entire完整无缺，whole整体不拆分"),
"enormously": D(["enormous adj.巨大","enormity n.庞大"],["enormously strong","enormously hard"],["This athlete trains enormously hard every day."],"近义词：extremely；反义词：slightly；enormously程度极强，extremely通用非常"),
"positive": D(["positively adv.积极","positivity n.乐观"],["positive attitude","positive comment"],["Keep positive when facing sport failures."],"近义词：optimistic；反义词：negative；positive心态正向，optimistic乐观向上"),
"million": D(["millionth adj.百万分之一"],["a million people","two million medals"],["The news spreads to a million readers."],""),
"disqualify": D(["disqualification n.取消资格","qualify v.合格"],["disqualify athletes","disqualify for faults"],["You will get disqualified for breaking track rules."],"近义词：exclude；反义词：qualify；disqualify违规除名，exclude单纯排除"),
"athlete": D(["athletic adj.运动的","athletics n.田径"],["young athlete","track athlete"],["All athletes must follow match rules."],"近义词：sportsman；无反义词；athlete专业田径选手，sportsman通用运动员"),
"medal": D(["medalist n.奖牌得主"],["win a medal","gold medal"],["She wins a silver medal in the triathlon."],"近义词：prize；无反义词；medal赛事奖牌，prize竞赛奖品"),
"somehow": D([],["somehow win","somehow succeed"],["He somehow stays in the lead till the end."],"近义词：anyhow；反义词：surely；somehow不知何种方式，anyhow无论如何"),
"indeed": D([],["indeed powerful","indeed hard"],["The triathlon is indeed a hard sport."],"近义词：really；反义词：hardly；indeed加强肯定，really单纯真实"),
"onto": D([],["jump onto track","step onto stage"],["The athlete jumps onto the running track."],"近义词：on；反义词：off；onto动态到表面，on静态在上面"),
"settle for": D([],["settle for second","settle for small medal"],["I will not settle for only a bronze medal."],""),
"in the lead": D([],["stay in the lead","remain in the lead"],["Our runner stays in the lead on the track."],""),

// ===== Unit 4（友谊与成长）=====
"forever": D([],["last forever","remember forever"],["I will keep this warm memory forever."],"近义词：always；反义词：temporarily；forever指永久不变，always侧重经常性"),
"familiar": D(["familiarity n.熟悉","unfamiliar adj.陌生的"],["be familiar with","familiar topic"],["This story is familiar to all classmates."],"近义词：well-known；反义词：unfamiliar；familiar日常熟知，well-known广为人知"),
"adventure": D(["adventurous adj.爱冒险","misadventure n.不幸遭遇"],["school adventure","life adventure"],["Our field trip is a great small adventure."],"近义词：journey；反义词：routine；adventure含刺激奇遇，journey普通旅途"),
"prefer": D(["preference n.偏爱","preferable adj.更合适的"],["prefer A to B","prefer doing"],["I prefer reading English to playing games."],"近义词：like better；反义词：dislike；prefer两相比较偏爱，like单纯喜欢"),
"deliver": D(["delivery n.递送","deliverer n.配送人"],["deliver messages","deliver goods"],["The teacher delivers learning materials to us."],"近义词：send；反义词：receive；deliver专人送达，send普通寄送"),
"advance": D(["advance v.推进","advanced adj.高级的"],["make advance","great advance"],["We make big advance in oral English."],"近义词：progress；反义词：regress；advance阶段性进步，progress长期成长"),
"significantly": D(["significant adj.重大","significance n.意义"],["improve significantly","drop significantly"],["My reading speed improves significantly."],"近义词：greatly；反义词：slightly；significantly幅度大，greatly程度深"),
"maintain": D(["maintenance n.维持"],["maintain friendship","maintain balance"],["We maintain daily communication with partners."],"近义词：keep；反义词：abandon；maintain长期稳固维持，keep普通保持"),
"wifi": D([],["public wifi","school wifi"],["We use free wifi in the library."],""),
"click": D(["click n.点击声"],["click the icon","click the link"],["Click this site to read English articles."],"近义词：tap；无反义词；click鼠标点击，tap触屏轻点"),
"digital": D(["digit n.数字","digitally adv.数字化地"],["digital resource","digital device"],["We use digital tools to learn words."],"近义词：electronic；反义词：analog；digital数字编码，electronic电子通用"),
"enable": D(["able adj.能够","ability n.能力"],["enable sb to do","enable study"],["The app enables us memorise words fast."],"近义词：allow；反义词：prevent；enable赋予能力，allow许可行为"),
"unusual": D(["usual adj.平常","usually adv.通常"],["unusual story","unusual hobby"],["He has an unusual way to memorise words."],"近义词：strange；反义词：usual；unusual少见独特，strange怪异奇怪"),
"site": D(["website n.网站"],["learning site","English site"],["This site provides free reading excerpts."],"近义词：website；无反义词；site简写，website完整写法"),
"tend": D(["tendency n.倾向"],["tend to forget","tend to relax"],["Students tend to feel anxious before exams."],"近义词：be likely；反义词：refuse；tend习惯性倾向，be likely客观可能"),
"update": D(["update v.更新","updated adj.更新的"],["daily update","news update"],["Check the update of English learning site."],""),
"saying": D(["say v.说","said adj.上述的"],["old saying","useful saying"],["This saying helps us build good qualities."],"近义词：proverb；无反义词；saying通用俗语，proverb经典谚语"),
"criminal": D(["crime n.罪行","criminal adj.犯罪的"],["catch criminal","dangerous criminal"],["The text tells a story about a criminal."],"近义词：lawbreaker；反义词：police；criminal法律罪犯，lawbreaker违法者"),
"bathwater": D([],["dirty bathwater","warm bathwater"],["Don't pour bathwater everywhere in dorm."],""),
"acquire": D(["acquisition n.习得"],["acquire skills","acquire knowledge"],["We acquire generosity from daily life."],"近义词：gain；反义词：lose；acquire慢慢习得，gain努力收获"),
"goods": D(["good adj.好"],["daily goods","school goods"],["The shop sells cheap study goods."],"近义词：products；反义词：raw material；goods售卖商品，products工业产品"),
"prove": D(["proof n.证据","proven adj.证实的"],["prove facts","prove one's passion"],["You can prove your progress through tests."],"近义词：show；反义词：disprove；prove严谨证明，show单纯展示"),
"illustrate": D(["illustration n.图解","illustrative adj.说明的"],["illustrate rules","illustrate ideas"],["The diagram illustrates word formation."],"近义词：explain；反义词：confuse；illustrate配例阐释，explain普通解释"),
"diagram": D([],["flow diagram","word diagram"],["Draw a diagram to show word groups."],"近义词：chart；无反义词；diagram流程简图，chart数据图表"),
"inspiring": D(["inspire v.激励","inspiration n.灵感"],["inspiring story","inspiring excerpt"],["This inspiring passage lifts our mood."],"近义词：encouraging；反义词：boring；inspiring激发内心，encouraging给予鼓励"),
"teenager": D(["teenage adj.青少年","teens n.少年时期"],["young teenager","high school teenager"],["Most teenagers use social media daily."],"近义词：youth；反义词：adult；teenager13-19岁，youth青年群体"),
"pour": D(["pour n.倾泻"],["pour water","pour milk"],["Pour a slice of bread into the pot."],"近义词：fill；反义词：empty；pour液体倾倒，fill填满容器"),
"pot": D([],["cooking pot","small pot"],["We heat soup in a metal pot."],"近义词：pan；无反义词；pot深锅，pan平底锅"),
"gram": D([],["500 gram","one gram"],["This slice of bread weighs ten gram."],""),
"pack": D(["pack v.打包","package n.包裹"],["food pack","stationery pack"],["I buy a pack of English flashcards."],"近义词：packet；无反义词；pack美式小包，packet英式"),
"comfort": D(["comfort v.安抚","comfortable adj.舒适"],["give comfort","seek comfort"],["Friends give me comfort when anxious."],"近义词：relief；反义词：pain；comfort情感慰藉，relief压力缓解"),
"patience": D(["patient adj.耐心","patient n.病人"],["have patience","lose patience"],["We need patience to memorise words."],"近义词：calmness；反义词：impatience；patience忍耐心性，calmness情绪平静"),
"passion": D(["passionate adj.热情"],["deep passion","study passion"],["She has great passion for English."],"近义词：enthusiasm；反义词：coldness；passion强烈热爱，enthusiasm热忱兴趣"),
"generosity": D(["generous adj.慷慨","generously adv.大方地"],["show generosity","true generosity"],["His generosity wins many good partners."],"近义词：kindness；反义词：selfishness；generosity大方施舍，kindness普通善良"),
"slice": D(["slice v.切片"],["bread slice","thin slice"],["Add a slice of apple to the meal."],"近义词：piece；反义词：whole；slice薄切片，piece任意小块"),
"humour": D(["humorous adj.幽默","humorously adv.风趣地"],["sense of humour","dry humour"],["Chap has good humour to cheer us up."],"近义词：funniness；反义词：sadness；humour内在风趣，funniness表面好笑"),
"quality": D(["qualify v.合格","qualified adj.合格的"],["good quality","personal quality"],["Generosity is a valuable quality."],"近义词：character；反义词：weakness；quality内在品性，character人格特质"),
"anxious": D(["anxiety n.焦虑","anxiously adv.担忧地"],["feel anxious","anxious about tests"],["I feel anxious before final exams."],"近义词：worried；反义词：calm；anxious持续不安，worried短期担忧"),
"distance": D(["distance n.距离","distant adj.遥远"],["distance oneself","distance from others"],["Don't distance your old chums."],"近义词：separate；反义词：close；distance刻意疏远，separate物理分开"),
"postpone": D(["postponement n.延期"],["postpone meeting","postpone task"],["We postpone the activity till appointed time."],"近义词：put off；反义词：advance；postpone书面正式，put off口语"),
"ordinary": D(["ordinarily adv.平常"],["ordinary student","ordinary scene"],["He is just an ordinary high school boy."],"近义词：common；反义词：special；ordinary平淡无特点，common随处可见"),
"scar": D([],["deep scar","small scar"],["The scar on his arm comes from an accident."],"近义词：mark；无反义词；scar伤口疤痕，mark普通印记"),
"dine": D(["dinner n.晚餐","dining n.用餐"],["dine together","dine at school"],["We dine with our chums after class."],"近义词：eat；反义词：fast；dine正式就餐，eat通用吃"),
"chum": D([],["old chum","close chum"],["My old chum corresponds with me weekly."],"近义词：partner；反义词：enemy；chum口语挚友，partner搭档"),
"chap": D([],["nice chap","young chap"],["This staunch chap is my desk mate."],"近义词：boy；反义词：girl；chap英式口语男生，boy通用男孩"),
"fortune": D(["fortunate adj.幸运","fortunately adv.幸运地"],["make one's fortune","big fortune"],["His proposition helps him make fortune."],"近义词：wealth；反义词：poverty；fortune大额财富，wealth整体财产"),
"drag": D(["drag n.拖累"],["drag luggage","drag heavy pot"],["Don't drag your bag on the floor."],"近义词：pull；反义词：push；drag费力拖，pull普通拉"),
"destiny": D(["destined adj.注定"],["one's destiny","personal destiny"],["Hard work changes our own destiny."],"近义词：fate；反义词：chance；destiny可改变命运，fate宿命"),
"correspond": D(["correspondence n.书信","correspondent n.通信人"],["correspond with chum","correspond regularly"],["We correspond to share daily excerpts."],"近义词：write to；反义词：meet；correspond书面通信，write to写信给"),
"proposition": D(["propose v.提议","proposal n.提案"],["small proposition","good proposition"],["His small proposition brings a fortune."],"近义词：business；反义词：hobby；proposition盈利项目，business各类生意"),
"hustle": D(["hustle n.忙碌"],["hustle for fortune","hustle at study"],["We hustle to improve our word memory."],"近义词：work hard；反义词：lazy；hustle奋力打拼，work hard普通努力"),
"staunch": D(["staunchly adv.忠实地"],["staunch chap","staunch partner"],["He is my staunch friend for years."],"近义词：loyal；反义词：unreliable；staunch坚定忠诚，loyal忠心不二"),
"partner": D(["partnership n.合作","part n.部分"],["study partner","group partner"],["My partner shares inspiring excerpts with me."],"近义词：chum；反义词：opponent；partner协作搭档，chum私人好友"),
"excerpt": D(["excerpt v.摘抄"],["short excerpt","text excerpt"],["Copy this inspiring excerpt in your journal."],"近义词：extract；反义词：whole text；excerpt短篇节选，extract专业摘录"),
"appointed": D(["appoint v.约定","appointment n.约会"],["appointed time","appointed place"],["Meet your partner at the appointed location."],"近义词：fixed；反义词：random；appointed事前商定，fixed固定不变"),
"strike": D(["stroke n.抚摸","striking adj.惊人"],["strike a cigar match","strike quickly"],["He strikes a match to light the candle."],"近义词：light；反义词：put out；strike摩擦点火，light点燃光源"),
"cigar": D([],["light a cigar","thick cigar"],["The text mentions an old man with a cigar."],""),
"plain": D(["plainly adv.简单"],["plain scene","plain style"],["Her plain speech has inspiring power."],"近义词：simple；反义词：complex；plain简约无修饰，simple易懂简单"),
"scene": D(["scenery n.风景","scenic adj.风景优美"],["daily scene","story scene"],["The scene shows two chums dining together."],"近义词：view；无反义词；scene故事场景，view视野风景"),
"bitterly": D(["bitter adj.痛苦","bitterness n.苦楚"],["cry bitterly","regret bitterly"],["He feels bitterly ashamed of mistakes."],"近义词：sadly；反义词：happily；bitterly悔恨痛苦，sadly单纯难过"),
"ashamed": D(["shame n.羞愧","shameful adj.可耻"],["feel ashamed","be ashamed of faults"],["I feel ashamed to distance my friends."],"近义词：embarrassed；反义词：proud；ashamed内心愧疚，embarrassed当场尴尬"),
"unfold": D(["fold v.折叠","unfolding n.展开"],["unfold paper","unfold the diagram"],["Unfold the sheet to see the full scene."],"近义词：open；反义词：fold；unfold展开折叠物，open打开封闭物"),
"location": D(["locate v.定位","local adj.当地"],["exact location","meeting location"],["Tell your partner the exact location."],"近义词：place；无反义词；location精准位置，place普通地方"),
"surroundings": D(["surround v.包围","surrounding adj.周围"],["school surroundings","quiet surroundings"],["Good surroundings build positive personality."],"近义词：environment；反义词：interior；surroundings周边实物，environment整体氛围"),
"personality": D(["personal adj.个人","personally adv.亲自"],["unique personality","good personality"],["Generosity is part of his personality."],"近义词：character；无反义词；personality整体性格，character内在品性"),
"atmosphere": D(["atmospheric adj.氛围的"],["warm atmosphere","class atmosphere"],["We keep a friendly atmosphere in group talks."],"近义词：mood；反义词：tension；atmosphere环境气氛，mood个人心情"),
"lose track of": D([],["lose track of friends","lose track of news"],["Don't lose track of your old chums."],""),
"thanks to": D([],["thanks to hard work","thanks to partners"],["Thanks to patience, I memorise words fast."],""),
"throw the baby out with the bathwater": D([],["don't throw the baby out with the bathwater"],["We can't throw the baby out with the bathwater."],""),
"social media": D([],["use social media","social media site"],["Teenagers often share excerpts on social media."],""),
"make one's fortune": D([],["hustle to make one's fortune"],["His small proposition helps make one's fortune."],""),
"ought to": D([],["ought to practise","ought to be patient"],["We ought to keep in touch with old chums."],""),
"turn up": D([],["turn up at location","turn up after delay"],["My staunch chap turns up at the appointed time."],""),

// ===== Unit 5 =====
"charity": D(["charitable adj.慈善的","charitably adv.慈善地"],["charity activity","charity group"],["We take part in school charity activities."],"近义词：foundation；反义词：selfishness；charity侧重救助机构，foundation基金会"),
"monarch": D(["monarchy n.君主制"],["monarch butterfly","ancient monarch"],["The text talks about an old monarch."],"近义词：king；反义词：commoner；monarch正式君主，king国王"),
"Atlantic": D([],["Atlantic Ocean","Atlantic coast"],["Many whales swim in the Atlantic Ocean."],""),
"whale": D(["whaler n.捕鲸人"],["blue whale","whale migration"],["We learn about whale migration in class."],""),
"annual": D(["annually adv.每年","yearly adj.年度的"],["annual activity","annual report"],["Our school holds an annual wildlife show."],"近义词：yearly；反义词：monthly；annual书面年度，yearly日常每年"),
"migration": D(["migrate v.迁徙","migratory adj.迁徙的"],["animal migration","yearly migration"],["We study the migration of butterflies."],"近义词：movement；反义词：stay；migration季节性迁徙，movement普通移动"),
"migrate": D(["migration n.迁徙","migratory adj.迁徙的"],["migrate south","migrate every year"],["Many birds migrate in autumn."],"近义词：travel；反义词：settle；migrate季节迁移，travel普通出行"),
"seek": D(["seeker n.寻求者"],["seek food","seek solutions"],["Caterpillars seek fresh plant leaves."],"近义词：look for；反义词：ignore；seek书面寻求，look for口语寻找"),
"professor": D(["profession n.职业","professional adj.专业的"],["biology professor","school professor"],["The professor studies butterfly migration."],"近义词：teacher；反义词：student；professor大学教授，teacher普通老师"),
"measure": D(["measurement n.尺寸","measurable adj.可测量的"],["measure distance","measure size"],["We measure the path in the wild park."],"近义词：calculate；反义词：guess；measure实物测量，calculate计算"),
"position": D(["position v.放置","positive adj.积极的"],["fixed position","exact position"],["We find the eagle's high position."],"近义词：location；反义词：displacement；position固定点位，location地点"),
"determine": D(["determination n.决心","determined adj.坚定的"],["determine position","determine time"],["We determine our observation time."],"近义词：decide；反义词：doubt；determine精准确定，decide做出选择"),
"eventually": D(["eventual adj.最终"],["eventually arrive","eventually find"],["We eventually find the monarch butterflies."],"近义词：finally；反义词：initially；eventually侧重历经波折，finally单纯最后"),
"solution": D(["solve v.解决","solvable adj.可解决的"],["find a solution","good solution"],["We discuss solutions to protect creatures."],"近义词：answer；反义词：problem；solution应对方案，answer问题答案"),
"mystery": D(["mysterious adj.神秘","mysteriously adv.神秘地"],["natural mystery","unsolved mystery"],["The butterfly migration is a natural mystery."],"近义词：puzzle；反义词：truth；mystery自然谜团，puzzle智力谜题"),
"amazing": D(["amaze v.使惊奇","amazed adj.感到吃惊"],["amazing sight","amazing creature"],["The eagle's flight is amazing."],"近义词：surprising；反义词：ordinary；amazing事物令人惊叹，surprising出人意料"),
"crash": D([],["price crash","number crash"],["The number of caterpillars may crash."],"近义词：drop；反义词：rise；crash大幅骤降，drop普通下降"),
"per cent": D([],["fifty per cent","ten per cent"],["Ninety per cent of butterflies migrate."],"近义词：percentage；无反义词；per cent符号%，percentage百分比概念"),
"destroy": D(["destruction n.破坏","destructive adj.破坏性的"],["destroy homes","destroy plants"],["Bad chemicals destroy caterpillars' food."],"近义词：ruin；反义词：protect；destroy彻底摧毁，ruin毁坏变质"),
"chemical": D(["chemistry n.化学","chemical adj.化学的"],["harmful chemical","farm chemical"],["Farm chemicals harm small creatures."],"近义词：substance；反义词：nutrient；chemical人工药剂，substance物质"),
"caterpillar": D([],["butterfly caterpillar","green caterpillar"],["A caterpillar will turn into a butterfly."],"近义词：larva；无反义词；caterpillar蝴蝶幼虫，larva幼虫统称"),
"creature": D(["create v.创造","creation n.创造物"],["wild creature","small creature"],["All wild creatures need safe homes."],"近义词：animal；反义词：human；creature一切生物，animal动物"),
"survive": D(["survival n.生存","survivor n.幸存者"],["survive winter","survive danger"],["Some butterflies survive long flights."],"近义词：live；反义词：die；survive艰难存活，live普通生活"),
"effect": D(["affect v.影响","effective adj.有效的"],["bad effect","great effect"],["Chemicals have a bad effect on insects."],"近义词：influence；无反义词；effect侧重直接影响的结果，influence侧重潜移默化的作用"),
"accommodation": D(["accommodate v.容纳"],["wild accommodation","safe accommodation"],["Trees give accommodation to small creatures."],"近义词：home；反义词：wilderness；accommodation栖息场所，home家"),
"idiom": D(["idiomatic adj.地道"],["English idiom","useful idiom"],["We learn idioms about animals today."],"近义词：phrase；反义词：word；idiom固定习语，phrase普通短语"),
"authority": D(["authoritative adj.权威"],["local authority","school authority"],["The wildlife authority protects whales."],"近义词：power；反义词：weakness；authority官方职权，power力量"),
"source": D(["source v.获取","resource n.资源"],["food source","information source"],["Plants are the food source of caterpillars."],"近义词：origin；反义词：end；source物资来源，origin起源"),
"found": D(["foundation n.基金会","founder n.创始人"],["found charity","found group"],["We found a wildlife protection charity."],"近义词：set up；反义词：destroy；found创立机构，set up搭建组织"),
"photographer": D(["photograph n.照片","photography n.摄影"],["wildlife photographer","school photographer"],["The photographer captures eagle images."],"近义词：cameraman；无反义词；photographer专业摄影师，cameraman摄像师"),
"button": D([],["screen button","digital button"],["Tap the button to view creature images."],"近义词：key；无反义词；button电子按钮，key按键"),
"recover": D(["recovery n.恢复","recoverable adj.可恢复的"],["recover strength","recover health"],["Butterflies recover energy on their way."],"近义词：get back；反义词：worsen；recover恢复状态，get back拿回物品"),
"shock": D(["shock v.使震惊","shocked adj.震惊的"],["great shock","big shock"],["It's a shock to see fewer whales."],"近义词：surprise；反义词：calm；shock强烈冲击，surprise普通意外"),
"element": D(["elementary adj.基础"],["key element","natural element"],["Food is a key element for all creatures."],"近义词：factor；反义词：whole；element基础构成要素，factor影响因素"),
"variety": D(["various adj.多样","vary v.变化"],["wide variety","great variety"],["There is a variety of wild creatures."],"近义词：diversity；反义词：sameness；variety种类多样，diversity差异性"),
"per": D([],["per year","per cent"],["We count insects per square metre."],"近义词：each；反义词：total；per计量每单位，each每一个个体"),
"encounter": D(["encounter v.偶遇"],["wild encounter","nice encounter"],["I have an encounter with an eagle."],"近义词：meeting；反义词：separation；encounter意外偶遇，meeting约定会面"),
"path": D([],["narrow path","wild path"],["We walk along a small forest path."],"近义词：track；无反义词；path林间小路，track跑道/小道"),
"breathtaking": D(["breathe v.呼吸","breath n.气息"],["breathtaking view","breathtaking scene"],["The view of migrating birds is breathtaking."],"近义词：amazing；反义词：plain；breathtaking视觉震撼，amazing通用惊人"),
"eagle": D([],["golden eagle","flying eagle"],["The eagle flies high above the path."],""),
"concentrate": D(["concentration n.专注","concentrated adj.集中的"],["concentrate on study","concentrate on observation"],["Concentrate on the butterfly movement."],"近义词：focus；反义词：distract；concentrate脑力集中，focus视线/注意力"),
"freeze": D(["frozen adj.冻住的"],["freeze with shock","freeze suddenly"],["I freeze when I see a big eagle."],"近义词：stop；反义词：move；freeze瞬间僵住，stop普通停止"),
"stare": D([],["stare at eagles","stare at images"],["Don't stare at wild animals too long."],"近义词：watch；反义词：glance；stare长久盯着，watch正常观看"),
"capture": D(["capture n.捕获","captivating adj.迷人的"],["capture images","capture scenes"],["The photographer captures whale images."],"近义词：record；反义词：miss；capture影像记录，record文字记录"),
"image": D(["imagine v.想象","imaginary adj.虚构的"],["wildlife image","clear image"],["We watch eagle images on screen."],"近义词：picture；反义词：text；image电子图像，picture图画"),
"reaction": D(["react v.反应","reactive adj.反应的"],["natural reaction","quick reaction"],["The caterpillar has a quick reaction to danger."],"近义词：response；反义词：cause；reaction本能反应，response主动回应"),
"file": D([],["animal file","digital file"],["Save all wildlife photos in a file."],"近义词：document；反义词：folder；file单份文件档案，folder文件夹"),
"monarch butterfly": D([],["study monarch butterfly","track monarch butterfly"],["We study the monarch butterfly's migration."],""),
"flow chart": D([],["draw flow chart","read flow chart"],["Draw a flow chart of butterfly growth."],""),
"kill two birds with one stone": D([],["kill two birds with one stone in study"],["We kill two birds with one stone by reading and memorising words."],""),
"hold your horses": D([],["hold your horses before observation"],["Hold your horses and don't run into the woods."],""),
"rain cats and dogs": D([],["rain cats and dogs in spring"],["It will rain cats and dogs during our field trip."],""),
"the elements": D([],["brave the elements","fight the elements"],["We must brave the rough elements on the trip."],""),
"brave the elements": D([],["brave the elements to watch whales"],["We brave the elements to see migrating birds."],""),
"after all": D([],["after all it's a natural mystery"],["Don't give up; after all it's an easy task."],""),

// ===== Unit 6 =====
"wrap": D(["wrapping n.包装材料","wrapped adj.包裹好"],["wrap up crops","wrap with cloth"],["We wrap small plants with thin cloth in winter."],"近义词：cover；反义词：unfold；wrap侧重包裹物品，cover泛指遮盖"),
"sheet": D([],["a sheet of frost","ice sheet"],["A thick sheet of frost covers the terraces."],"近义词：layer；反义词：piece；sheet大面积薄层，layer分层"),
"frost": D(["frosty adj.结霜的"],["heavy frost","frost damage"],["Frost will harm young crops in cold days."],"近义词：ice；反义词：heat；frost地面白霜，ice冰块"),
"terrace": D(["terraced adj.阶梯式的"],["mountain terrace","rice terrace"],["Many old dynasties built mountain terraces."],"近义词：farmland；反义词：desert；terrace阶梯农田，farmland普通耕地"),
"dynasty": D(["dynastic adj.王朝的"],["ancient dynasty","old dynasty"],["This text talks about an old farming dynasty."],"近义词：age；反义词：modern times；dynasty王朝时代，age年代"),
"completion": D(["complete v.完成","completely adv.完全"],["task completion","project completion"],["We celebrate the completion of the model terrace."],"近义词：finish；反义词：start；completion名词完工，finish动词结束"),
"region": D(["regional adj.区域的"],["mountain region","dry region"],["Cacti grow in dry desert regions."],"近义词：area；反义词：whole；region大片地域，area小区域"),
"therefore": D([],["therefore important","therefore useful"],["Soil is valuable, therefore we protect it."],"近义词：so；反义词：however；therefore书面连词，so口语"),
"steep": D(["steepen v.变陡"],["steep valley","steep slope"],["The path to the terrace is quite steep."],"近义词：sharp；反义词：flat；steep坡度陡，sharp尖锐"),
"soil": D(["soiled adj.沾满泥土"],["rich soil","dry soil"],["Good soil brings good crop harvests."],"近义词：earth；反义词：rock；soil种植土壤，earth泥土大地"),
"shallow": D(["shallowly adv.浅显"],["shallow basin","shallow river"],["The shallow valley river feeds crops."],"近义词：thin；反义词：deep；shallow水深浅，thin薄"),
"prevent": D(["prevention n.预防","preventive adj.预防的"],["prevent harm","prevent frost"],["We plant trees to prevent soil loss."],"近义词：stop；反义词：allow；prevent预先阻止，stop当场停下"),
"harmony": D(["harmonious adj.和谐的"],["live in harmony","natural harmony"],["People and organisms live in harmony."],"近义词：peace；反义词：conflict；harmony万物和睦，peace和平"),
"design": D(["design n.设计","designer n.设计师"],["design terraces","design system"],["Farmers design terraces to save soil."],"近义词：plan；反义词：ruin；design规划构造，plan简单计划"),
"vapour": D(["vaporous adj.多蒸汽"],["water vapour","thin vapour"],["Sun turns water into light vapour."],"近义词：steam；反义词：liquid；vapour通用水汽，steam沸水蒸汽"),
"harm": D(["harm n.伤害","harmful adj.有害"],["harm soil","harm crops"],["Bad minerals will harm living plants."],"近义词：destroy；反义词：protect；harm轻微损害，destroy彻底毁坏"),
"crop": D(["cropland n.农田"],["farm crop","rice crop"],["Farmers grow various crops on terraces."],"近义词：plant；反义词：weed；crop粮食作物，plant普通植物"),
"agriculture": D(["agricultural adj.农业"],["modern agriculture","green agriculture"],["We learn about ancient agriculture in class."],"近义词：farming；反义词：industry；agriculture专业农业，farming耕种"),
"replace": D(["replacement n.替代品"],["replace material","replace soil"],["We replace old branches with new ones."],"近义词：change；反义词：keep；replace替换旧物，change单纯更换"),
"material": D(["material adj.物质"],["building material","natural material"],["Wood is a common natural material."],"近义词：substance；反义词：product；material原材料，substance物质"),
"mineral": D(["mineral adj.矿物"],["natural mineral","rich mineral"],["Soil contains useful natural minerals."],"近义词：rock；反义词：plant；mineral地下矿产，rock岩石"),
"consumer": D(["consume v.消耗","consumption n.消耗"],["food consumer","green consumer"],["We as consumers protect farm soil."],"近义词：buyer；反义词：producer；consumer购买使用者，buyer买家"),
"priority": D(["prior adj.优先"],["top priority","main priority"],["Protecting soil is our top priority."],"近义词：task；反义词：unimportant；priority首要事项，task普通任务"),
"beauty": D(["beautiful adj.美丽","beautifully adv.优美"],["natural beauty","valley beauty"],["The canyon shows amazing natural beauty."],"近义词：charm；反义词：ugliness；beauty视觉美，charm魅力"),
"barrier": D([],["natural barrier","soil barrier"],["Trees act as a barrier against frost."],"近义词：block；反义词：gate；barrier阻隔屏障，block障碍物"),
"reef": D([],["coral reef","sea reef"],["Many living organisms live on sea reefs."],"近义词：rock；反义词：sand；reef海中礁石，rock岩石"),
"structure": D(["structural adj.结构"],["soil structure","terrace structure"],["We study the structure of mountain terraces."],"近义词：form；反义词：mess；structure固定构造，form外形"),
"living": D(["live v.生存","alive adj.活着"],["living organism","living plant"],["All living things need water and soil."],"近义词：alive；反义词：dead；living作定语，alive作表语"),
"organism": D(["organ n.器官","organic adj.有机"],["small organism","living organism"],["Herbs are small living organisms."],"近义词：creature；反义词：object；organism有机生物，creature动物"),
"observatory": D(["observe v.观测","observation n.观察"],["mountain observatory","sky observatory"],["The observatory sits on a grand hill."],"反义词：lab；observatory天文观测台，lab实验室"),
"basin": D([],["river basin","dry basin"],["Water flows into the mountain basin."],"近义词：valley；反义词：hill；basin四周低盆地，valley两山山谷"),
"grand": D(["grandly adv.宏伟","grandeur n.宏伟"],["grand canyon","grand terrace"],["The grand valley attracts visitors."],"近义词：great；反义词：tiny；grand规模宏大，great普通伟大"),
"canyon": D([],["deep canyon","grand canyon"],["We learn about a famous river canyon."],"近义词：valley；反义词：plain；canyon深邃大峡谷，valley浅山谷"),
"valley": D([],["narrow valley","green valley"],["Sunflowers grow in the warm valley."],"近义词：basin；反义词：mountain；valley两山之间，basin封闭盆地"),
"narrow": D(["narrow v.收窄","narrowly adv.勉强"],["narrow channel","narrow path"],["The tunnel is quite narrow inside."],"近义词：thin；反义词：wide；narrow空间窄，thin薄"),
"platform": D([],["stone platform","high platform"],["The observatory stands on a stone platform."],"近义词：stage；无反义词；platform观景高台，stage舞台"),
"waterfall": D([],["small waterfall","valley waterfall"],["A beautiful waterfall runs down the steep hill."],"近义词：stream；反义词：lake；waterfall跌落瀑布，stream溪流"),
"thunder": D(["thunder n.雷声","thundery adj.雷雨的"],["thunder loudly","thunder in valley"],["It will thunder before heavy rain."],"反义词：sunshine；thunder打雷，sunshine晴天"),
"channel": D([],["sea channel","narrow channel"],["Ships sail through the wide sea channel."],"近义词：waterway；反义词：land；channel海上航道，waterway水路"),
"tunnel": D([],["mountain tunnel","long tunnel"],["We walk through a dark mountain tunnel."],"近义词：passage；无反义词；tunnel地下通道，passage小道"),
"camel": D([],["desert camel","wild camel"],["Camels travel across dry deserts."],""),
"desert": D(["deserted adj.荒芜"],["dry desert","vast desert"],["Few crops grow on dry desert land."],"近义词：wasteland；反义词：farmland；desert干旱荒漠，wasteland荒地"),
"sail": D(["sail n.船帆","sailor n.水手"],["sail across channel","sail by reef"],["We sail to the island to study reefs."],"近义词：travel；无反义词；sail水上航行，travel通用出行"),
"climate": D(["climatic adj.气候"],["dry climate","warm climate"],["Valleys have a pleasant warm climate."],"近义词：weather；无反义词；climate长期气候，weather单日天气"),
"inside": D(["inside adj.内部","outside adv.外面"],["stay inside","walk inside"],["We stay inside when it thunders."],"近义词：indoors；反义词：outside；inside通用，indoors室内专用"),
"publish": D(["public adj.公共","publication n.出版物"],["publish books","publish reports"],["Experts publish articles about agriculture."],"近义词：release；反义词：hide；publish出版发行，release发布"),
"sunflower": D([],["plant sunflower","tall sunflower"],["We grow sunflowers on the terrace."],"近义词：flower；反义词：weed；sunflower特定花卉，flower花"),
"expert": D(["expert n.专家","expertly adv.专业"],["expert farmer","expert researcher"],["He is an expert on valley agriculture."],"近义词：skilled；反义词：unskilled；expert专业精通，skilled有技巧"),
"branch": D([],["tree branch","dry branch"],["We collect dry branches as materials."],"近义词：twig；反义词：trunk；branch大树枝，twig细嫩枝"),
"rent": D(["rent n.租金","rental adj.租赁"],["rent land","rent rooftop"],["We rent a small rooftop to grow herbs."],"近义词：hire；反义词：own；rent长期租用，hire短期租借"),
"rooftop": D([],["flat rooftop","high rooftop"],["We plant pleasant herbs on the rooftop."],"近义词：roof；反义词：ground；rooftop屋顶平面，roof屋顶整体"),
"thistle": D([],["wild thistle","dry thistle"],["Thistle grows in dry desert regions."],"近义词：weed；反义词：crop；thistle野生杂草蓟"),
"limited": D(["limit v.限制","limit n.限度"],["limited mineral","limited space"],["The rooftop space is quite limited."],"近义词：little；反义词：endless；limited受限制，little数量少"),
"benefit": D(["benefit v.有益于","beneficial adj.有益"],["great benefit","real benefit"],["Green fingers bring great farming benefits."],"近义词：advantage；反义词：harm；benefit实际益处，advantage优势"),
"herb": D(["herbal adj.草本"],["fresh herb","green herb"],["We plant fragrant herbs on the rooftop."],"近义词：plant；反义词：crop；herb调味草本，plant普通植物"),
"pleasant": D(["pleasure n.愉悦","pleasantly adv.宜人"],["pleasant climate","pleasant flavour"],["The valley has a very pleasant climate."],"近义词：nice；反义词：unpleasant；pleasant环境宜人，nice通用好"),
"flavour": D([],["herb flavour","natural flavour"],["This herb has a special light flavour."],"近义词：taste；反义词：odour；flavour食物风味，taste味觉感受"),
"energy": D(["energetic adj.精力充沛"],["natural energy","plant energy"],["Sun gives energy to all crops."],"近义词：power；反义词：weakness；energy生物活力，power力量"),
"system": D(["systematic adj.系统"],["farming system","soil system"],["Old dynasties created terrace systems."],"近义词：structure；反义词：mess；system成套体系，structure构造"),
"green fingers": D([],["have green fingers","show green fingers"],["Our biology teacher has green fingers."],"")

};
